The BioCro C++ Library: /github/workspace/source/src/module_library/CanA.h File Reference
CanA.h File Reference
Functions
struct ET_Str EvapoTrans2 (double Rad, double Iave, double Airtemperature, double RH, double WindSpeed, double LeafAreaIndex, double CanopyHeight, double stomatacond, double leafw, int eteq)
Function Documentation
EvapoTrans2()
struct ET_Str EvapoTrans2 (double Rad, double Iave, double Airtemperature, double RH, double WindSpeed, double LeafAreaIndex, double CanopyHeight, double stomatacond, double leafw, int eteq)
Definition at line 325 of file AuxBioCro.cpp.
Referenced by CanAC(), ed_evapotrans2::do_operation(), ed_canac_leaf::do_operation(), and c4_leaf_photosynthesis::do_operation().