The BioCro C++ Library: ten_layer_canopy_integrator Class Reference
ten_layer_canopy_integrator Class Reference
A child class of multilayer_canopy_integrator where the number of layers has been defined. Instances of this class can be created using the module factory.
#include <multilayer_canopy_integrator.h>
Public Member Functions
ten_layer_canopy_integrator (const std::unordered_map< std::string, double > *input_parameters, std::unordered_map< std::string, double > *output_parameters)
Public Member Functions inherited from multilayer_canopy_integrator
multilayer_canopy_integrator (const std::string &module_name, const int &nlayers, const std::unordered_map< std::string, double > *input_parameters, std::unordered_map< std::string, double > *output_parameters)
Static Public Member Functions
static std::vector< std::string > get_inputs ()
static std::vector< std::string > get_leaf_classes ()
static std::vector< std::string > get_multiclass_multilayer_outputs ()
static std::vector< std::string > get_pure_multilayer_outputs ()
static std::vector< std::string > get_outputs ()
Static Public Member Functions inherited from multilayer_canopy_integrator
static std::vector< std::string > get_inputs (int nlayers)
Define all inputs required by the module, adding layer suffixes as required.
static std::vector< std::string > get_outputs (int nlayers)
Define all outputs produced by the module.
Private Member Functions
void do_operation () const
Static Private Attributes
static const int nlayers = 10
Additional Inherited Members
Protected Member Functions inherited from multilayer_canopy_integrator
void run () const
Detailed Description
A child class of multilayer_canopy_integrator where the number of layers has been defined. Instances of this class can be created using the module factory.
Definition at line 186 of file multilayer_canopy_integrator.h.
Constructor & Destructor Documentation
ten_layer_canopy_integrator()
ten_layer_canopy_integrator (const std::unordered_map< std::string, double > * input_parameters, std::unordered_map< std::string, double > * output_parameters) inline
Definition at line 189 of file multilayer_canopy_integrator.h.
Member Function Documentation
do_operation()
void do_operation () const private virtual
Reimplemented from multilayer_canopy_integrator.
Definition at line 223 of file multilayer_canopy_integrator.h.
References multilayer_canopy_integrator::run().
get_inputs()
std::vector< std::string > get_inputs () static
Definition at line 213 of file multilayer_canopy_integrator.h.
References multilayer_canopy_integrator::get_inputs(), and nlayers.
get_leaf_classes()
static std::vector<std::string> get_leaf_classes () static
get_multiclass_multilayer_outputs()
static std::vector<std::string> get_multiclass_multilayer_outputs () static
get_outputs()
std::vector< std::string > get_outputs () static
Definition at line 218 of file multilayer_canopy_integrator.h.
References multilayer_canopy_integrator::get_outputs(), and nlayers.
get_pure_multilayer_outputs()
static std::vector<std::string> get_pure_multilayer_outputs () static
Member Data Documentation
nlayers
const int nlayers = 10 static private
Definition at line 206 of file multilayer_canopy_integrator.h.
Referenced by get_inputs(), and get_outputs().
The documentation for this class was generated from the following file:
/github/workspace/source/src/module_library/multilayer_canopy_integrator.h