var hierarchy =
[
    [ "c3_str", "structc3__str.html", null ],
    [ "c4_str", "structc4__str.html", null ],
    [ "Can_Str", "struct_can___str.html", null ],
    [ "collatz_result", "structcollatz__result.html", null ],
    [ "crop_phenology", "structcrop__phenology.html", null ],
    [ "dbp_str", "structdbp__str.html", null ],
    [ "DerivModule", null, [
      [ "aba_decay", "classaba__decay.html", null ],
      [ "bucket_soil_drainage", "classbucket__soil__drainage.html", null ],
      [ "empty_senescence", "classempty__senescence.html", null ],
      [ "flowering", "classflowering.html", null ],
      [ "gamma_oscillator", "classgamma__oscillator.html", null ],
      [ "grimm_soybean_flowering", "classgrimm__soybean__flowering.html", null ],
      [ "harmonic_oscillator", "classharmonic__oscillator.html", null ],
      [ "magic_clock", "classmagic__clock.html", null ],
      [ "night_and_day_trackers", "classnight__and__day__trackers.html", null ],
      [ "nr_ex", "classnr__ex.html", null ],
      [ "one_layer_soil_profile", "classone__layer__soil__profile.html", null ],
      [ "one_layer_soil_profile_derivatives", "classone__layer__soil__profile__derivatives.html", null ],
      [ "P1", "class_p1.html", null ],
      [ "P10", "class_p10.html", null ],
      [ "P100", "class_p100.html", null ],
      [ "P1000", "class_p1000.html", null ],
      [ "partitioning_growth", "classpartitioning__growth.html", null ],
      [ "phase_clock", "classphase__clock.html", null ],
      [ "poincare_clock", "classpoincare__clock.html", null ],
      [ "pokhilko_circadian_clock", "classpokhilko__circadian__clock.html", null ],
      [ "position_oscillator", "classposition__oscillator.html", null ],
      [ "reaction", "classreaction.html", null ],
      [ "song_flowering", "classsong__flowering.html", null ],
      [ "test_derivs", "classtest__derivs.html", null ],
      [ "thermal_time_and_frost_senescence", "classthermal__time__and__frost__senescence.html", null ],
      [ "thermal_time_beta", "classthermal__time__beta.html", null ],
      [ "thermal_time_bilinear", "classthermal__time__bilinear.html", null ],
      [ "thermal_time_linear", "classthermal__time__linear.html", null ],
      [ "thermal_time_linear_extended", "classthermal__time__linear__extended.html", null ],
      [ "thermal_time_senescence", "classthermal__time__senescence.html", null ],
      [ "thermal_time_trilinear", "classthermal__time__trilinear.html", null ],
      [ "two_layer_soil_profile", "classtwo__layer__soil__profile.html", null ],
      [ "utilization_growth", "classutilization__growth.html", null ],
      [ "utilization_senescence", "classutilization__senescence.html", null ],
      [ "velocity_oscillator", "classvelocity__oscillator.html", null ]
    ] ],
    [ "ed_collatz_assimilation", "classed__collatz__assimilation.html", null ],
    [ "ET_Str", "struct_e_t___str.html", null ],
    [ "frostParms", "structfrost_parms.html", null ],
    [ "Light_model", "struct_light__model.html", null ],
    [ "Light_profile", "struct_light__profile.html", null ],
    [ "crop_phenology::minerals1", "structcrop__phenology_1_1minerals1.html", null ],
    [ "module_wrapper_factory", "classmodule__wrapper__factory.html", null ],
    [ "nitroParms", "structnitro_parms.html", null ],
    [ "rd_str", "structrd__str.html", null ],
    [ "seqRD_str", "structseq_r_d__str.html", null ],
    [ "soilML_str", "structsoil_m_l__str.html", null ],
    [ "soilText_str", "structsoil_text__str.html", null ],
    [ "SteadyModule", null, [
      [ "ball_berry_module", "classball__berry__module.html", null ],
      [ "big_leaf_multilayer_canopy", "classbig__leaf__multilayer__canopy.html", null ],
      [ "biomass_leaf_n_limitation", "classbiomass__leaf__n__limitation.html", null ],
      [ "c3_canopy", "classc3__canopy.html", null ],
      [ "c3_leaf_photosynthesis", "classc3__leaf__photosynthesis.html", null ],
      [ "c4_canopy", "classc4__canopy.html", null ],
      [ "c4_leaf_photosynthesis", "classc4__leaf__photosynthesis.html", null ],
      [ "canac_with_collatz", "classcanac__with__collatz.html", null ],
      [ "collatz_leaf", "classcollatz__leaf.html", null ],
      [ "ed_apply_stomatal_water_stress_via_assimilation", "classed__apply__stomatal__water__stress__via__assimilation.html", null ],
      [ "ed_apply_stomatal_water_stress_via_conductance", "classed__apply__stomatal__water__stress__via__conductance.html", null ],
      [ "ed_ball_berry", "classed__ball__berry.html", null ],
      [ "ed_boundary_conductance_max", "classed__boundary__conductance__max.html", null ],
      [ "ed_boundary_conductance_quadrature", "classed__boundary__conductance__quadrature.html", null ],
      [ "ed_c4photo", "classed__c4photo.html", null ],
      [ "ed_canac_leaf", "classed__canac__leaf.html", null ],
      [ "ed_collatz_c4_assimilation", "classed__collatz__c4__assimilation.html", null ],
      [ "ed_evapotrans2", "classed__evapotrans2.html", null ],
      [ "ed_gas_concentrations", "classed__gas__concentrations.html", null ],
      [ "module_base", "classed__leaf__photosynthesis_1_1module__base.html", [
        [ "module_base", "classed__leaf__photosynthesis__nr_1_1module__base.html", [
          [ "ed_c4_leaf_photosynthesis", "classed__c4__leaf__photosynthesis.html", null ]
        ] ]
      ] ],
      [ "ed_long_wave_energy_loss", "classed__long__wave__energy__loss.html", null ],
      [ "ed_nikolov_conductance_forced", "classed__nikolov__conductance__forced.html", null ],
      [ "ed_nikolov_conductance_free", "classed__nikolov__conductance__free.html", null ],
      [ "ed_penman_monteith_leaf_temperature", "classed__penman__monteith__leaf__temperature.html", null ],
      [ "ed_rh_to_mole_fraction", "classed__rh__to__mole__fraction.html", null ],
      [ "ed_stomata_water_stress_linear", "classed__stomata__water__stress__linear.html", null ],
      [ "ed_water_vapor_properties", "classed__water__vapor__properties.html", null ],
      [ "fake_solar", "classfake__solar.html", null ],
      [ "flowering_calculator", "classflowering__calculator.html", null ],
      [ "FvCB", "class_fv_c_b.html", null ],
      [ "golden_ratio_hyperbola", "classgolden__ratio__hyperbola.html", null ],
      [ "grimm_soybean_flowering_calculator", "classgrimm__soybean__flowering__calculator.html", null ],
      [ "harmonic_energy", "classharmonic__energy.html", null ],
      [ "hyperbola_2d", "classhyperbola__2d.html", null ],
      [ "incident_shortwave_from_ground_par", "classincident__shortwave__from__ground__par.html", null ],
      [ "leaf_shape_factor", "classleaf__shape__factor.html", null ],
      [ "leaf_water_stress_exponential", "classleaf__water__stress__exponential.html", null ],
      [ "light_from_solar", "classlight__from__solar.html", null ],
      [ "linear_vmax_from_leaf_n", "classlinear__vmax__from__leaf__n.html", null ],
      [ "Module_1", "class_module__1.html", null ],
      [ "Module_2", "class_module__2.html", null ],
      [ "Module_3", "class_module__3.html", null ],
      [ "multilayer_canopy_integrator", "classmultilayer__canopy__integrator.html", [
        [ "ten_layer_canopy_integrator", "classten__layer__canopy__integrator.html", null ]
      ] ],
      [ "multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >", "classmultilayer__canopy__photosynthesis.html", null ],
      [ "multilayer_canopy_photosynthesis< ten_layer_canopy_properties, c3_leaf_photosynthesis >", "classmultilayer__canopy__photosynthesis.html", [
        [ "ten_layer_c3_canopy", "classten__layer__c3__canopy.html", null ]
      ] ],
      [ "multilayer_canopy_photosynthesis< ten_layer_canopy_properties, c4_leaf_photosynthesis >", "classmultilayer__canopy__photosynthesis.html", [
        [ "ten_layer_c4_canopy", "classten__layer__c4__canopy.html", null ]
      ] ],
      [ "multilayer_canopy_properties", "classmultilayer__canopy__properties.html", [
        [ "ten_layer_canopy_properties", "classten__layer__canopy__properties.html", null ]
      ] ],
      [ "no_leaf_resp_partitioning_growth_calculator", "classno__leaf__resp__partitioning__growth__calculator.html", null ],
      [ "oscillator_clock_calculator", "classoscillator__clock__calculator.html", null ],
      [ "parameter_calculator", "classparameter__calculator.html", null ],
      [ "partitioning_coefficient_selector", "classpartitioning__coefficient__selector.html", null ],
      [ "partitioning_growth_calculator", "classpartitioning__growth__calculator.html", null ],
      [ "penman_monteith_leaf_temperature", "classpenman__monteith__leaf__temperature.html", null ],
      [ "penman_monteith_transpiration", "classpenman__monteith__transpiration.html", null ],
      [ "priestley_transpiration", "classpriestley__transpiration.html", null ],
      [ "shortwave_atmospheric_scattering", "classshortwave__atmospheric__scattering.html", null ],
      [ "soil_evaporation", "classsoil__evaporation.html", null ],
      [ "soil_type_selector", "classsoil__type__selector.html", null ],
      [ "solar_zenith_angle", "classsolar__zenith__angle.html", null ],
      [ "stomata_water_stress_exponential", "classstomata__water__stress__exponential.html", null ],
      [ "stomata_water_stress_linear", "classstomata__water__stress__linear.html", null ],
      [ "stomata_water_stress_linear_and_aba_response", "classstomata__water__stress__linear__and__aba__response.html", null ],
      [ "stomata_water_stress_sigmoid", "classstomata__water__stress__sigmoid.html", null ],
      [ "test_calc_state", "classtest__calc__state.html", null ],
      [ "test_module", "classtest__module.html", null ],
      [ "utilization_growth_calculator", "classutilization__growth__calculator.html", null ],
      [ "utilization_senescence_calculator", "classutilization__senescence__calculator.html", null ],
      [ "water_vapor_properties_from_air_temperature", "classwater__vapor__properties__from__air__temperature.html", null ]
    ] ],
    [ "ws_str", "structws__str.html", null ]
];