BioCro: /github/workspace/source/src/module_library/BioCro.h File Reference
BioCro.h File Reference
#include "AuxBioCro.h"
Data Structures
struct Light_model
Functions
double cos_zenith_angle (const double latitude, const int day_of_year, const double hour_of_day)
struct Can_Str CanAC (double LAI, int DOY, double hr, double solarR, double Temp, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double theta, double kd, double chil, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double upperT, double lowerT, const struct nitroParms &nitroP, double leafwidth, int eteq, double StomataWS, int water_stress_approach)
struct Can_Str c3CanAC (double LAI, int DOY, double hr, double solarR, double Temp, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Jmax, double Rd, double Catm, double o2, double b0, double b1, double theta, double kd, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double chil, double StomataWS, double growth_respiration_fraction, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation)
double resp (double comp, double mrc, double temp)
struct ws_str watstr (double precipit, double evapo, double cws, double soildepth, double fieldc, double wiltp, double phi1, double phi2, double soil_saturation_capacity, double soil_sand_content, double Ks, double air_entry, double b)
double SoilEvapo (double LAI, double k, double AirTemp, double DirectRad, double awc, double fieldc, double wiltp, double winds, double RelH, double rsec, double soil_clod_size, double soil_reflectance, double soil_transmission, double specific_heat, double stefan_boltzman)
struct soilML_str soilML (double precipit, double transp, double *cws, double soildepth, double *depths, double soil_field_capacity, double soil_wilting_point, double soil_saturation_capacity, double soil_air_entry, double soil_saturated_conductivity, double soil_b_coefficient, double soil_sand_content, double phi1, double phi2, int wsFun, int layers, double rootDB, double LAI, double k, double AirTemp, double IRad, double winds, double RelH, int hydrDist, double rfl, double rsec, double rsdf, double soil_clod_size, double soil_reflectance, double soil_transmission, double specific_heat, double stefan_boltzman)
void RHprof (double RH, int nlayers, double *relative_humidity_profile)
void WINDprof (double WindSpeed, double LAI, int nlayers, double *wind_speed_profile)
struct Light_profile sunML (double Idir, double Idiff, double LAI, int nlayers, double cosTheta, double kd, double chil, double heightf)
struct Light_model lightME (double lat, int DOY, double td)
struct FL_str FmLcFun (double Lig, double Nit)
struct flow_str flow (double *SC, double CNratio, double A, double Lc, double Tm, double resp, int kno, double Ks[8])
double AbiotEff (double smoist, double stemp)
struct ET_Str EvapoTrans2 (double Rad, double Iave, double Airtemperature, double RH, double WindSpeed, double LeafAreaIndex, double CanopyHeight, double stomatacond, double leafw, int eteq)
struct ET_Str c3EvapoTrans (double Itot, double Airtemperature, double RH, double WindSpeed, double CanopyHeight, double stomtal_conductance)
Function Documentation
AbiotEff()
double AbiotEff (double smoist, double stemp)
c3CanAC()
struct Can_Str c3CanAC (double LAI, int DOY, double hr, double solarR, double Temp, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Jmax, double Rd, double Catm, double o2, double b0, double b1, double theta, double kd, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double chil, double StomataWS, double growth_respiration_fraction, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation)
Definition at line 1 of file c3CanAC.cpp.
 {
         struct Light_model light_model = lightME(lat, DOY, hr);
     double Idir = light_model.direct_irradiance_fraction * solarR;
     double Idiff = light_model.diffuse_irradiance_fraction * solarR;
     double cosTh = light_model.cosine_zenith_angle;
     struct Light_profile light_profile = sunML(Idir, Idiff, LAI, nlayers, cosTh, kd, chil, heightf);
 //    if(LAI < 0) throw std::range_error("Thrown in c3CanAC: LAI is negative."); MLM removed this error message 04/22/2020; can cause issues with integration
     double LAIc = LAI / nlayers;
     double relative_humidity_profile[nlayers];
     RHprof(RH, nlayers, relative_humidity_profile);
     double wind_speed_profile[nlayers];
     WINDprof(WindSpeed, LAI, nlayers, wind_speed_profile);
     double leafN_profile[nlayers];
     LNprof(leafN, LAI, nlayers, kpLN, leafN_profile);
     double CanopyA = 0.0, CanopyT = 0.0, GCanopyA = 0.0;
     for (int i = 0; i < nlayers; ++i)
     {
         int current_layer = nlayers - 1 - i;
                 double leafN_lay = leafN_profile[current_layer];
         double vmax1;
         if (lnfun == 0) {
                         vmax1 = Vmax;
                 } else {
                         vmax1 = leafN_lay * lnb1 + lnb0;
                 }
         double relative_humidity = relative_humidity_profile[current_layer];
         double layer_wind_speed = wind_speed_profile[current_layer];
         double IDir = light_profile.direct_irradiance[current_layer];  // micromole / m^2 / s
         double Itot = light_profile.total_irradiance[current_layer];  // micromole / m^2 / s
         double pLeafsun = light_profile.sunlit_fraction[current_layer];  // dimensionless
         double CanHeight = light_profile.height[current_layer];  // meters
         double Leafsun = LAIc * pLeafsun;
         double stomatal_conductance_direct = c3photoC(IDir, air_temperature, relative_humidity, vmax1, Jmax, Rd, b0, b1, Catm, o2, theta, StomataWS, water_stress_approach, electrons_per_carboxylation, electrons_per_oxygenation).Gs;  // mmol / m^2 / s. Estimate stomatal_conductance by assuming the leaf has the same temperature as the air.
         struct ET_Str et_direct = c3EvapoTrans(Itot, air_temperature, relative_humidity, layer_wind_speed, CanHeight, stomatal_conductance_direct);
         double leaf_temperature_Idir = air_temperature + et_direct.Deltat;
         struct c3_str temp_photo_results = c3photoC(IDir, leaf_temperature_Idir, relative_humidity, vmax1, Jmax, Rd, b0, b1, Catm, o2, theta, StomataWS, water_stress_approach, electrons_per_carboxylation, electrons_per_oxygenation);
         double AssIdir = temp_photo_results.Assim;
         double GAssIdir = temp_photo_results.GrossAssim;
         double IDiff = light_profile.diffuse_irradiance[current_layer];  // micromole / m^2 /s
         double pLeafshade = light_profile.shaded_fraction[current_layer];  // dimensionless
         double Leafshade = LAIc * pLeafshade;
         double stomatal_conductance_diffuse = c3photoC(IDiff, air_temperature, relative_humidity, vmax1, Jmax, Rd, b0, b1, Catm, o2, theta, StomataWS, water_stress_approach, electrons_per_carboxylation, electrons_per_oxygenation).Gs;  // mmol / m^2 / s. Estimate stomatal_conductance by assuming the leaf has the same temperature as the air.
         struct ET_Str et_diffuse = c3EvapoTrans(Itot, air_temperature, relative_humidity, layer_wind_speed, CanHeight, stomatal_conductance_diffuse);
         double leaf_temperature_Idiffuse = air_temperature + et_diffuse.Deltat;
         temp_photo_results = c3photoC(IDiff, leaf_temperature_Idiffuse, relative_humidity, vmax1, Jmax, Rd, b0, b1, Catm, o2, theta, StomataWS, water_stress_approach, electrons_per_carboxylation, electrons_per_oxygenation);
         double AssIdiff = temp_photo_results.Assim;
         double GAssIdiff = temp_photo_results.GrossAssim;
         CanopyA += Leafsun * AssIdir + Leafshade * AssIdiff;
         GCanopyA += Leafsun * GAssIdir + Leafshade * GAssIdiff;
         CanopyT += Leafsun * et_direct.TransR + Leafshade * et_diffuse.TransR;
     }
    /* CanopyA has units of micromole CO2 / m^2 / s.
     * 3600 s / hr
     * 10^-6 mol / micromole
     * 30 g / mol - grams of C6H12O6 (glucose) incorporated into dry biomass per mole of CO2
     * 10^-6 Mg / g
     * 10000 m^2 / ha
     */
     const double cf = 3600 * 1e-6 * 30 * 1e-6 * 10000;
    /* CanopyT has units of mmol H2O / m^2 / s.
     * 3600 s / hr
     * 10^-3 mol / mmol
     * 18 g / (mol H2O)
     * 10^-6 Mg / g
     * 10000 m^2 / ha
     */
     const double cf2 = 3600 * 1e-3 * 18 * 1e-6 * 10000;
     struct Can_Str ans;
     ans.Assim = cf * CanopyA * (1.0 - growth_respiration_fraction);  // Mg / ha / hr.
     ans.Trans = cf2 * CanopyT;   // Mg / ha / hr.
     ans.GrossAssim = cf * GCanopyA;
     return ans;
 }
References c3_str::Assim, Can_Str::Assim, c3EvapoTrans(), c3photoC(), Light_model::cosine_zenith_angle, ET_Str::Deltat, Light_profile::diffuse_irradiance, Light_model::diffuse_irradiance_fraction, Light_profile::direct_irradiance, Light_model::direct_irradiance_fraction, c3_str::GrossAssim, Can_Str::GrossAssim, c3_str::Gs, Light_profile::height, lightME(), LNprof(), RHprof(), Light_profile::shaded_fraction, Light_profile::sunlit_fraction, sunML(), Light_profile::total_irradiance, Can_Str::Trans, ET_Str::TransR, and WINDprof().
c3EvapoTrans()
struct ET_Str c3EvapoTrans (double Itot, double Airtemperature, double RH, double WindSpeed, double CanopyHeight, double stomtal_conductance)
Definition at line 1 of file c3EvapoTrans.cpp.
 {
     constexpr double StefanBoltzmann = 5.67037e-8;       // J / m^2 / s^1 / K^4
     constexpr double tau = 0.2;                          // dimensionless. Leaf transmission coefficient.
     constexpr double LeafReflectance = 0.2;              // dimensionless
     constexpr double SpecificHeat = 1010;                // J / kg / K
     constexpr double kappa = 0.41;                       // dimensionless. von Karmon's constant. Thornley and Johnson pgs 414 and 416.
     constexpr double WindSpeedHeight = 5;                // meters
     constexpr double dCoef = 0.77;                       // dimensionless
     constexpr double ZetaCoef = 0.026;                   // dimensionless
     constexpr double ZetaMCoef = 0.13;                   // dimensionless
     const double Zeta = ZetaCoef * CanopyHeight;         // meters
     const double Zetam = ZetaMCoef * CanopyHeight;       // meters
     const double d = dCoef * CanopyHeight;               // meters
     constexpr double molar_mass_of_water = 18.01528e-3;  // kg / mol
     constexpr double R = 8.314472;                       // joule / kelvin / mole.
     //constexpr double atmospheric_pressure = 101325;      // Pa
     constexpr double joules_per_micromole_PAR = 0.235;   // J / micromole. For the wavelengths that make up PAR in sunlight, one mole of photons has, on average, approximately 2.35 x 10^5 joules:
     if (CanopyHeight < 0.1)
         CanopyHeight = 0.1;
     const double DdryA = TempToDdryA(air_temperature);  // kg / m^3
     const double LHV = TempToLHV(air_temperature);  // J / kg
     const double SlopeFS = TempToSFS(air_temperature);  // kg / m^3 / K. It is also kg / m^3 / degrees C since it's a change in temperature.
     const double SWVP = saturation_vapor_pressure(air_temperature);  // Pa
     constexpr double volume_of_one_mole_of_air = 24.39e-3;  // m^3 / mol. TODO: This is for about 20 degrees C at 100000 Pa. Change it to use the model state. (1 * R * temperature) / pressure
     double conductance_in_m_per_s = stomatal_conductance * 1e-3 * volume_of_one_mole_of_air;  // m / s
     if (conductance_in_m_per_s <= 0) /* Prevent errors due to extremely low Layer conductance. */
         conductance_in_m_per_s = 0.01;
     if (RH > 1)
         throw std::range_error("Thrown in c3EvapoTrans: RH (relative humidity) is greater than 1.");
     /* SOLAR RADIATION COMPONENT*/
     const double totalradiation = Itot * joules_per_micromole_PAR;  // W / m^2.
     const double SWVC = SWVP / R / (air_temperature + 273.15) * molar_mass_of_water;  // kg / m^3. Convert from vapor pressure to vapor density using the ideal gas law. This is approximately right for temperatures what won't kill plants.
     if (SWVC < 0)
         throw std::range_error("Thrown in c3EvapoTrans: SWVC is less than 0.");
     const double PsycParam = DdryA * SpecificHeat / LHV;  // kg / m^3 / K
     const double DeltaPVa = SWVC * (1 - RH);  // kg / m^3
     const double Ja = 2 * totalradiation * (1 - LeafReflectance - tau) / (1 - tau);  // W / m^2
     /* AERODYNAMIC COMPONENT */
     if (WindSpeed < 0.5) WindSpeed = 0.5;
     /* Calculation of ga */
     /* According to thornley and Johnson pg. 416 */
     const double ga0 = pow(kappa, 2) * WindSpeed;                     // m / s
     const double ga1 = log((WindSpeedHeight + Zeta - d) / Zeta);      // dimensionless
     const double ga2 = log((WindSpeedHeight + Zetam - d) / Zetam);    // dimensionless
     const double ga = ga0 / (ga1 * ga2);                              // m / s
     if (ga < 0)
         throw std::range_error("Thrown in c3EvapoTrans: ga is less than zero.");
     /* Temperature of the leaf according to Campbell and Norman (1998) Chp 4.*/
     /* This version is non-iterative and an approximation*/
     /* Stefan-Boltzmann law: B = sigma * T^4. where sigma is the Boltzmann constant: 5.67 * 1e-8 W m^-2 K^-4. */
     /* From Table A.3 in Campbell and Norman.*/
     /* This is the original from WIMOVAC*/
     double Deltat = 0.01;  // degrees C
     //std::cout << "Evapotrans inputs: " << Itot << ", " << air_temperature << ", " << RH << ", " << WindSpeed << ", " << CanopyHeight << ", " << stomatal_conductance << "\n";
     //std::cout << "Delta t in c3EvapoTrans, initial: " << Deltat << "\n";
     double PhiN;
     {
         double ChangeInLeafTemp = 10;  // degrees C
         for (int Counter = 0; (ChangeInLeafTemp > 0.5) && (Counter <= 10); ++Counter) {
             double OldDeltaT = Deltat;
             double rlc = 4.0 * StefanBoltzmann * pow(273.0 + air_temperature, 3.0) * Deltat;  // W / m^2
             PhiN = Ja - rlc;  // W / m^2
             double TopValue = PhiN * (1 / ga + 1 / conductance_in_m_per_s) - LHV * DeltaPVa;  // J / m^3
             double BottomValue = LHV * (SlopeFS + PsycParam * (1 + ga / conductance_in_m_per_s));  // J / m^2 / K
             Deltat = TopValue / BottomValue;  // kelvin. It is also degrees C, because it is a temperature difference.
             Deltat = std::min(std::max(Deltat, -5.0), 5.0);
             ChangeInLeafTemp = fabs(OldDeltaT - Deltat);  // kelvin. It is also degrees C, because it is a temperature difference.
         }
     }
     //std::cout << "Delta t in c3EvapoTrans, final: " << Deltat << "\n";
     if (PhiN < 0)
         PhiN = 0;
     const double TransR = (SlopeFS * PhiN + LHV * PsycParam * ga * DeltaPVa)
         / (LHV * (SlopeFS + PsycParam * (1 + ga / conductance_in_m_per_s)));  // kg / m^2 / s
     const double EPen = (SlopeFS * PhiN + LHV * PsycParam * ga * DeltaPVa)
         / (LHV * (SlopeFS + PsycParam));  // kg / m^2 / s
     const double EPries = 1.26 * (SlopeFS * PhiN / (LHV * (SlopeFS + PsycParam)));  // kg / m^2 / s
     // TransR has units of kg / m^2 / s.
     // Convert to mm / m^2 / s.
     /* 1e3 - g / kg  */
     /* 18 - g / mol for water */
     /* 1e3 - mmol / mol */
     struct ET_Str et_results;
     et_results.TransR = TransR * 1e3 * 1e3 / 18;
     et_results.EPenman = EPen * 1e3 * 1e3 / 18;
     et_results.EPriestly = EPries * 1e3 * 1e3 / 18;
     et_results.Deltat = Deltat;
     return et_results;
 }
References ET_Str::Deltat, ET_Str::EPenman, ET_Str::EPriestly, saturation_vapor_pressure(), TempToDdryA(), TempToLHV(), TempToSFS(), and ET_Str::TransR.
Referenced by c3CanAC().
CanAC()
struct Can_Str CanAC (double LAI, int DOY, double hr, double solarR, double Temp, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double theta, double kd, double chil, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double upperT, double lowerT, const struct nitroParms & nitroP, double leafwidth, int eteq, double StomataWS, int water_stress_approach)
Definition at line 1 of file CanAC.cpp.
 {
     struct Light_model light_model = lightME(lat, DOY, hr);
     double Idir = light_model.direct_irradiance_fraction * solarR;  // micromole / m^2 / s. Flux through a plane perpendicular to the rays of the sun.
     double Idiff = light_model.diffuse_irradiance_fraction * solarR;
     double cosTh = light_model.cosine_zenith_angle;
     struct Light_profile light_profile = sunML(Idir, Idiff, LAI, nlayers, cosTh, kd, chil, heightf);
     double LAIc = LAI / nlayers;
     double relative_humidity_profile[nlayers];
     RHprof(RH, nlayers, relative_humidity_profile);  // Modifies relative_humidity_profile.
     double wind_speed_profile[nlayers];
     WINDprof(WindSpeed, LAI, nlayers, wind_speed_profile);  // Modifies wind_speed_profile.
     double leafN_profile[nlayers];
     LNprof(leafN, LAI, nlayers, kpLN, leafN_profile);  // Modifies leafN_profile.
     double CanopyA = 0.0, GCanopyA = 0.0, CanopyT = 0.0, CanopyPe = 0.0, CanopyPr = 0.0;
     double canopy_conductance = 0.0;
     double result_matrix[21 * MAXLAY];
     for (int i = 0; i < nlayers; ++i)
     {
         int current_layer = nlayers - 1 - i;
         double leafN_lay = leafN_profile[current_layer];
         double vmax1;
         if (lnfun == 0) {
             vmax1 = Vmax;
         } else {
             vmax1 = nitroP.Vmaxb1 * leafN_lay + nitroP.Vmaxb0;
             if (vmax1 < 0) vmax1 = 0.0;
             if (vmax1 > Vmax) vmax1 = Vmax;
             Alpha = nitroP.alphab1 * leafN_lay + nitroP.alphab0;
             Rd = nitroP.Rdb1 * leafN_lay + nitroP.Rdb0;
         }
         double relative_humidity = relative_humidity_profile[current_layer];
         double layer_wind_speed = wind_speed_profile[current_layer];
         double CanHeight = light_profile.height[current_layer];  // meters
         double Itot = light_profile.total_irradiance[current_layer];  // micromole / m^2 / s
         double IDir = light_profile.direct_irradiance[current_layer];  // micromole / m^2 / s
         double pLeafsun = light_profile.sunlit_fraction[current_layer];  // dimensionless. Fraction of LAI that is sunlit.
         double Leafsun = LAIc * pLeafsun;
         double direct_stomatal_conductance = c4photoC(IDir, temperature, relative_humidity, vmax1, Alpha, Kparm, theta, beta, Rd, b0, b1, StomataWS, Catm, water_stress_approach, upperT, lowerT).Gs; // mmol / m^2 / s
         struct ET_Str et_direct = EvapoTrans2(IDir, Itot, temperature, relative_humidity, layer_wind_speed, LAIc, CanHeight, direct_stomatal_conductance, leafwidth, eteq);
         double leaf_temperature_Idir = temperature + et_direct.Deltat;
         struct c4_str direct_photo = c4photoC(IDir, leaf_temperature_Idir, relative_humidity, vmax1, Alpha, Kparm, theta, beta, Rd, b0, b1, StomataWS, Catm, water_stress_approach, upperT, lowerT);
         double IDiff = light_profile.diffuse_irradiance[current_layer];  // micromole / m^2 / s
         double pLeafshade = light_profile.shaded_fraction[current_layer];  // dimensionless. Fraction of LAI that is shaded.
         double Leafshade = LAIc * pLeafshade;
         //Rprintf("current_layer,CumLAI,leafN_lay,relative_humidity,layer_wind_speed,CanHeight,Itot,IDir,pLeafSun,IDiff,pLeafShade\n");
         //Rprintf("%i,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f\n", current_layer, LAIc * (current_layer + 0.5), leafN_lay, relative_humidity, layer_wind_speed, CanHeight, Itot, IDir, pLeafsun, IDiff, pLeafshade);
         double diffuse_stomatal_conductance = c4photoC(IDiff, temperature, relative_humidity, vmax1, Alpha, Kparm, theta, beta, Rd, b0, b1, StomataWS, Catm, water_stress_approach, upperT, lowerT).Gs;
         struct ET_Str et_diffuse = EvapoTrans2(IDiff, Itot, temperature, relative_humidity, layer_wind_speed, LAIc, CanHeight, diffuse_stomatal_conductance, leafwidth, eteq);
         double leaf_temp_Idiffuse = temperature + et_diffuse.Deltat;
         struct c4_str diffuse_photo = c4photoC(IDiff, leaf_temp_Idiffuse, relative_humidity, vmax1, Alpha, Kparm, theta, beta, Rd, b0, b1, StomataWS, Catm, water_stress_approach, upperT, lowerT);
         CanopyA += Leafsun * direct_photo.Assim + Leafshade * diffuse_photo.Assim;
         CanopyT += Leafsun * et_direct.TransR + Leafshade * et_diffuse.TransR;
         GCanopyA += Leafsun * direct_photo.GrossAssim + Leafshade * diffuse_photo.GrossAssim;
         //Rprintf("shade leaf assim %f; sun leaf assim %f; shade trans %f; sun trans %f\n", diffuse_photo.Assim, direct_photo.Assim, et_diffuse.TransR, et_direct.TransR);
         CanopyPe += Leafsun * et_direct.EPenman + Leafshade * et_diffuse.EPenman;
         CanopyPr += Leafsun * et_direct.EPriestly + Leafshade * et_diffuse.EPriestly;
         canopy_conductance += Leafsun * direct_photo.Gs + Leafshade * diffuse_photo.Gs;
         result_matrix[    i*21] = IDir;
         result_matrix[1 + i*21] = IDiff;
         result_matrix[2 + i*21] = Leafsun;
         result_matrix[3 + i*21] = Leafshade;
         result_matrix[4 + i*21] = et_direct.TransR;
         result_matrix[5 + i*21] = et_diffuse.TransR;
         result_matrix[6 + i*21] = direct_photo.Assim;
         result_matrix[7 + i*21] = diffuse_photo.Assim;
         result_matrix[8 + i*21] = et_direct.Deltat;
         result_matrix[9 + i*21] = et_diffuse.Deltat;
         result_matrix[10 + i*21] = direct_photo.Gs;
         result_matrix[11 + i*21] = diffuse_photo.Gs;
         result_matrix[12 + i*21] = leafN_lay;
         result_matrix[13 + i*21] = vmax1;
         result_matrix[14 + i*21] = relative_humidity;
         result_matrix[15 + i*21] = direct_photo.GrossAssim;
         result_matrix[16 + i*21] = diffuse_photo.GrossAssim;
         result_matrix[17 + i*21] = Alpha;
         result_matrix[18 + i*21] = leafN_lay;
         result_matrix[19 + i*21] = layer_wind_speed;
         result_matrix[20 + i*21] = CanHeight;
     }
     struct Can_Str ans;
     /* For Assimilation */
     /* 3600 - seconds per hour */
     /* 1e-6 - moles per micromole */
     /* 30 - grams of C6H12O6 (glucose) incorporated into dry biomass per mole of CO2 */
     /* 1e-6 - megagrams per gram */
     /* 10000 - meters squared per hectare*/
     ans.Assim = CanopyA * 3600 * 1e-6 * 30 * 1e-6 * 10000;  // Mg / ha / hr.
     ans.GrossAssim = GCanopyA * 3600 * 1e-6 * 30 * 1e-6 * 10000;  // Mg / ha / hr.
     /* For Transpiration */
     /* 3600 - seconds per hour */
     /* 1e-3 - millimoles per mole */
     /* 18 - grams per mole for H2O */
     /* 1e-6 - megagrams per  gram */
     /* 10000 - meters squared per hectare */
     ans.Trans = CanopyT * 3600 * 1e-3 * 18 * 1e-6 * 10000;  // Mg / ha / hr.
     ans.canopy_transpiration_penman = CanopyPe;
     ans.canopy_transpiration_priestly = CanopyPr;
     ans.canopy_conductance = canopy_conductance;
     for (int i = 0; i < nlayers * 21; ++i) {
         ans.result_matrix[i] = result_matrix[i];
     }
     return ans;
 }
References c4_str::Assim, Can_Str::Assim, c4photoC(), Can_Str::canopy_conductance, Can_Str::canopy_transpiration_penman, Can_Str::canopy_transpiration_priestly, Light_model::cosine_zenith_angle, ET_Str::Deltat, Light_profile::diffuse_irradiance, Light_model::diffuse_irradiance_fraction, Light_profile::direct_irradiance, Light_model::direct_irradiance_fraction, ET_Str::EPenman, ET_Str::EPriestly, EvapoTrans2(), c4_str::GrossAssim, Can_Str::GrossAssim, c4_str::Gs, Light_profile::height, lightME(), LNprof(), MAXLAY, Can_Str::result_matrix, RHprof(), Light_profile::shaded_fraction, Light_profile::sunlit_fraction, sunML(), Light_profile::total_irradiance, Can_Str::Trans, ET_Str::TransR, and WINDprof().
cos_zenith_angle()
double cos_zenith_angle (const double latitude, const int day_of_year, const double hour_of_day)
Computation of the cosine of the zenith angle from latitute (lat), day of the year (DOY), and time of day (td).
For the values of angles in radians, we'll use the common practice of denoting the latitude by phi (), the declination by delta (), and the hour angle by tau (). NDS denotes the number of days after December solstice and omega () denotes the angle (in radians) of the orbital position of the earth around the sun relative to its position at the December solstice.
Denoting the axial tilt of the earth by , the equation used for declination (delta) is
which is an approximation (always accurate to within 0.26 degrees) of the more accurate formula
The cosine of the solar zenith angle may be calculated from the declination , the latitude , and the hour angle by the formula
which is a straight-forward application of the law of cosines for spherical triangles, substituting cofunctions of coangles in the case of latitude and declination.
Definition at line 72 of file AuxBioCro.cpp.
 {
     constexpr double radians_per_degree = math_constants::pi/180;
     constexpr int solar_noon = 12;
     constexpr double radians_rotation_per_hour = 15 * radians_per_degree;
     constexpr double axial_tilt = 23.5 * radians_per_degree;
     const double phi = latitude * radians_per_degree;
     const int NDS = day_of_year + 10;
     const double omega = 360.0 * (NDS / 365.0) * radians_per_degree;
     const double delta = -axial_tilt * cos(omega);
     const double tau = (hour_of_day - solar_noon) * radians_rotation_per_hour;
     return sin(delta) * sin(phi) + cos(delta) * cos(phi) * cos(tau);
 }
Referenced by lightME().
EvapoTrans2()
struct ET_Str EvapoTrans2 (double Rad, double Iave, double Airtemperature, double RH, double WindSpeed, double LeafAreaIndex, double CanopyHeight, double stomatacond, double leafw, int eteq)
Definition at line 325 of file AuxBioCro.cpp.
 {
     constexpr double StefanBoltzmann = 5.67037e-8;       // J / m^2 / s / K^4
     constexpr double tau = 0.2;                          // dimensionless. Leaf transmission coefficient.
     constexpr double LeafReflectance = 0.2;              // dimensionless.
     constexpr double SpecificHeat = 1010;                // J / kg / K
     constexpr double molar_mass_of_water = 18.01528e-3;  // kg / mol
     constexpr double R = 8.314472;                       // joule / kelvin / mole.
     //constexpr double atmospheric_pressure = 101325;      // Pa
     CanopyHeight = fmax(0.1, CanopyHeight); // ensure CanopyHeight >= 0.1
     double WindSpeedHeight = 2; // This is the height at which the wind speed was measured.
     // When the height at which wind was measured is lower than the canopy height, there can be problems with the calculations.
     // This is a very crude way of solving this problem.
     if (WindSpeedHeight < CanopyHeight + 1) {
         WindSpeedHeight = CanopyHeight + WindSpeedHeight;
     }
     const double DdryA = TempToDdryA(airTemp);  // kg / m^3. Density of dry air.,
     const double LHV = TempToLHV(airTemp);  // J / kg
     const double SlopeFS = TempToSFS(airTemp);  // kg / m^3 / K. It is also kg / m^3 / degrees C since it's a change in temperature.
     const double SWVP = saturation_vapor_pressure(airTemp);  // Pa.
     double constexpr volume_of_one_mole_of_air = 24.39e-3;  // m^3 / mol. TODO: This is for about 20 degrees C at 100000 Pa. Change it to use the model state. (1 * R * temperature) / pressure
     double conductance_in_m_per_s = stomatal_conductance * 1e-3 * volume_of_one_mole_of_air;  // m / s
     if (conductance_in_m_per_s <= 0.001) {
         conductance_in_m_per_s = 0.001;
     }
     if (RH > 1)
         throw std::range_error("Thrown in EvapoTrans2: RH (relative humidity) is greater than 1.");
     const double SWVC = SWVP / R / (airTemp + 273.15) * molar_mass_of_water;  // kg / m^3. Convert from vapor pressure to vapor density using the ideal gas law. This is approximately right for temperatures what won't kill plants.
     if (SWVC < 0)
         throw std::range_error("Thrown in EvapoTrans2: SWVC is less than 0.");
     const double PsycParam = DdryA * SpecificHeat / LHV;  // kg / m^3 / K
     const double vapor_density_deficit = SWVC * (1 - RH);  // kg / m^3
     const double ActualVaporPressure = RH * SWVP;  // Pa
     /* SOLAR RADIATION COMPONENT */
     // Convert from PPFD to irradiance.
     double constexpr fraction_of_irradiance_in_PAR = 0.5;  // dimensionless.
     double constexpr joules_per_micromole_PAR = 0.235;   // J / micromole. For the wavelengths that make up PAR in sunlight, one mole of photons has, on average, approximately 2.35 x 10^5 joules:
     double const total_irradiance = Rad * joules_per_micromole_PAR / fraction_of_irradiance_in_PAR;  // W / m^2.
     double const total_average_irradiance = Iave * joules_per_micromole_PAR / fraction_of_irradiance_in_PAR;  // W / m^2
     /* With a clear sky, irradiance may exceed 1000 W / m^2 in some parts of the world. Thornley and Johnson pg 400. */
     /* This value cannot possibly be higher than 1300 W / m^2. */
     if (total_irradiance > 1300) {
         throw std::range_error("Thrown in EvapoTrans2: total irradiance is " + std::to_string(total_irradiance) + ", which is too high.");
     }
     const double Ja = total_irradiance * (1 - LeafReflectance - tau) / (1 - tau);  // W / m^2
     /* The value below is only for leaf temperature */
     const double Ja2 = total_average_irradiance * (1 - LeafReflectance - tau) / (1 - tau);  // W / m^2
     /* AERODYNAMIC COMPONENT */
     if (WindSpeed < 0.5) WindSpeed = 0.5;
     /* This is the original from WIMOVAC*/
     double Deltat = 0.01;  // degrees C
     double ga;
     double rlc; /* Long wave radiation for iterative calculation */
     {
         double ChangeInLeafTemp = 10.0;  // degrees C
         double Counter = 0;
         do {
             ga = leaf_boundary_layer_conductance(WindSpeed, leaf_width, airTemp, Deltat, conductance_in_m_per_s, ActualVaporPressure);  // m / s
             /* In WIMOVAC, ga was added to the canopy conductance */
             /* ga = (ga * gbcW)/(ga + gbcW); */
             double OldDeltaT = Deltat;
             rlc = 4 * StefanBoltzmann * pow(273 + airTemp, 3) * Deltat;  // W / m^2
             /* rlc = net long wave radiation emittted per second = radiation emitted per second - radiation absorbed per second = sigma * (Tair + deltaT)^4 - sigma * Tair^4
              * To make it a linear function of deltaT, do a Taylor series about deltaT = 0 and keep only the zero and first order terms.
              * rlc = sigma * Tair^4 + deltaT * (4 * sigma * Tair^3) - sigma * Tair^4 = 4 * sigma * Tair^3 * deltaT
              * where 4 * sigma * Tair^3 is the derivative of sigma * (Tair + deltaT)^4 evaluated at deltaT = 0,
              */
             const double PhiN2 = Ja2 - rlc;  // W / m^2
             /* This equation is from Thornley and Johnson pg. 418 */
             const double TopValue = PhiN2 * (1 / ga + 1 / conductance_in_m_per_s) - LHV * vapor_density_deficit;  // J / m^3
             const double BottomValue = LHV * (SlopeFS + PsycParam * (1 + ga / conductance_in_m_per_s));  // J / m^3 / K
             Deltat = fmin(fmax(TopValue / BottomValue, -10), 10); // kelvin. Confine Deltat to the interval [-10, 10]:
             ChangeInLeafTemp = fabs(OldDeltaT - Deltat);  // kelvin
         } while ( (++Counter <= 10) && (ChangeInLeafTemp > 0.5) );
     }
     /* Net radiation */
     const double PhiN = fmax(0, Ja - rlc);  // W / m^2
     //Rprintf("SlopeFS %f, PhiN %f, LHV %f, PsycParam %f, ga %f, vapor_density_deficit %f, conductance_in... %f\n", SlopeFS, PhiN, LHV, PsycParam, ga, vapor_density_deficit, conductance_in_m_per_s);
     const double penman_monieth = (SlopeFS * PhiN + LHV * PsycParam * ga * vapor_density_deficit)
         / (LHV * (SlopeFS + PsycParam * (1 + ga / conductance_in_m_per_s)));  // kg / m^2 / s.  Thornley and Johnson. 1990. Plant and Crop Modeling. Equation 14.4k. Page 408.
     const double EPen = (SlopeFS * PhiN + LHV * PsycParam * ga * vapor_density_deficit)
         / (LHV * (SlopeFS + PsycParam));  // kg / m^2 / s
     const double EPries = 1.26 * SlopeFS * PhiN / (LHV * (SlopeFS + PsycParam));  // kg / m^2 / s
     /* Choose equation to report */
     double TransR;
     switch (eteq) {
     case 1:
         TransR = EPen;
         break;
     case 2:
         TransR = EPries;
         break;
     default:
         TransR = penman_monieth;
         break;
     }
     // TransR has units of kg / m^2 / s.
     // Convert to mm / m^2 / s.
     /* 1e3 - g / kg  */
     /* 18 - g / mol for water */
     /* 1e3 - mmol / mol */
     struct ET_Str et_results;
     et_results.TransR = TransR * 1e3 * 1e3 / 18;    // mmol / m^2 / s
     et_results.EPenman = EPen * 1e3 * 1e3 / 18;     // mmol / m^2 / s
     et_results.EPriestly = EPries * 1e3 * 1e3 / 18; // mmol / m^2 / s
     et_results.Deltat = Deltat;                     // degrees C
     return et_results;
 }
flow()
struct flow_str flow (double * SC, double CNratio, double A, double Lc, double Tm, double resp, int kno, double Ks[8])
FmLcFun()
struct FL_str FmLcFun (double Lig, double Nit)
lightME()
struct Light_model lightME (const double latitude, const int day_of_year, const double hour_of_day)
Light Macro Environment
Definition at line 95 of file AuxBioCro.cpp.
 {
     // day_of_year and hour_of_day are given as local time for the specified latitude.
     //
     // Return values.
     //  light_model.direct_irradiance_fraction: The fraction of irradiance that is direct radiation. dimensionless.
     //  light_model.diffuse_irradiance_fraction: The fraction of irradiance that is diffuse radiation. dimensionless.
     //  light_model.cosine_zenith_angle: The cosine of the zenith angle of the Sun. When the Sun is directly overhead, the angle is 0 and cos(angle) is 1. dimensionless.
     //
     // The basis for this function is given in chapter 11 of Norman and Campbell. An Introduction to Environmental Biophysics. 2nd edition.
     const double cosine_zenith_angle = cos_zenith_angle(latitude, day_of_year, hour_of_day);  // dimensionless.
     double direct_irradiance_transmittance;
     double diffuse_irradiance_transmittance;
     if (cosine_zenith_angle <= 0) { // Check if the Sun is at or below the horizon. If it is, directly set direct_irradiance_transmittance and diffuse_irradiance_transmittance because the equations below would otherwise produce erroneous results. The Sun is at or below the horizon when cosine_zenith_angle is less than or equal to 0.
         direct_irradiance_transmittance = 0;
         diffuse_irradiance_transmittance = 1;
     } else { // If the Sun is above the horizon, calculate diffuse and direct irradiance from the Sun's angle to the ground and the path through the atmosphere.
         constexpr double atmospheric_transmittance = 0.85; // dimensionless.
         constexpr double atmospheric_pressure_at_sea_level = 1e5; // Pa.
         constexpr double local_atmospheric_pressure = 1e5; // Pa.
         constexpr double pressure_ratio = local_atmospheric_pressure / atmospheric_pressure_at_sea_level; // dimensionless.
         constexpr double proportion_of_irradiance_scattered = 0.3; // dimensionless.
         direct_irradiance_transmittance = pow(atmospheric_transmittance, (pressure_ratio / cosine_zenith_angle)); // Modified from equation 11.11 of Norman and Campbell.
         diffuse_irradiance_transmittance = proportion_of_irradiance_scattered * (1 - direct_irradiance_transmittance) * cosine_zenith_angle; // Modified from equation 11.13 of Norman and Campbell.
     }
     Light_model light_model;
     light_model.direct_irradiance_fraction = direct_irradiance_transmittance / (direct_irradiance_transmittance + diffuse_irradiance_transmittance); // dimensionless.
     light_model.diffuse_irradiance_fraction = diffuse_irradiance_transmittance / (direct_irradiance_transmittance + diffuse_irradiance_transmittance); // dimensionless.
     light_model.cosine_zenith_angle = cosine_zenith_angle; // dimensionless.
     return light_model;
 }
References cos_zenith_angle(), Light_model::cosine_zenith_angle, Light_model::diffuse_irradiance_fraction, and Light_model::direct_irradiance_fraction.
Referenced by c3CanAC(), CanAC(), and newCanAC().
resp()
double resp (double comp, double mrc, double temp)
Definition at line 903 of file AuxBioCro.cpp.
{
     double ans = comp *  (1 - (mrc * pow(2, (temp / 10.0))));
     if (ans <0) ans = 0;
     return ans;
 }
RHprof()
void RHprof (double RH, int nlayers, double * relative_humidity_profile)
Preconditions: RH is between 0 and 1. nlayers is at least 1 and at most MAXLAY. relative_humidity_profile is an array of at least size nlayers.
Postconditions: relative_humidity_profile contains values between 0 and 1.
Definition at line 255 of file AuxBioCro.cpp.
 {
     if (RH > 1 || RH < 0) {
         throw std::out_of_range("RH must be between 0 and 1.");
     }
     if (nlayers < 1 || nlayers > MAXLAY) {
         throw std::out_of_range("nlayers must be at least 1 but no more than MAXLAY.");
     }
     const double kh = 1 - RH;
     for (int i = 0; i < nlayers; ++i)
     {
         double j = i + 1;  // Explicitly make j a double so that j / nlayers isn't truncated.
         double temp_rh = RH * exp(kh * (j / nlayers));
         relative_humidity_profile[i] = temp_rh;
     }
 }
References MAXLAY.
Referenced by c3CanAC(), CanAC(), newCanAC(), and multilayer_canopy_properties::run().
SoilEvapo()
double SoilEvapo (double LAI, double k, double AirTemp, double DirectRad, double awc, double fieldc, double wiltp, double winds, double RelH, double rsec, double soil_clod_size, double soil_reflectance, double soil_transmission, double specific_heat, double stefan_boltzman)
Definition at line 536 of file AuxBioCro.cpp.
 {
     int method = 1;
     /* A simple way of calculating the proportion of the soil that is hit by direct radiation. */
     double soil_area_sunlit_fraction = exp(-k * LAI);  // dimensionless.
     /* For now the temperature of the soil will be the same as the air.
        At a later time this can be made more accurate. I looked at the equations for this and the issue is that it is strongly dependent on
        depth. Since the soil model now has a single layer, this cannot be implemented correctly at the moment.  */
     double SoilTemp = air_temperature;
     /* From Campbell and Norman. Environmental Biophysics. */
     /* If relative available water content is */
     double rawc = (soil_water_content - wiltp) / (fieldc - wiltp);  // dimensionless. relative available water content.
     /* Campbell and Norman. Environmental Physics, page 142 */
     double maximum_uptake_rate = 1 - pow((1 + 1.3 * rawc), -5);  // dimenionless
     /* This is a useful idea because dry soils evaporate little water when dry*/
     /* Total Radiation */
     /* Convert light assuming 1 micromole PAR photons = 0.235 J/s Watts*/
     /* At the moment soil evaporation is grossly overestimated. In WIMOVAC the light reaching the last layer of leaves is used. Here instead
        of calculating this again, I will for now assume a 10% as a rough estimate. Note that I could maybe get this since layIdir and
        layIDiff in sunML are external variables.  Rprintf("ppfd %.5f",layIdir[0],"\n"); Update: 03-13-2009. I tried printing this
        value but it is still too high and will likely overestimate soil evaporation. However, this is still a work in progress.
        */
     ppfd *= rsec; /* Radiation soil evaporation coefficient */
     double TotalRadiation = ppfd * 0.235;
     double DdryA = TempToDdryA(air_temperature);
     double LHV = TempToLHV(air_temperature);  // J / kg
     double SlopeFS = TempToSFS(air_temperature);
     double SWVC = saturation_vapor_pressure(air_temperature) * 1e-5;
     double PsycParam = (DdryA * specific_heat) / LHV;
     double vapor_density_deficit = SWVC * (1 - RelH / 100);
     double BoundaryLayerThickness = 4e-3 * sqrt(soil_clod_size / winds);
     double DiffCoef = 2.126e-5 * 1.48e-7 * SoilTemp;
     double SoilBoundaryLayer = DiffCoef / BoundaryLayerThickness;
     double Ja = 2 * TotalRadiation * ((1 - soil_reflectance - soil_transmission) / (1 - soil_transmission));
     double rlc = 4 * stefan_boltzman * pow((273 + SoilTemp), 3) * 0.005;
     /* the last term should be the difference between air temperature and soil. This is not actually calculated at the moment. Since this is
        mostly relevant to the first soil layer where the temperatures are similar. I will leave it like this for now. */
     double PhiN = Ja - rlc; /* Calculate the net radiation balance*/
     if (PhiN < 0) PhiN = 1e-7;
     double Evaporation = 0.0;
     if (method == 0) {
         /* Priestly-Taylor */
         Evaporation = 1.26 * (SlopeFS * PhiN) / (LHV * (SlopeFS + PsycParam));  // kg / m^2 / s.
     } else {
         /* Penman-Monteith */
         Evaporation = (SlopeFS * PhiN + LHV * PsycParam * SoilBoundaryLayer * vapor_density_deficit) / (LHV * (SlopeFS + PsycParam));  // kg / m^2 / s.
     }
     Evaporation *= soil_area_sunlit_fraction * maximum_uptake_rate;  // kg / m^2 / s.
     if (Evaporation < 0) Evaporation = 1e-6;  // Prevent odd values at very low light levels.
     return Evaporation;  // kg / m^2 / s.
 }
References saturation_vapor_pressure(), TempToDdryA(), TempToLHV(), and TempToSFS().
soilML()
struct soilML_str soilML (double precipit, double transp, double * cws, double soildepth, double * depths, double soil_field_capacity, double soil_wilting_point, double soil_saturation_capacity, double soil_air_entry, double soil_saturated_conductivity, double soil_b_coefficient, double soil_sand_content, double phi1, double phi2, int wsFun, int layers, double rootDB, double LAI, double k, double AirTemp, double IRad, double winds, double RelH, int hydrDist, double rfl, double rsec, double rsdf, double soil_clod_size, double soil_reflectance, double soil_transmission, double specific_heat, double stefan_boltzman)
Definition at line 604 of file AuxBioCro.cpp.
 {
     constexpr double g = 9.8; /* m / s-2  ##  http://en.wikipedia.org/wiki/Standard_gravity */
     soilML_str return_value;
     /* Crude empirical relationship between root biomass and rooting depth*/
     double rootDepth = fmin(rootDB * rsdf, soildepth);
     rd_str root_distribution = rootDist(layers, rootDepth, &depths[0], rfl);
     /* unit conversion for precip */
     double oldWaterIn = 0.0;
     double waterIn = precipit * 1e-3; /* convert precip in mm to m */
     double drainage = 0.0;
     double wsPhotoCol = 0.0;
     double LeafWSCol = 0.0;
     double Sevap = 0.0;
     double oldEvapoTra = 0.0;
     for (int i = layers - 1; i >= 0; --i) { /* The counter, i, decreases because I increase the water content due to precipitation in the last layer first*/
         double layerDepth = depths[i+1] - depths[i];  /* This supports unequal depths. */
         if (hydrDist > 0) {
             /* For this section see Campbell and Norman "Environmental BioPhysics" Chapter 9*/
             /* First compute the matric potential */
             double psim1 = soil_air_entry * pow((cws[i]/soil_saturation_capacity), -soil_b_coefficient); /* This is matric potential of current layer */
             double dPsim;
             if (i > 0) {
                 double psim2 = soil_air_entry * pow((cws[i-1]/soil_saturation_capacity), -soil_b_coefficient); /* This is matric potential of next layer */
                 dPsim = psim1 - psim2;
                 /* The substraction is from the layer i - (i-1). If this last term is positive then it will move upwards. If it is negative it will move downwards. Presumably this term is almost always positive. */
             } else {
                 dPsim = 0.0;
             }
             double K_psim = soil_saturated_conductivity * pow((soil_air_entry/psim1), 2+3/soil_b_coefficient); /* This is hydraulic conductivity */
             double J_w = K_psim * (dPsim/layerDepth) - g * K_psim; /*  Campbell, pg 129 do not ignore the graviational effect*/
             /* Notice that K_psim is positive because my reference system is reversed */
             /* This last result should be in kg/(m2 * s) */
             J_w *= 3600 * 0.9882 * 1e-3; /* This is flow in m3 / (m^2 * hr). */
             if (i == (layers-1) && J_w < 0) {
                 /* cws[i] = cws[i] + J_w / layerDepth; Although this should be done it drains the last layer too much.*/
                 drainage += J_w;
             } else {
                     cws[i] = cws[i] - J_w / layerDepth;
                 if (i > 0) {
                     cws[i - 1] = cws[i - 1] + J_w / layerDepth;
                 }
             }
         }
         if (cws[i] > soil_saturation_capacity) cws[i] = soil_saturation_capacity;
         if (cws[i] < soil_wilting_point) cws[i] = soil_wilting_point;
         // Here is a convention aw is available water in volume and awc
         // is available water content as a fraction of the soil section being investigated.
         double aw = cws[i] * layerDepth;
         /* Available water (for this layer) is the current water status times the layer depth */
         if (waterIn > 0) {
             /* There is some rain. Need to add it.*/
             aw += waterIn / layers + oldWaterIn; /* They are both in meters so it works */
             /* Adding the same amount to water to each layer */
             /* In case there is overflow */
             double diffw = soil_field_capacity * layerDepth - aw;
             if (diffw < 0) {
                 /* This means that precipitation exceeded the capacity of the first layer */
                 /* Save this amount of water for the next layer */
                 oldWaterIn = -diffw;
                 aw = soil_field_capacity * layerDepth;
             } else {
                 oldWaterIn = 0.0;
             }
         }
         /* Root Biomass */
         double rootATdepth = rootDB * root_distribution.rootDist[i];
         return_value.rootDist[i] = rootATdepth;
         /* Plant available water is only between current water status and permanent wilting point */
         /* Plant available water */
         double pawha = (aw - soil_wilting_point * layerDepth) * 1e4;
         if (pawha < 0) pawha = 0;
         double Ctransp = 0.0;
         double EvapoTra = 0.0;
         double Newpawha;
         if (i == 0) {
             /* Only the first layer is affected by soil evaporation */
             double awc2 = aw / layerDepth;
             /* SoilEvapo function needs soil water content  */
             Sevap = SoilEvapo(LAI, k, AirTemp, IRad, awc2, soil_field_capacity, soil_wilting_point, winds, RelH, rsec,
                 soil_clod_size, soil_reflectance, soil_transmission, specific_heat, stefan_boltzman ) * 3600 * 1e-3 * 10000;  // Mg / ha / hr. 3600 s / hr * 1e-3 Mg / kg * 10000 m^2 / ha.
             /* I assume that crop transpiration is distributed simlarly to
                root density.  In other words the crop takes up water proportionally
                to the amount of root in each respective layer.*/
             Ctransp = transp * root_distribution.rootDist[0];
             EvapoTra = Ctransp + Sevap;
             constexpr double density_of_water_at_20_celcius = 0.9982;  // Mg m^-3.
             Newpawha = pawha - EvapoTra / density_of_water_at_20_celcius;
             /* The first term in the rhs pawha is the m3 of water available in this layer.
                EvapoTra is the Mg H2O ha-1 of transpired and evaporated water. 1/0.9882 converts from Mg to m3 */
         } else {
             Ctransp = transp * root_distribution.rootDist[i];
             EvapoTra = Ctransp;
             Newpawha = pawha - (EvapoTra + oldEvapoTra);
         }
         if (Newpawha < 0) {
             /* If the Demand is not satisfied by this layer. This will be stored and added to subsequent layers*/
             oldEvapoTra = -Newpawha;
             aw = soil_wilting_point * layerDepth;
         }
         double awc = Newpawha / 1e4 / layerDepth + soil_wilting_point;
         /* This might look like a weird place to populate the structure, but is more convenient*/
         return_value.cws[i] = awc;
         // To-do: Replace this block with a call to compute_wsPhoto.
     /* three different type of equations for modeling the effect of water stress on vmax and leaf area expansion.
        The equation for leaf area expansion is more severe than the one for vmax. */
         double wsPhoto = 0.0;
         double slp = 0.0;
         double intcpt = 0.0;
         double theta = 0.0;
         if (wsFun == 0) { /* linear */
             slp = 1/(soil_field_capacity - soil_wilting_point);
             intcpt = 1 - soil_field_capacity * slp;
             wsPhoto = slp * awc + intcpt;
         } else if (wsFun == 1) {
             double phi10 = (soil_field_capacity + soil_wilting_point)/2;
             wsPhoto = 1/(1 + exp((phi10 - awc)/ phi1));
         } else if (wsFun == 2) {
             slp = (1 - soil_wilting_point)/(soil_field_capacity - soil_wilting_point);
             intcpt = 1 - soil_field_capacity * slp;
             theta = slp * awc + intcpt;
             wsPhoto = (1 - exp(-2.5 * (theta - soil_wilting_point)/(1 - soil_wilting_point))) / (1 - exp(-2.5));
         } else if (wsFun == 3) {
             wsPhoto = 1;
         }
         if (wsPhoto <= 0 )
             wsPhoto = 1e-10; /* This can be mathematically lower than zero in some cases but I should prevent that. */
         wsPhotoCol += wsPhoto;
         double LeafWS = pow(awc, phi2) * 1/pow(soil_field_capacity, phi2);
         if (wsFun == 3) {
             LeafWS = 1;
         }
         LeafWSCol += LeafWS;
     }
     if (waterIn > 0) {
         drainage = waterIn;
         /* Need to convert to units used in the Parton et al 1988 paper. */
         /* The data comes in mm/hr and it needs to be in cm/month */
         return_value.Nleach = drainage * 0.1 * (1/24 * 30) / (18 * (0.2 + 0.7 * soil_sand_content));
     }
     else {
         return_value.Nleach = 0.0;
     }
     return_value.rcoefPhoto = (wsPhotoCol/layers);
     return_value.drainage = drainage;
     return_value.rcoefSpleaf = (LeafWSCol/layers);
     return_value.SoilEvapo = Sevap;
     return return_value;
 }
sunML()
struct Light_profile sunML (double Idir, double Idiff, double LAI, int nlayers, double cosTheta, double kd, double chil, double heightf)
Computation of an n-layered light profile from the direct light Idir, diffuse light Idiff, leaf area index LAI, the cosine of the zenith angle cosTheta and other parameters.
Preconditions: Idir and Idiff are positive. LAI is non-negative. nlayers is at least 1 and not more than MAXLAY, the compile-time constant defining the maximum array size for arrays used to store profile data (enforced). cosTheta is greater than 0 and at most 1 (enforced). kd is between 0 and 1. chil is non-negative. heightf is positive.
Definition at line 149 of file AuxBioCro.cpp.
 {
     if (nlayers < 1 || nlayers > MAXLAY) {
         throw std::out_of_range("nlayers must be at least 1 but no more than MAXLAY.");
     }
     if (cosTheta > 1 || cosTheta < -1) {
         throw std::out_of_range("cosTheta must be between -1 and 1.");
     }
     if (kd > 1 || kd < 0) {
         throw std::out_of_range("kd must be between 0 and 1.");
     }
     if (chil < 0) {
         throw std::out_of_range("chil must be non-negative.");
     }
     if (heightf <= 0) {
         throw std::out_of_range("heightf must greater than zero.");
     }
     constexpr double alphascatter = 0.8;
     double theta = acos(cosTheta);
     double k0 = sqrt( pow(chil, 2) + pow(tan(theta), 2) );
     double k1 = chil + 1.744 * pow((chil + 1.183), -0.733);
     double k = k0 / k1;  // Canopy extinction coefficient for an ellipsoidal leaf angle distribution. Page 251, Campbell and Norman. Environmental Biophysics. second edition.
     double LAIi = LAI / nlayers;
     Light_profile light_profile;
     const double Ibeam = Idir * cosTheta;
     double Isolar = Ibeam * k;
     for (int i = 0; i < nlayers; ++i) {
         const double CumLAI = LAIi * (i + 0.5);
         const double Iscat = Ibeam * (exp(-k * sqrt(alphascatter) * CumLAI) - exp(-k * CumLAI));
         double Idiffuse = Idiff * exp(-kd * CumLAI) + Iscat;  // The exponential term is equation 15.6, pg 255 of Campbell and Normal. Environmental Biophysics. with alpha=1 and Kbe(phi) = Kd.
         const double Ls = (1 - exp(-k * LAIi)) * exp(-k * CumLAI) / k;
         double Fsun = Ls / LAIi;
         double Fshade = 1 - Fsun;
         double Iaverage = (Fsun * (Isolar + Idiffuse) + Fshade * Idiffuse) * (1 - exp(-k * LAIi)) / k;
         // For values of cosTheta close to or less than 0, in place of the
         // calculations above, we want to use the limits of the above
         // expressions as cosTheta approaches 0 from the right:
         if (cosTheta <= 1E-10) {
             Isolar = Idir / k1;
             Idiffuse = Idiff * exp(-kd * CumLAI);
             Fsun = 0;
             Fshade = 1;
             Iaverage = 0;
         }
         light_profile.direct_irradiance[i] = Isolar + Idiffuse;  // micromole / m^2 / s
         light_profile.scattered_irradiance[i] = Iscat;  // micromole / m^2 / s
         light_profile.diffuse_irradiance[i]= Idiffuse;  // micromole / m^2 / s
         light_profile.total_irradiance[i] = Iaverage;  // micromole / m^2 / s
         light_profile.sunlit_fraction[i] = Fsun;  // dimensionless from m^2 / m^2
         light_profile.shaded_fraction[i] = Fshade;  // dimensionless from m^2 / m^2
         light_profile.height[i] = (LAI - CumLAI) / heightf;  // meters
     }
     return light_profile;
 }
References Light_profile::diffuse_irradiance, Light_profile::direct_irradiance, Light_profile::height, MAXLAY, Light_profile::scattered_irradiance, Light_profile::shaded_fraction, Light_profile::sunlit_fraction, and Light_profile::total_irradiance.
Referenced by c3CanAC(), CanAC(), newCanAC(), and multilayer_canopy_properties::run().
watstr()
struct ws_str watstr (double precipit, double evapo, double cws, double soildepth, double fieldc, double wiltp, double phi1, double phi2, double soil_saturation_capacity, double soil_sand_content, double Ks, double air_entry, double b)
Definition at line 604 of file AuxBioCro.cpp.
 {
     constexpr double g = 9.8; // m / s^2  ##  http://en.wikipedia.org/wiki/Standard_gravity
     double precipM = precipit * 1e-3; /* convert precip in mm to m*/
     double soil_water_fraction = precipM / soildepth + cws;  // m^3 m^-3
     double runoff = 0.0;
     double Nleach = 0.0;  /* Nleach is the NO3 leached. */
     if (soil_water_fraction > soil_saturation_capacity) {
         runoff = (soil_water_fraction - soil_saturation_capacity) * soildepth; /* This is in meters */
         /* Here runoff is interpreted as water content exceeding saturation level */
         /* Need to convert to units used in the Parton et al 1988 paper. */
         /* The data come in mm/hr and need to be in cm/month */
         Nleach = runoff / 18 * (0.2 + 0.7 * sand);
         soil_water_fraction = soil_saturation_capacity;
     }
     /* The density of water is 0.9982 Mg / m^3 at 20 degrees Celsius. */
     /* evapo is demanded water (Mg / ha) */
     double npaw = soil_water_fraction - wiltp - evapo / 0.9982 / 1e4 / soildepth;  // fraction of saturation.
     /* If demand exceeds supply, the crop is getting close to wilting point and transpiration
        will be over estimated. In this one layer model though, the crop is practically dead. */
     if (npaw < 0) npaw = 0.0;
     double awc = npaw + wiltp;
     /* Calculating the soil water potential based on equations from Norman and Campbell */
     /* tmp.psim = soTexS.air_entry * pow((awc/soTexS.fieldc*1.1),-soTexS.b); */
     /* New version of the soil water potential is based on
      * "Dynamic Simulation of Water Deficit Effects upon Maize Yield" R. F. Grant Agricultural Systems. 33(1990) 13-39. */
     ws_str tmp;
     tmp.psim = -exp(log(0.033) + (log(fieldc) - log(awc)) / (log(fieldc) - log(wiltp)) * (log(1.5) - log(0.033))) * 1e3; /* This last term converts from MPa to kPa */
     /* This is drainage */
     if (awc > fieldc) {
         double K_psim = Ks * pow((air_entry / tmp.psim), 2 + 3 / b); /* This is hydraulic conductivity */
         double J_w = -K_psim * (-tmp.psim / (soildepth * 0.5)) - g * K_psim; /*  Campbell, pg 129 do not ignore the graviational effect. I multiply soil depth by 0.5 to calculate the average depth */
         double drainage = J_w * 3600 * 0.9982 * 1e-3; /* This is flow in m^3 / (m^2 * hr). */
         awc = awc + drainage / soildepth;
     }
     tmp.awc = awc;
     tmp.runoff = runoff;
     tmp.Nleach = Nleach;
     return tmp;
 }
WINDprof()
void WINDprof (double WindSpeed, double LAI, int nlayers, double * wind_speed_profile)
RH and Wind profile function
Preconditions: WindSpeed is non-negative. LAI is non-negative nlayers is at least 1 and at most MAXLAY. wind_speed_profile is an array of at least size nlayers.
Definition at line 233 of file AuxBioCro.cpp.
 {
     constexpr double k = 0.7;
     double LI = LAI / nlayers;
     for (int i = 0; i < nlayers; ++i)
     {
         double CumLAI = LI * (i + 1);
         wind_speed_profile[i] = WindSpeed * exp(-k * (CumLAI - LI));
     }
 }
Referenced by c3CanAC(), CanAC(), newCanAC(), and multilayer_canopy_properties::run().