The BioCro C++ Library: /github/workspace/source/src/module_library/canac_with_collatz.hpp File Reference
canac_with_collatz.hpp File Reference
#include "../modules.h"
#include "../system.h"
#include "../standalone_ss.h"
#include "water_vapor_properties_from_air_temperature.hpp"
#include "penman_monteith_transpiration.hpp"
#include "collatz_leaf.hpp"
Data Structures
class canac_with_collatz
Functions
struct Can_Str newCanAC (double LAI, int DOY, double hr, double solarR, double temperature, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double theta, double kd, double chil, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double upperT, double lowerT, const struct nitroParms &nitroP, double leafwidth, int eteq, double StomataWS, int water_stress_approach, double leaf_transmittance, double leaf_reflectance)
Function Documentation
newCanAC()
struct Can_Str newCanAC (double LAI, int DOY, double hr, double solarR, double temperature, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double theta, double kd, double chil, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double upperT, double lowerT, const struct nitroParms & nitroP, double leafwidth, int eteq, double StomataWS, int water_stress_approach, double leaf_transmittance, double leaf_reflectance)
Definition at line 1 of file canac_with_collatz.hpp.
 {
         // Set up a few standalone modules that we will be using
         // Make the steady state module list
         // The order is important, since the outputs from the first module
         //  are used as inputs for the next two, and the outputs from the
         //  second module are used as inputs for the third
         std::vector<std::string> steady_state_modules = {
                 "water_vapor_properties_from_air_temperature",  // water_vapor_module
                 "collatz_leaf",                                                                 // leaf_assim_module
                 "penman_monteith_transpiration"                                 // leaf_evapo_module
         };
         // Set up the input parameters
         // Note: the list of required inputs was quickly determined by using the following R command
         //  with the BioCro library loaded:
         //  get_standalone_ss_info(c("water_vapor_properties_from_air_temperature", "collatz_leaf", "penman_monteith_transpiration"))
         // Note that some of these parameters have not been defined yet
         double Itot;
         double Ipar;
         double layer_wind_speed;
         double relative_humidity;
         double vmax1;
         double wsa = (double) water_stress_approach;
         double k_Q10 = 2.0;
         double stefan_boltzman = 5.67e-8;
         std::unordered_map<std::string, const double*> input_param_ptrs = {
                 {"Catm",                                        &Catm},
                 {"Rd",                                          &Rd},
                 {"StomataWS",                           &StomataWS},
                 {"alpha",                                       &Alpha},
                 {"b0",                                          &b0},
                 {"b1",                                          &b1},
                 {"beta",                                        &beta},
                 {"incident_irradiance",         &Itot},
                 {"incident_par",                        &Ipar},
                 {"k_Q10",                                       &k_Q10},
                 {"kparm",                                       &Kparm},
                 {"layer_wind_speed",            &layer_wind_speed},
                 {"leaf_reflectance",            &leaf_reflectance},
                 {"leaf_transmittance",          &leaf_transmittance},
                 {"leafwidth",                           &leafwidth},
                 {"lowerT",                                      &lowerT},
                 {"rh",                                          &relative_humidity},
                 {"stefan_boltzman",             &stefan_boltzman},
                 {"temp",                                        &temperature},
                 {"theta",                                       &theta},
                 {"upperT",                                      &upperT},
                 {"vmax",                                        &vmax1},
                 {"water_stress_approach",       &wsa}
         };
         // Set up the output parameters
         // Note: the list of all possible outputs can be quickly determined by using
         //  the following R command with the BioCro library loaded:
         //  get_standalone_ss_info(c("water_vapor_properties_from_air_temperature", "collatz_leaf", "penman_monteith_transpiration"))
         // Here were are only interested in a few of them
         double leaf_ass;
         double leaf_trans;
         double leaf_cond;
         std::unordered_map<std::string, double*> output_param_ptrs = {
                 {"leaf_assimilation_rate",                              &leaf_ass},
                 {"leaf_transpiration_rate",                     &leaf_trans},
                 {"leaf_stomatal_conductance",                   &leaf_cond}
         };
         // Now that the inputs are defined, make the standalone modules and store a smart pointer to them
         std::shared_ptr<Standalone_SS> canopy_modules = std::shared_ptr<Standalone_SS>(new Standalone_SS(steady_state_modules, input_param_ptrs, output_param_ptrs));
         // Calculate the light and humidity properties at each layer of the canopy
         struct Light_model light_model = lightME(lat, DOY, hr);
         double Idir = light_model.direct_irradiance_fraction * solarR;  // micromole / m^2 / s. Flux through a plane perpendicular to the rays of the sun.
         double Idiff = light_model.diffuse_irradiance_fraction * solarR;
         double cosTh = light_model.cosine_zenith_angle;
         struct Light_profile light_profile = sunML(Idir, Idiff, LAI, nlayers, cosTh, kd, chil, heightf);
         double LAIc = LAI / nlayers;
         double relative_humidity_profile[nlayers];
         RHprof(RH, nlayers, relative_humidity_profile);  // Modifies relative_humidity_profile.
         double wind_speed_profile[nlayers];
         WINDprof(WindSpeed, LAI, nlayers, wind_speed_profile);  // Modifies wind_speed_profile.
         double leafN_profile[nlayers];
         LNprof(leafN, LAI, nlayers, kpLN, leafN_profile);  // Modifies leafN_profile.
         double CanopyA = 0.0,  CanopyT = 0.0;
         double canopy_conductance = 0.0;
         // Initialize some rates
         double sunlit_leaf_assimilation_rate;
         double sunlit_leaf_transpiration_rate;
         double sunlit_leaf_conductance;
         double shaded_leaf_assimilation_rate;
         double shaded_leaf_transpiration_rate;
         double shaded_leaf_conductance;
         // Go through the layers
         for (int i = 0; i < nlayers; ++i)
         {
                 // Get new values for system inputs that vary by layer
                 int current_layer = nlayers - 1 - i;
                 double leafN_lay = leafN_profile[current_layer];
                 if (lnfun == 0) {
                         vmax1 = Vmax;
                 } else {
                         vmax1 = nitroP.Vmaxb1 * leafN_lay + nitroP.Vmaxb0;
                         if (vmax1 < 0) vmax1 = 0.0;
                         if (vmax1 > Vmax) vmax1 = Vmax;
                         Alpha = nitroP.alphab1 * leafN_lay + nitroP.alphab0;
                         Rd = nitroP.Rdb1 * leafN_lay + nitroP.Rdb0;
                 }
                 relative_humidity = relative_humidity_profile[current_layer];
                 layer_wind_speed = wind_speed_profile[current_layer];
                 Itot = light_profile.total_irradiance[current_layer];  // micromole / m^2 / s
                 // Get assimilation, transpiration, and conductance rates for sunlit leaves
                 Ipar = light_profile.direct_irradiance[current_layer];  // micromole / m^2 / s
                 double pLeafsun = light_profile.sunlit_fraction[current_layer];  // dimensionless. Fraction of LAI that is sunlit.
                 double Leafsun = LAIc * pLeafsun;
                 canopy_modules->run();
                 sunlit_leaf_assimilation_rate = leaf_ass;
                 sunlit_leaf_transpiration_rate = leaf_trans;
                 sunlit_leaf_conductance = leaf_cond;
                 // Get assimilation, transpiration, and conductance rates for shaded leaves
                 Ipar = light_profile.diffuse_irradiance[current_layer];  // micromole / m^2 / s
                 double pLeafshade = light_profile.shaded_fraction[current_layer];  // dimensionless. Fraction of LAI that is shaded.
                 double Leafshade = LAIc * pLeafshade;
                 canopy_modules->run();
                 shaded_leaf_assimilation_rate = leaf_ass;
                 shaded_leaf_transpiration_rate = leaf_trans;
                 shaded_leaf_conductance = leaf_cond;
                 // Add rates to the total canopy assimilation, transpiration, and conductance
                 CanopyA += Leafsun * sunlit_leaf_assimilation_rate + Leafshade * shaded_leaf_assimilation_rate;
                 CanopyT += Leafsun * sunlit_leaf_transpiration_rate + Leafshade * shaded_leaf_transpiration_rate;
                 canopy_conductance += Leafsun * sunlit_leaf_conductance + Leafshade * shaded_leaf_conductance;
         }
         struct Can_Str ans;
         /* For Assimilation */
         /* 3600 - seconds per hour */
         /* 1e-6 - moles per micromole */
         /* 30 - grams per mole for CO2 */
         /* 1e-6 - megagrams per gram */
         /* 10000 - meters squared per hectare*/
         ans.Assim = CanopyA * 3600 * 1e-6 * 30 * 1e-6 * 10000;  // Mg / ha / hr.
         /* For Transpiration */
         /* 3600 - seconds per hour */
         /* 1e-3 - millimoles per mole */
         /* 18 - grams per mole for H2O */
         /* 1e-6 - megagrams per  gram */
         /* 10000 - meters squared per hectare */
         ans.Trans = CanopyT * 3600 * 1e-3 * 18 * 1e-6 * 10000;  // Mg / ha / hr.
         ans.canopy_conductance = canopy_conductance;
         return ans;
 }
References Can_Str::Assim, Can_Str::canopy_conductance, Light_model::cosine_zenith_angle, Light_profile::diffuse_irradiance, Light_model::diffuse_irradiance_fraction, Light_profile::direct_irradiance, Light_model::direct_irradiance_fraction, lightME(), LNprof(), RHprof(), Light_profile::shaded_fraction, Light_profile::sunlit_fraction, sunML(), Light_profile::total_irradiance, Can_Str::Trans, and WINDprof().