BioCro: ten_layer_canopy_properties Class Reference
ten_layer_canopy_properties Class Reference
A child class of multilayer_canopy_properties where the number of layers has been defined. Instances of this class can be created using the module factory.
#include <multilayer_canopy_properties.h>
Public Member Functions
ten_layer_canopy_properties (const std::unordered_map< std::string, double > *input_parameters, std::unordered_map< std::string, double > *output_parameters)
Public Member Functions inherited from multilayer_canopy_properties
multilayer_canopy_properties (const std::string &module_name, const int &nlayers, const std::unordered_map< std::string, double > *input_parameters, std::unordered_map< std::string, double > *output_parameters)
Public Member Functions inherited from SteadyModule
SteadyModule (const std::string &module_name, bool adaptive_compatible=true)
Public Member Functions inherited from Module
Module (std::string const &module_name, bool const &deriv, bool const &adaptive_compatible)
virtual ~Module ()=0
std::string get_name () const
bool is_deriv () const
bool is_adaptive_compatible () const
void run () const
Static Public Member Functions
static std::vector< std::string > get_inputs ()
static std::vector< std::string > define_leaf_classes ()
static std::vector< std::string > define_multiclass_multilayer_outputs ()
static std::vector< std::string > define_pure_multilayer_outputs ()
static std::vector< std::string > get_outputs ()
Additional Inherited Members
Protected Member Functions inherited from multilayer_canopy_properties
void run () const
Protected Member Functions inherited from SteadyModule
void update (double *output_ptr, const double &value) const
Protected Member Functions inherited from Module
double get_val_debug (const double *ptr, const std::string name) const
Static Protected Member Functions inherited from multilayer_canopy_properties
static std::vector< std::string > get_inputs (int nlayers)
Define all inputs required by the module.
static std::vector< std::string > define_leaf_classes ()
Define the different leaf classes included by the module.
static std::vector< std::string > define_multiclass_multilayer_outputs ()
Define all outputs that have different values for each leaf class and layer.
static std::vector< std::string > define_pure_multilayer_outputs ()
Define all outputs that have different values for each layer, not including outputs that also depend on leaf class.
static std::vector< std::string > get_outputs (int nlayers)
Define all output names by appending leaf class prefixes and layer number suffixes. Here we should make use of the define_XXX functions to reduce code duplication.
Static Protected Attributes inherited from Module
static const double eps = 1e-10
Detailed Description
A child class of multilayer_canopy_properties where the number of layers has been defined. Instances of this class can be created using the module factory.
Definition at line 236 of file multilayer_canopy_properties.h.
Constructor & Destructor Documentation
ten_layer_canopy_properties()
ten_layer_canopy_properties::ten_layer_canopy_properties (const std::unordered_map< std::string, double > * input_parameters, std::unordered_map< std::string, double > * output_parameters) inline
Definition at line 239 of file multilayer_canopy_properties.h.
         : multilayer_canopy_properties("ten_layer_canopy_properties",
                                        ten_layer_canopy_properties::nlayers,
                                        input_parameters,
                                        output_parameters)  // Create the base class with the appropriate number of layers
     {
     }
Member Function Documentation
define_leaf_classes()
std::vector< std::string > ten_layer_canopy_properties::define_leaf_classes () static
Definition at line 268 of file multilayer_canopy_properties.h.
 {
     return multilayer_canopy_properties::define_leaf_classes();
 }
References multilayer_canopy_properties::define_leaf_classes().
define_multiclass_multilayer_outputs()
std::vector< std::string > ten_layer_canopy_properties::define_multiclass_multilayer_outputs () static
Definition at line 273 of file multilayer_canopy_properties.h.
 {
     // Just call the parent class's multilayer output function
     return multilayer_canopy_properties::define_multiclass_multilayer_outputs();
 }
References multilayer_canopy_properties::define_multiclass_multilayer_outputs().
define_pure_multilayer_outputs()
std::vector< std::string > ten_layer_canopy_properties::define_pure_multilayer_outputs () static
Definition at line 279 of file multilayer_canopy_properties.h.
 {
     // Just call the parent class's multilayer output function
     return multilayer_canopy_properties::define_pure_multilayer_outputs();
 }
References multilayer_canopy_properties::define_pure_multilayer_outputs().
get_inputs()
std::vector< std::string > ten_layer_canopy_properties::get_inputs () static
Definition at line 263 of file multilayer_canopy_properties.h.
 {
     return multilayer_canopy_properties::get_inputs(ten_layer_canopy_properties::nlayers);
 }
References multilayer_canopy_properties::get_inputs().
get_outputs()
std::vector< std::string > ten_layer_canopy_properties::get_outputs () static
Definition at line 285 of file multilayer_canopy_properties.h.
 {
     return multilayer_canopy_properties::get_outputs(ten_layer_canopy_properties::nlayers);
 }
References multilayer_canopy_properties::get_outputs().
The documentation for this class was generated from the following file:
/github/workspace/source/src/module_library/multilayer_canopy_properties.h