BioCro: multilayer_canopy_properties Class Reference
multilayer_canopy_properties Class Reference
Calculates properties of each canopy layer using functions found in AuxBioCro (for the most part). Also includes multiple leaf classes (sunlit & shaded). Leaf class is added to output parameters as a prefix, while layer number is added as a suffix. Note that this module has a non-standard constructor, so it cannot be created using the module_wrapper_factory.
#include <multilayer_canopy_properties.h>
Public Member Functions
multilayer_canopy_properties (const std::string &module_name, const int &nlayers, const std::unordered_map< std::string, double > *input_parameters, std::unordered_map< std::string, double > *output_parameters)
Protected Member Functions
void run () const
Static Protected Member Functions
static std::vector< std::string > get_inputs (int nlayers)
Define all inputs required by the module.
static std::vector< std::string > define_leaf_classes ()
Define the different leaf classes included by the module.
static std::vector< std::string > define_multiclass_multilayer_outputs ()
Define all outputs that have different values for each leaf class and layer.
static std::vector< std::string > define_pure_multilayer_outputs ()
Define all outputs that have different values for each layer, not including outputs that also depend on leaf class.
static std::vector< std::string > get_outputs (int nlayers)
Define all output names by appending leaf class prefixes and layer number suffixes. Here we should make use of the define_XXX functions to reduce code duplication.
Detailed Description
Calculates properties of each canopy layer using functions found in AuxBioCro (for the most part). Also includes multiple leaf classes (sunlit & shaded). Leaf class is added to output parameters as a prefix, while layer number is added as a suffix. Note that this module has a non-standard constructor, so it cannot be created using the module_wrapper_factory.
For compatibility with the multilayer canopy photosynthesis module, the outputs of this module must be split into the following categories:
multiclass_multilayer outputs: these outputs are different for each leaf class and canopy layer
pure_multilayer outputs: these outputs are different for each canopy layer but not for each leaf class
other outputs: these outputs do not depend on the leaf class or canopy layer (there are currently no outputs of this type) The base names for the multiclass_multilayer and pure_multilayer outputs will be used by the multilayer canopy photosynthesis module to pass them to a leaf photosynthesis module.
Definition at line 28 of file multilayer_canopy_properties.h.
Constructor & Destructor Documentation
multilayer_canopy_properties()
multilayer_canopy_properties::multilayer_canopy_properties (const std::string & module_name, const int & nlayers, const std::unordered_map< std::string, double > * input_parameters, std::unordered_map< std::string, double > * output_parameters) inline
Definition at line 31 of file multilayer_canopy_properties.h.
         :  // Define basic module properties by passing its name to its parent class
           SteadyModule(module_name),
           // Store the number of layers
           nlayers(nlayers),
           // Get references to input parameters
           par_incident_direct(get_input(input_parameters, "par_incident_direct")),
           par_incident_diffuse(get_input(input_parameters, "par_incident_diffuse")),
           lai(get_input(input_parameters, "lai")),
           cosine_zenith_angle(get_input(input_parameters, "cosine_zenith_angle")),
           kd(get_input(input_parameters, "kd")),
           chil(get_input(input_parameters, "chil")),
           heightf(get_input(input_parameters, "heightf")),
           rh(get_input(input_parameters, "rh")),
           windspeed(get_input(input_parameters, "windspeed")),
           LeafN(get_input(input_parameters, "LeafN")),
           kpLN(get_input(input_parameters, "kpLN")),
           lnfun(get_input(input_parameters, "lnfun")),
           // Get pointers to output parameters
           sunlit_incident_par_ops(get_multilayer_op(output_parameters, nlayers, "sunlit_incident_par")),
           sunlit_fraction_ops(get_multilayer_op(output_parameters, nlayers, "sunlit_fraction")),
           shaded_incident_par_ops(get_multilayer_op(output_parameters, nlayers, "shaded_incident_par")),
           shaded_fraction_ops(get_multilayer_op(output_parameters, nlayers, "shaded_fraction")),
           incident_scattered_par_ops(get_multilayer_op(output_parameters, nlayers, "incident_scattered_par")),
           incident_average_par_ops(get_multilayer_op(output_parameters, nlayers, "incident_average_par")),
           height_ops(get_multilayer_op(output_parameters, nlayers, "height")),
           rh_ops(get_multilayer_op(output_parameters, nlayers, "rh")),
           windspeed_ops(get_multilayer_op(output_parameters, nlayers, "windspeed")),
           LeafN_ops(get_multilayer_op(output_parameters, nlayers, "LeafN"))
     {
     }
Member Function Documentation
define_leaf_classes()
std::vector< std::string > multilayer_canopy_properties::define_leaf_classes () static protected
Define the different leaf classes included by the module.
Definition at line 128 of file multilayer_canopy_properties.h.
 {
     return {
         "sunlit",  // these leaves receive diffuse, scattered, and direct solar radiation
         "shaded"   // these leaves receive diffuse and scattered solar radiation
     };
 }
Referenced by ten_layer_canopy_properties::define_leaf_classes(), and get_outputs().
define_multiclass_multilayer_outputs()
std::vector< std::string > multilayer_canopy_properties::define_multiclass_multilayer_outputs () static protected
Define all outputs that have different values for each leaf class and layer.
Definition at line 139 of file multilayer_canopy_properties.h.
 {
     return {
         "incident_par",  // J / (m^2 leaf) / s
         "fraction"       // dimensionless
     };
 }
Referenced by ten_layer_canopy_properties::define_multiclass_multilayer_outputs(), and get_outputs().
define_pure_multilayer_outputs()
std::vector< std::string > multilayer_canopy_properties::define_pure_multilayer_outputs () static protected
Define all outputs that have different values for each layer, not including outputs that also depend on leaf class.
Definition at line 151 of file multilayer_canopy_properties.h.
 {
     return {
         "incident_scattered_par",  // J / (m^2 leaf) / s
         "incident_average_par",    // J / (m^2 leaf) / s
         "height",                  // m
         "rh",                      // dimensionless from Pa / Pa
         "windspeed",               // m / s
         "LeafN",                   // mmol / m^2 (?)
     };
 }
Referenced by ten_layer_canopy_properties::define_pure_multilayer_outputs(), and get_outputs().
get_inputs()
std::vector< std::string > multilayer_canopy_properties::get_inputs (int nlayers) static protected
Define all inputs required by the module.
Definition at line 107 of file multilayer_canopy_properties.h.
 {
     return {
         "par_incident_direct",   // J / (m^2 beam) / s [area perpendicular to beam]
         "par_incident_diffuse",  // J / m^2 / s        [through any plane]
         "lai",                   // dimensionless from (m^2 leaf) / (m^2 ground). LAI of entire canopy.
         "cosine_zenith_angle",   // dimensionless
         "kd",                    // (m^2 ground) / (m^2 leaf)
         "chil",                  // dimensionless from m^2 / m^2
         "heightf",               // m^-1 from (m^2 / m^2) / m.  Leaf area density; LAI per height of canopy.
         "rh",                    // dimensionless from Pa / Pa
         "windspeed",             // m / s
         "LeafN",                 // mmol / m^2 (?)
         "kpLN",                  // dimensionless
         "lnfun",                 // a dimensionless switch
     };
 }
Referenced by ten_layer_canopy_properties::get_inputs().
get_outputs()
std::vector< std::string > multilayer_canopy_properties::get_outputs (int nlayers) static protected
Define all output names by appending leaf class prefixes and layer number suffixes. Here we should make use of the define_XXX functions to reduce code duplication.
Definition at line 167 of file multilayer_canopy_properties.h.
 {
     // Add leaf_class prefixes to the multiclass_multilayer outputs
     std::vector<std::string> multilayer_outputs = generate_multiclass_quantity_names(
         multilayer_canopy_properties::define_leaf_classes(),
         multilayer_canopy_properties::define_multiclass_multilayer_outputs());
     // Add other multilayer outputs
     for (std::string const& name : multilayer_canopy_properties::define_pure_multilayer_outputs()) {
         multilayer_outputs.push_back(name);
     }
     // Add layer number suffixes to all multilayer outputs
     // We can return the result immediately since there are no other outputs
     return generate_multilayer_quantity_names(nlayers, multilayer_outputs);
 }
References define_leaf_classes(), define_multiclass_multilayer_outputs(), and define_pure_multilayer_outputs().
Referenced by ten_layer_canopy_properties::get_outputs().
run()
void multilayer_canopy_properties::run () const protected
Definition at line 184 of file multilayer_canopy_properties.h.
 {
     // Calculate PAR levels throughout the canopy. Note that sunML specifies that its
     // `Idir` and `Idiff` arguments should have [micromol / m^2 / s] units. However,
     // we can leave these quantities as energy flux densities with [J / m^2 / s] units
     // because the two units are simply related by a multiplicative conversion factor
     // and the output of sunML is linear with respect to `Idir` and `Idiff`.
     struct Light_profile par_profile = sunML(par_incident_direct, par_incident_diffuse,
                                              lai, nlayers, cosine_zenith_angle, kd, chil, heightf);
     // Calculate relative humidity levels throughout the canopy
     double relative_humidity_profile[nlayers];
     RHprof(rh, nlayers, relative_humidity_profile);  // Modifies relative_humidity_profile.
     // Calculate windspeed throughout the canopy
     double wind_speed_profile[nlayers];
     WINDprof(windspeed, lai, nlayers, wind_speed_profile);  // Modifies wind_speed_profile.
     // Calculate leaf nitrogen throughout the canopy
     double leafN_profile[nlayers];
     LNprof(LeafN, lai, nlayers, kpLN, leafN_profile);  // Modifies leafN_profile.
     // Don't calculate anything based on the nitrogen profile
     if (lnfun != 0) {
         throw std::logic_error("Thrown by the multilayer_canopy_properties module: lnfun != 0 is not yet supported.");
     }
     // Update layer-dependent outputs
     for (int i = 0; i < nlayers; ++i) {
         update(sunlit_fraction_ops[i], par_profile.sunlit_fraction[i]);
         update(shaded_fraction_ops[i], par_profile.shaded_fraction[i]);
         update(height_ops[i], par_profile.height[i]);
         update(sunlit_incident_par_ops[i], par_profile.direct_irradiance[i]);
         update(incident_scattered_par_ops[i], par_profile.scattered_irradiance[i]);
         update(shaded_incident_par_ops[i], par_profile.diffuse_irradiance[i]);
         update(incident_average_par_ops[i], par_profile.total_irradiance[i]);
         update(rh_ops[i], relative_humidity_profile[i]);
         update(windspeed_ops[i], wind_speed_profile[i]);
         update(LeafN_ops[i], leafN_profile[i]);
     }
 }
References Light_profile::diffuse_irradiance, Light_profile::direct_irradiance, Light_profile::height, LNprof(), RHprof(), Light_profile::scattered_irradiance, Light_profile::shaded_fraction, Light_profile::sunlit_fraction, sunML(), Light_profile::total_irradiance, and WINDprof().
The documentation for this class was generated from the following file:
/github/workspace/source/src/module_library/multilayer_canopy_properties.h