BioCro: simultaneous_equations Class Reference
simultaneous_equations Class Reference
Defines a set of simultaneous equations.
#include <simultaneous_equations.h>
Public Member Functions
simultaneous_equations (state_map const &known_quantities, string_vector const &unknown_quantities, string_vector const &ss_module_names)
void update_known_quantities (std::vector< const double * > const &ptrs_to_values)
Updates the values of the known quantities using the values pointed to by the elements of ptrs_to_values. The elements of ptr_to_values must be sorted according to quantity name.
template<typename vector_type >
void get_all_outputs (std::vector< double > &vector_to_update, vector_type const &unknown_quantity_vector)
Updates the values of vector_to_update using the values pointed to by the elements of the private member output_ptrs. The elements of vector_to_update must be sorted according to quantity name. Values of the unknown quantities are used to calculate the outputs.
template<typename in_vector_type , typename out_vector_type >
void operator() (in_vector_type const &unknown_quantity_vector, out_vector_type &difference_vector)
Calculates the change in value of the unknown quantities given a vector of initial values.
int get_ncalls () const
void reset_ncalls ()
std::string generate_startup_report () const
std::string generate_usage_report () const
Detailed Description
Defines a set of simultaneous equations.
Definition at line 20 of file simultaneous_equations.h.
Constructor & Destructor Documentation
simultaneous_equations()
simultaneous_equations::simultaneous_equations (state_map const & known_quantities, string_vector const & unknown_quantities, string_vector const & ss_module_names)
Definition at line 150 of file simultaneous_equations.cpp.
 {
     startup_message = std::string("");
     // Make sure the inputs can form a valid set of simultaneous equations
     bool valid = validate_simultaneous_equations_inputs(startup_message, known_quantities, unknown_quantities, ss_module_names);
     if (!valid) {
         throw std::logic_error("Thrown by simultaneous_equations::simultaneous_equations: the supplied inputs cannot form a valid set of simultaneous equations.\n\n" + startup_message);
     }
     // Make the central list of quantities and the module output map
     quantities = define_quantity_map(
         std::vector<state_map>{known_quantities},
         std::vector<string_vector>{ss_module_names});
     module_output_map = quantities;
     // Instantiate the modules
     steady_state_modules = get_module_vector(std::vector<string_vector>{ss_module_names}, &quantities, &module_output_map);
     // Make sorted lists of subsets of quantity names
     // Note that the output of string_set_to_string_vector is automatically
     //  sorted, because a string_set is always sorted by definition.
     string_vector steady_state_output_names = string_set_to_string_vector(find_unique_module_outputs(std::vector<string_vector>{ss_module_names}));
     string_vector known_quantity_names = keys(known_quantities);
     std::sort(known_quantity_names.begin(), known_quantity_names.end());
     // Get vectors of pointers to important subsets of the quantities.
     // These pointers allow the user to update the values of the known
     //  quantities and to retrieve the values of all module outputs.
     // Here it is important to use sorted vectors of names so the
     //  quantities will have a definite order that the user can safely
     //  assume.
     known_ptrs = get_pointers(known_quantity_names, quantities);
     output_ptrs = get_const_pointers(steady_state_output_names, quantities);
     // Get vectors of pointers to important subsets of the quantities.
     // These pointers allow us to efficiently alter portions of the
     //  quantity maps before running the modules.
     unknown_ptrs = get_pointers(unknown_quantities, quantities);
     steady_state_ptrs = get_pointers(steady_state_output_names, module_output_map);
     // Get pairs of pointers to important subsets of the quantities.
     // These pairs allow us to efficiently retrieve the output of each
     //  module and store it in the main quantity map
     unknown_ptr_pairs = get_pointer_pairs(unknown_quantities, quantities, module_output_map);
     steady_state_ptr_pairs = get_pointer_pairs(steady_state_output_names, quantities, module_output_map);
 }
References define_quantity_map(), find_unique_module_outputs(), get_const_pointers(), get_module_vector(), get_pointer_pairs(), get_pointers(), keys(), string_set_to_string_vector(), ed_leaf_photosynthesis_nr::unknown_quantities, and validate_simultaneous_equations_inputs().
Member Function Documentation
generate_startup_report()
std::string simultaneous_equations::generate_startup_report () const inline
Definition at line 41 of file simultaneous_equations.h.
 { return startup_message; }
generate_usage_report()
std::string simultaneous_equations::generate_usage_report () const inline
Definition at line 43 of file simultaneous_equations.h.
     {
         return std::string("The simultaneous equations were evaluated ") +
                std::to_string(ncalls) +
                std::string(" times");
     }
get_all_outputs()
template<typename vector_type > void simultaneous_equations::get_all_outputs (std::vector< double > & vector_to_update, vector_type const & unknown_quantity_vector)
Updates the values of vector_to_update using the values pointed to by the elements of the private member output_ptrs. The elements of vector_to_update must be sorted according to quantity name. Values of the unknown quantities are used to calculate the outputs.
Definition at line 81 of file simultaneous_equations.h.
 {
     if (vector_to_update.size() != output_ptrs.size()) {
         throw std::logic_error("Thrown by simultaneous_equations::update_known_quantities: vector_to_update has the wrong size.");
     }
     run_modules(unknown_quantity_vector);
     for (size_t i = 0; i < output_ptrs.size(); ++i) {
         vector_to_update[i] = *output_ptrs[i];
     }
 }
get_ncalls()
int simultaneous_equations::get_ncalls () const inline
Definition at line 39 of file simultaneous_equations.h.
 { return ncalls; }
operator()()
template<typename in_vector_type , typename out_vector_type > void simultaneous_equations::operator() (in_vector_type const & unknown_quantity_vector, out_vector_type & difference_vector)
Calculates the change in value of the unknown quantities given a vector of initial values.
To solve the set of equations, we seek a set of initial values that produces a vector of zeroes when used as an input to this function.
Parameters
[in] unknown_quantity_vector a vector of initial values for the unknown quantities
[out] difference_vector a vector of (final - initial) values for the unknown quantities
Definition at line 106 of file simultaneous_equations.h.
 {
     run_modules(unknown_quantity_vector);
     // Get the calculated values of the unknown quantities from the main quantity map
     for (size_t i = 0; i < unknown_ptrs.size(); i++) {
         difference_vector[i] = *(unknown_ptrs[i]) - unknown_quantity_vector[i];
     }
 }
reset_ncalls()
void simultaneous_equations::reset_ncalls () inline
Definition at line 40 of file simultaneous_equations.h.
 { ncalls = 0; }
update_known_quantities()
void simultaneous_equations::update_known_quantities (std::vector< const double * > const & ptrs_to_values)
Updates the values of the known quantities using the values pointed to by the elements of ptrs_to_values. The elements of ptr_to_values must be sorted according to quantity name.
Definition at line 205 of file simultaneous_equations.cpp.
 {
     if (ptrs_to_values.size() != known_ptrs.size()) {
         throw std::logic_error("Thrown by simultaneous_equations::update_known_quantities: ptrs_to_values has the wrong size.");
     }
     for (size_t i = 0; i < known_ptrs.size(); ++i) {
         *known_ptrs[i] = *ptrs_to_values[i];
     }
 }
The documentation for this class was generated from the following files:
/github/workspace/source/src/simultaneous_equations.h
/github/workspace/source/src/simultaneous_equations.cpp