BioCro: Standalone_SS Class Reference
Standalone_SS Class Reference
This class defines a standalone steady state module, i.e., a module that can easily be used without creating a system. It may be formed from one or more steady state modules. Its main intended use is to allow modules to call other modules as part of their operation.
#include <standalone_ss.h>
Public Member Functions
Standalone_SS (string_vector const &ss_module_names, std::unordered_map< std::string, const double * > const &input_ptrs, std::unordered_map< std::string, double * > const &output_ptrs)
bool is_adaptive_compatible () const
string_set get_inputs () const
string_vector get_outputs () const
std::string generate_startup_report () const
void run () const
Gets values from the objects pointed to by the input_ptrs, runs each module, and exports the results to the objects pointed to by the output_ptrs.
Detailed Description
This class defines a standalone steady state module, i.e., a module that can easily be used without creating a system. It may be formed from one or more steady state modules. Its main intended use is to allow modules to call other modules as part of their operation.
Definition at line 28 of file standalone_ss.h.
Constructor & Destructor Documentation
Standalone_SS()
Standalone_SS::Standalone_SS (string_vector const & ss_module_names, std::unordered_map< std::string, const double * > const & input_ptrs, std::unordered_map< std::string, double * > const & output_ptrs)
Definition at line 103 of file standalone_ss.cpp.
                                                              : steady_state_module_names(ss_module_names)
 {
     startup_message = std::string("");
     // Make sure the inputs can form a valid Standalone_SS
     bool valid = validate_standalone_ss_inputs(startup_message, ss_module_names, input_ptrs, output_ptrs);
     if (!valid) {
         throw std::logic_error("Thrown by Standalone_SS::Standalone_SS: the supplied inputs cannot form a valid Standalone_SS.\n\n" + startup_message);
     }
     // Make the central list of quantities and the module output map
     quantities = define_quantity_map(
         std::vector<state_map>{state_map_from_names(keys(input_ptrs))},
         std::vector<string_vector>{ss_module_names});
     module_output_map = quantities;
     // Instantiate the modules
     steady_state_modules = get_module_vector(std::vector<string_vector>{ss_module_names}, &quantities, &module_output_map);
     // Make lists of subsets of quantity names
     string_set module_outputs = find_unique_module_outputs(std::vector<string_vector>{ss_module_names});
     // Get vectors of pointers to important subsets of the quantities
     // These pointers allow us to efficiently reset portions of the
     //  module output map before running the modules
     module_output_ptrs = get_pointers(module_outputs, quantities);
     // Get pairs of pointers to important subsets of the quantities
     // These pairs allow us to efficiently retrieve the output of each
     //  module and store it in the main quantity map when running the system,
     //  report the results of a calculation using the output_ptrs, etc
     module_output_ptr_pairs = get_pointer_pairs(module_outputs, quantities, module_output_map);
     input_ptr_pairs = get_input_pointer_pairs(quantities, input_ptrs);
     output_ptr_pairs = get_output_pointer_pairs(quantities, output_ptrs);
 }
References define_quantity_map(), find_unique_module_outputs(), get_input_pointer_pairs(), get_module_vector(), get_output_pointer_pairs(), get_pointer_pairs(), get_pointers(), keys(), state_map_from_names(), and validate_standalone_ss_inputs().
Member Function Documentation
generate_startup_report()
std::string Standalone_SS::generate_startup_report () const inline
Definition at line 51 of file standalone_ss.h.
 { return startup_message; }
Referenced by R_test_standalone_ss().
get_inputs()
string_set Standalone_SS::get_inputs () const inline
Definition at line 42 of file standalone_ss.h.
{
         return find_strictly_required_inputs(std::vector<string_vector>{steady_state_module_names});
     }
References find_strictly_required_inputs().
get_outputs()
string_vector Standalone_SS::get_outputs () const inline
Definition at line 46 of file standalone_ss.h.
{
         return string_set_to_string_vector(find_unique_module_outputs(std::vector<string_vector>{steady_state_module_names}));
     }
References find_unique_module_outputs(), and string_set_to_string_vector().
is_adaptive_compatible()
bool Standalone_SS::is_adaptive_compatible () const inline
Definition at line 37 of file standalone_ss.h.
     {
         return check_adaptive_compatible(&steady_state_modules);
     }
References check_adaptive_compatible().
run()
void Standalone_SS::run () const
Gets values from the objects pointed to by the input_ptrs, runs each module, and exports the results to the objects pointed to by the output_ptrs.
Definition at line 147 of file standalone_ss.cpp.
 {
     // Get the input parameter values
     for (auto const& x : input_ptr_pairs) {
         *x.first = *x.second;
     }
     // Clear the module output map
     for (double* const& x : module_output_ptrs) {
         *x = 0.0;
     }
     // Run each module and store its output in the main quantity map
     for (std::unique_ptr<Module> const& m : steady_state_modules) {
         m->run();
         for (auto const& x : module_output_ptr_pairs) {
             *x.first = *x.second;
         }
     }
     // Export the parameter values
     for (auto const& x : output_ptr_pairs) {
         *x.second = *x.first;
     }
 }
Referenced by R_test_standalone_ss().
The documentation for this class was generated from the following files:
/github/workspace/source/src/standalone_ss.h
/github/workspace/source/src/standalone_ss.cpp