BioCro: module_wrapper_factory Class Reference
module_wrapper_factory Class Reference
#include <module_wrapper_factory.h>
Static Public Member Functions
static std::unique_ptr< module_wrapper_base > create (std::string const &module_name)
static std::string get_description (std::string const &module_name)
static std::vector< std::string > get_modules ()
static std::unordered_map< std::string, std::vector< std::string > > get_all_quantities ()
Detailed Description
Definition at line 11 of file module_wrapper_factory.h.
Member Function Documentation
create()
std::unique_ptr< module_wrapper_base > module_wrapper_factory::create (std::string const & module_name) static
Definition at line 106 of file module_wrapper_factory.cpp.
 {
     try {
         return module_wrapper_factory::module_wrapper_creators.at(module_name)();
     } catch (std::out_of_range) {
         std::string message = std::string("\"") + module_name +
                        std::string("\"") +
                        std::string(" was given as a module name, ") +
                        std::string("but no module with that name could be found.\n");
         throw std::out_of_range(message);
     }
 }
Referenced by ed_leaf_photosynthesis::check_module_io_equivalence(), define_quantity_map(), find_misordered_modules(), find_strictly_required_inputs(), find_undefined_module_inputs(), find_undefined_module_outputs(), find_unique_module_inputs(), find_unique_module_outputs(), get_all_quantities(), get_defined_quantity_names(), get_module_inputs(), get_module_outputs(), get_module_vector(), R_get_module_info(), R_test_module(), and R_test_standalone_ss().
get_all_quantities()
std::unordered_map< std::string, std::vector< std::string > > module_wrapper_factory::get_all_quantities () static
Definition at line 249 of file module_wrapper_factory.cpp.
 {
     // Make the output map
     std::unordered_map<std::string, std::vector<std::string>> quantity_map = {
         {"module_name",     std::vector<std::string>{}},
         {"quantity_type",   std::vector<std::string>{}},
         {"quantity_name",   std::vector<std::string>{}}
     };
     // Make a lambda function for adding entries to the map
     auto add_quantity_map_entry = [&quantity_map](std::string module_name, std::string quantity_type, std::string quantity_name) {
         quantity_map["module_name"].push_back(module_name);
         quantity_map["quantity_type"].push_back(quantity_type);
         quantity_map["quantity_name"].push_back(quantity_name);
     };
     // Fill the output map with all the quantities
     for (std::string const& module_name : module_wrapper_factory::get_modules()) {
         auto w = module_wrapper_factory::create(module_name);
         // Add the module's inputs to the parameter map
         for (std::string const& input_name : w->get_inputs()) {
             add_quantity_map_entry(module_name, "input", input_name);
         }
         // Add the module's outputs to the parameter map
         for (std::string const& output_name : w->get_outputs()) {
             add_quantity_map_entry(module_name, "output", output_name);
         }
     }
     return quantity_map;
 }
References create(), and get_modules().
Referenced by R_get_all_quantities().
get_description()
static std::string module_wrapper_factory::get_description (std::string const & module_name) static
get_modules()
std::vector< std::string > module_wrapper_factory::get_modules () static
Definition at line 224 of file module_wrapper_factory.cpp.
 {
     std::vector<std::string> module_name_vector;
     for (auto const& x : module_wrapper_creators) {
         module_name_vector.push_back(x.first);
     }
     auto case_insensitive_compare = [](std::string const& a, std::string const& b) {
         // Make a lowercase copy of a
         std::string al = a;
         std::transform(al.begin(), al.end(), al.begin(), [](unsigned char c) { return std::tolower(c); });
         // Make a lowercase copy of b
         std::string bl = b;
         std::transform(bl.begin(), bl.end(), bl.begin(), [](unsigned char c) { return std::tolower(c); });
         int compare = al.compare(bl);
         return (compare > 0) ? false : true;
     };
     std::sort(module_name_vector.begin(), module_name_vector.end(), case_insensitive_compare);
     return module_name_vector;
 }
Referenced by get_all_quantities(), and R_get_all_modules().
The documentation for this class was generated from the following files:
/github/workspace/source/src/module_library/module_wrapper_factory.h
/github/workspace/source/src/module_library/module_wrapper_factory.cpp