BioCro: se_solver Class Reference
se_solver Class Reference abstract
An abstract class for a generic simultaneous equation solver. Its solve member function provides a uniform interface for all derived solvers, and its constructor defines inputs that are common to all solvers.
#include <se_solver.h>
Public Member Functions
se_solver (std::string solver_name, double rel_error_tol, double abs_error_tol, int max_it)
virtual ~se_solver ()=0
template<typename observer_type >
bool solve (std::unique_ptr< simultaneous_equations > const &se, std::vector< double > const &initial_guess_for_root, std::vector< double > const &lower_bounds, std::vector< double > const &upper_bounds, std::vector< double > &final_value_for_root, observer_type observer)
Tries to find a root, starting at the initial guess and staying within the bounds.
bool solve (std::unique_ptr< simultaneous_equations > const &se, std::vector< double > const &initial_guess_for_root, std::vector< double > const &lower_bounds, std::vector< double > const &upper_bounds, std::vector< double > &final_value_for_root)
std::string generate_info_report () const
Returns a string describing the se_solver's basic properties.
std::string generate_solve_report () const
Returns a string describing what happened during the most recent attempt to find a root.
Detailed Description
An abstract class for a generic simultaneous equation solver. Its solve member function provides a uniform interface for all derived solvers, and its constructor defines inputs that are common to all solvers.
Definition at line 29 of file se_solver.h.
Constructor & Destructor Documentation
se_solver()
se_solver::se_solver (std::string solver_name, double rel_error_tol, double abs_error_tol, int max_it) inline
Definition at line 32 of file se_solver.h.
                     : solver_name(solver_name),
                       rel_error_tolerance(rel_error_tol),
                       abs_error_tolerance(abs_error_tol),
                       max_iterations(max_it) {}
~se_solver()
se_solver::~se_solver () inline pure virtual
Definition at line 90 of file se_solver.h.
 {
 }
Member Function Documentation
generate_info_report()
std::string se_solver::generate_info_report () const
Returns a string describing the se_solver's basic properties.
Definition at line 70 of file se_solver.cpp.
 {
     return std::string("Name: ") + solver_name +
            std::string("\nRelative error tolerance: ") + std::to_string(rel_error_tolerance) +
            std::string("\nAbsolute error tolerance: ") + std::to_string(abs_error_tolerance) +
            std::string("\nMaximum number of iterations: ") + std::to_string(max_iterations);
 }
generate_solve_report()
std::string se_solver::generate_solve_report () const
Returns a string describing what happened during the most recent attempt to find a root.
Definition at line 82 of file se_solver.cpp.
 {
     if (!solve_method_has_been_called) {
         return std::string("The solver has not been called yet");
     } else {
         auto bool_to_string = [](bool b) -> std::string {
             return b ? std::string("Yes") : std::string("No");
         };
         return std::string("Details about the most recent calculation:") +
                std::string("\n Converged according to absolute threshold: ") + bool_to_string(converged_abs) +
                std::string("\n Converged according to relative threshold: ") + bool_to_string(converged_rel) +
                std::string("\n Number of iterations: ") + std::to_string(num_iterations) +
                std::string("\n Number of adjustments: ") + std::to_string(num_adjustments);
     }
 }
solve() [1/2]
bool se_solver::solve (std::unique_ptr< simultaneous_equations > const & se, std::vector< double > const & initial_guess_for_root, std::vector< double > const & lower_bounds, std::vector< double > const & upper_bounds, std::vector< double > & final_value_for_root) inline
Definition at line 53 of file se_solver.h.
     {
         return solve(se, initial_guess_for_root, lower_bounds, upper_bounds, final_value_for_root, se_observer_null());
     }
References solve().
solve() [2/2]
template<typename observer_type > bool se_solver::solve (std::unique_ptr< simultaneous_equations > const & se, std::vector< double > const & initial_guess_for_root, std::vector< double > const & lower_bounds, std::vector< double > const & upper_bounds, std::vector< double > & final_value_for_root, observer_type observer)
Tries to find a root, starting at the initial guess and staying within the bounds.
Parameters
[in] se
[in] initial_guess_for_root
[in] lower_bounds
[in] upper_bounds
[out] final_value_for_root
[in] observer an object with an operator()(std::vector<double> const& uq, bool adjustment_made) method. This method will be called at each step of the solution process.
Returns
indicates whether or not the procedure was successful in finding a root.
The solver proceeds by steps, in which a new guess for the root is determined from the previous guess using the get_next_guess method, which must be implemented by derived classes. When a new guess is found, it is first checked to see if it lies within the acceptable bounds. If it lies outside the bounds, it is adjusted with the adjust_bad_guess method, which has a default behavior but can be overridden by derived classes. If the new guess doesn't need an adjustment, it is compared to the previous guess to check for convergence using either an absolute or relative threshold. The process ends when all convergence criteria (relative and absolute) have been met or when the number of iterations exceeds a threshold value.
Definition at line 121 of file se_solver.h.
 {
     // Reset all the status indicators
     solve_method_has_been_called = true;
     converged_abs = false;
     converged_rel = false;
     num_iterations = 0;
     num_adjustments = 0;
     // Pass the first guess to the observer
     observer(initial_guess_for_root, false);
     // Initialize temporary variables for the loop
     std::vector<double> previous_guess = initial_guess_for_root;
     std::vector<double> next_guess = initial_guess_for_root;
     bool need_to_make_adjustment;
     // Define a lambda to simplify error checking
     auto errors_occurred = [](std::vector<bool> error_vector) -> bool {
         int num_errors = std::accumulate(error_vector.begin(), error_vector.end(), 0);
         return num_errors > 0;
     };
     // Define a lambda to simplify convergence checking
     auto check_convergence = [&errors_occurred](std::vector<bool> convergence_error_vector, bool* convergence_achieved) -> void {
         if (!errors_occurred(convergence_error_vector)) {
             *convergence_achieved = true;
         }
     };
     // Run the loop until convergence is achieved or the max number of iterations is exceeded
     do {
         ++num_iterations;
         next_guess = get_next_guess(se, previous_guess);
         need_to_make_adjustment = errors_occurred(is_outside_bounds(next_guess, lower_bounds, upper_bounds));
         if (need_to_make_adjustment) {
             ++num_adjustments;
             next_guess = adjust_bad_guess(next_guess, lower_bounds, upper_bounds);
         } else {
             std::map<bool*, std::vector<bool>> convergence_checks = {
                 {&converged_abs, has_not_converged_abs(previous_guess, next_guess, abs_error_tolerance)},
                 {&converged_rel, has_not_converged_rel(previous_guess, next_guess, rel_error_tolerance)}};
             for (auto const& x : convergence_checks) {
                 check_convergence(x.second, x.first);
             }
         }
         observer(next_guess, need_to_make_adjustment);
         previous_guess = next_guess;
     } while (num_iterations < max_iterations && !(converged_abs && converged_rel));
     final_value_for_root = next_guess;
     return converged_abs && converged_rel;
 }
References has_not_converged_abs(), has_not_converged_rel(), and is_outside_bounds().
Referenced by solve().
The documentation for this class was generated from the following files:
/github/workspace/source/src/se_solver.h
/github/workspace/source/src/se_solver.cpp