BioCro: /github/workspace/source/src/utils/module_dependency_utilities.h File Reference
module_dependency_utilities.h File Reference
#include <boost/graph/topological_sort.hpp>
#include "../validate_system.h"
Functions
string_vector get_evaluation_order (string_vector module_names)
bool has_cyclic_dependency (string_vector module_names)
bool order_ok (string_vector module_names)
Function Documentation
get_evaluation_order()
string_vector get_evaluation_order (string_vector module_names)
Given a list of steady-state module names (presented as a vector of strings), return the same list in a suitable order for evaluating the modules.
If no such ordering exists (due to a cyclic dependency), the function throws an exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::not_a_dag>>.
Parameters
module_names A list (presented as a vector of strings) of names of steady-state modules.
Returns
The same list given in module_names, but ordered so that each module in the list depends only on modules occuring earlier in the list.
Note
Even if the input list module_names is already in a suitable evaluation order, the output list may nevertheless give the modules in a different order.
Exceptions
boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::not_a_dag>> Thrown if there is no suitable evaluation order due to a cyclic dependency in the set of modules specified by module_names.
Definition at line 327 of file module_dependency_utilities.cpp.
{
     Graph g = get_dependency_graph(module_names);
     vertex_list evaluation_order = get_topological_ordering(g);
     module_name_map_t name_map = get(vertex_name, g);
     string_vector ordered_module_list;
     for (vertex_list::iterator i = evaluation_order.begin();
          i != evaluation_order.end();
          ++i)
     {
         ordered_module_list.push_back(name_map[*i]);
     }
     return ordered_module_list;
 }
References get_dependency_graph(), and get_topological_ordering().
Referenced by analyze_system_inputs().
has_cyclic_dependency()
bool has_cyclic_dependency (string_vector module_names)
Given a list of steady-state module names (presented as a vector of strings), determine if the list can be put in a suitable order for evaluating the modules.
Parameters
module_names A list (presented as a vector of strings) of names of steady-state modules.
Returns
true if there is a cyclic dependency among the given modules so that they cannot be suitably ordered; false otherwise.
Definition at line 241 of file module_dependency_utilities.cpp.
{
     Graph g = get_dependency_graph(module_names);
     return has_cycle(g);
 }
References get_dependency_graph(), and has_cycle().
Referenced by analyze_system_inputs(), and validate_system_inputs().
order_ok()
bool order_ok (string_vector module_names)
Determines whether the steady-state modules in module_names need to be reordered before evaluation.
Parameters
module_names A list (presented as a vector of strings) of names of steady-state modules.
Returns
true if the list of modules as given in module_names is a suitable evaluation order, false otherwise.
Definition at line 257 of file module_dependency_utilities.cpp.
{
     for (int i = 0; i < module_names.size(); ++i) {
         for (int j = i; j < module_names.size(); ++j) {
             if (depends_on(module_names[i], module_names[j])) {
                 return false;
             }
         }
     }
     return true;
 }
References depends_on().
Referenced by analyze_system_inputs().