BioCro: /github/workspace/source/src/utils/module_dependency_utilities.cpp File Reference
module_dependency_utilities.cpp File Reference
#include "module_dependency_utilities.h"
#include <boost/config.hpp>
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/topological_sort.hpp>
#include "../module_library/module_wrapper_factory.h"
#include "../state_map.h"
#include "../validate_system.h"
Data Structures
class cycle_detector
Typedefs
using Graph = boost::adjacency_list< boost::setS, boost::listS, boost::directedS, boost::property< boost::vertex_name_t, std::string, boost::property< boost::vertex_index_t, std::size_t > > >
using module_name_map_t = boost::property_map< Graph, boost::vertex_name_t >::type
using index_map_t = boost::property_map< Graph, boost::vertex_index_t >::type
using Vertex = boost::graph_traits< Graph >::vertex_descriptor
using vertex_list = std::list< Vertex >
using vertex_iterator = boost::graph_traits< Graph >::vertex_iterator
Functions
string_vector get_module_inputs (string module_name)
string_vector get_module_outputs (string module_name)
bool depends_on (string m1, string m2)
Graph get_dependency_graph (string_vector module_names)
bool has_cycle (Graph g)
bool has_cyclic_dependency (string_vector module_names)
bool order_ok (string_vector module_names)
vertex_list get_topological_ordering (const Graph &g)
string_vector get_evaluation_order (string_vector module_names)
Typedef Documentation
Graph
using Graph = boost::adjacency_list< boost::setS, boost::listS, boost::directedS, boost::property<boost::vertex_name_t, std::string, boost::property<boost::vertex_index_t, std::size_t> > >
Graph is the type of a directed Boost graph without multi-edges implemented as an adjacency list and having vertex name and vertex index properties.
Definition at line 31 of file module_dependency_utilities.cpp.
index_map_t
using index_map_t = boost::property_map<Graph, boost::vertex_index_t>::type
index_map_t is the type for the map mapping Graph vertex descriptors to the vertex index. (We wouldn't need this if we used vecS instead of listS for the VertexList adjacency_list template paramater. But this allows us to use either.)
Definition at line 52 of file module_dependency_utilities.cpp.
module_name_map_t
using module_name_map_t = boost::property_map<Graph, boost::vertex_name_t>::type
module_name_map_t is the type for the map mapping Graph vertex descriptors to names. In our case, these will be steady-state module names.
Definition at line 44 of file module_dependency_utilities.cpp.
Vertex
using Vertex = boost::graph_traits<Graph>::vertex_descriptor
Vertex is the type of the vertex used by Graph.
Definition at line 57 of file module_dependency_utilities.cpp.
vertex_iterator
using vertex_iterator = boost::graph_traits<Graph>::vertex_iterator
vertex_iterator is the type of an iterator that may be used to iterate through any container of vertices from a graph of type Graph.
Definition at line 70 of file module_dependency_utilities.cpp.
vertex_list
using vertex_list = std::list<Vertex>
vertex_list is a std::list containing Vertex objects. Used for storing the module evaluation order.
Definition at line 63 of file module_dependency_utilities.cpp.
Function Documentation
depends_on()
bool depends_on (string m1, string m2)
Determines if the module named by m1 depends on the module named by m2, returning true if it does and false if not. m1 depends on m2 if and only if some input of m1 corresponds to some output of m2.
Parameters
[in] m1 A steady-state module name.
[in] m2 A steady-state module name.
Returns
true if the module named by m1 depends upon the module named by m2, false otherwise.
Definition at line 124 of file module_dependency_utilities.cpp.
{
     string_vector m1_inputs = get_module_inputs(m1);
     string_vector m2_outputs = get_module_outputs(m2);
     string_vector result;
     // set_intersection relies on both ranges being sorted, which they are.
     set_intersection(m1_inputs.begin(), m1_inputs.end(),
                      m2_outputs.begin(), m2_outputs.end(),
                      back_inserter(result));
     // If m1's inputs overlap with m2's outputs (i.e., their intersection is
     // non-empty), m1 depends on m2:
     return result.size() != 0;
 }
References get_module_inputs(), and get_module_outputs().
Referenced by get_dependency_graph(), and order_ok().
get_dependency_graph()
Graph get_dependency_graph (string_vector module_names)
Creates and returns a graph that models the dependency structure of the steady-state modules listed in module_names. There is a directed edge from the vertex for module A to the vertex for module B if A is depended upon by B, that is, if B depends on A.
Parameters
module_names A list (presented as a vector of strings) of names of steady-state modules.
Returns
A Graph object modeling the dependency structure of the steady-state modules listed in module_names.
Definition at line 152 of file module_dependency_utilities.cpp.
{
     int N = module_names.size();
     Graph g(N);
     module_name_map_t name_map = get(vertex_name, g);
     index_map_t index_map = get(vertex_index, g);
     vertex_iterator vi;
     vertex_iterator vi_end;
     int i = 0;
     for (tie(vi, vi_end) = vertices(g); vi != vi_end; ++vi, ++i) {
         name_map[*vi] = module_names[i];
         // If the adjacency_list VertexList parameter is vecS, then
         // index_map will be read-only; but it will be set properly so
         // that the body of this if statement is not executed.  On the
         // other hand, if it is listS, then we must set it manually:
         if (index_map[*vi] != i) {
             index_map[*vi] = i;
         }
     }
     vertex_iterator vi2;
     vertex_iterator vi2_end;
     for (tie(vi, vi_end) = vertices(g); vi != vi_end; ++vi) {
         for (tie(vi2, vi2_end) = vertices(g); vi2 != vi2_end; ++vi2) {
             if (depends_on(name_map[*vi], name_map[*vi2])) {
                 add_edge(*vi2, *vi, g);
             }
         }
     }
     return g;
 }
References depends_on().
Referenced by get_evaluation_order(), and has_cyclic_dependency().
get_evaluation_order()
string_vector get_evaluation_order (string_vector module_names)
Given a list of steady-state module names (presented as a vector of strings), return the same list in a suitable order for evaluating the modules.
If no such ordering exists (due to a cyclic dependency), the function throws an exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::not_a_dag>>.
Parameters
module_names A list (presented as a vector of strings) of names of steady-state modules.
Returns
The same list given in module_names, but ordered so that each module in the list depends only on modules occuring earlier in the list.
Note
Even if the input list module_names is already in a suitable evaluation order, the output list may nevertheless give the modules in a different order.
Exceptions
boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::not_a_dag>> Thrown if there is no suitable evaluation order due to a cyclic dependency in the set of modules specified by module_names.
Definition at line 327 of file module_dependency_utilities.cpp.
{
     Graph g = get_dependency_graph(module_names);
     vertex_list evaluation_order = get_topological_ordering(g);
     module_name_map_t name_map = get(vertex_name, g);
     string_vector ordered_module_list;
     for (vertex_list::iterator i = evaluation_order.begin();
          i != evaluation_order.end();
          ++i)
     {
         ordered_module_list.push_back(name_map[*i]);
     }
     return ordered_module_list;
 }
References get_dependency_graph(), and get_topological_ordering().
Referenced by analyze_system_inputs().
get_module_inputs()
string_vector get_module_inputs (string module_name)
Returns a list (presented as a sorted vector of strings) of all inputs for the module having name module_name.
Parameters
[in] module_name The name of a steady-state module.
Returns
A list (presented as a sorted vector of strings) of all inputs for the module having name module_name.
Definition at line 89 of file module_dependency_utilities.cpp.
{
     string_vector inputs { module_wrapper_factory::create(module_name)->get_inputs() };
     sort(inputs.begin(), inputs.end());
     return inputs;
 }
References module_wrapper_factory::create().
Referenced by depends_on().
get_module_outputs()
string_vector get_module_outputs (string module_name)
Returns a list (presented as a sorted vector of strings) of all outputs for the module having name module_name.
Parameters
[in] module_name The name of a steady-state module.
Returns
A list (presented as a sorted vector of strings) of all outputs for the module having name module_name.
Definition at line 104 of file module_dependency_utilities.cpp.
{
     string_vector outputs { module_wrapper_factory::create(module_name)->get_outputs() };
     sort(outputs.begin(), outputs.end());
     return outputs;
 }
References module_wrapper_factory::create().
Referenced by depends_on().
get_topological_ordering()
vertex_list get_topological_ordering (const Graph & g)
Given a directed acyclic graph g, return a ordered list of the vertices (presented as a vertex_list object) such that for each edge of the graph, the source vertex of the edge occurs in the list before the target vertex of the edge.
If g is not actually a directed acyclic graph, the function throws an exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::not_a_dag>>.
Parameters
g A Graph object corresponding to a directed acyclic graph.
Returns
A list of the vertices of g (presented as a list of Vertex objects) ordered so the module associated with each vertex in the list depends only on modules associated with vertices occuring earlier in the list.
Exceptions
boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::not_a_dag>> if g is not acyclic.
Note
g is passed by (const) reference not merely for efficiency, but so that the returned vertex list will actually be a list of vertices of g, not a list of vertices of a copy of g. This matters when we try to get the names of the vertices in the list.
Definition at line 296 of file module_dependency_utilities.cpp.
{
     vertex_list topological_order;
     topological_sort(g, front_inserter(topological_order));
     return topological_order;
 }
Referenced by get_evaluation_order().
has_cycle()
bool has_cycle (Graph g)
Given a directed graph g, return true if g has a cycle, false otherwise.
Parameters
g A graph object of type Graph.
Returns
true if directed graph g has a cycle, false if it is acyclic.
Definition at line 219 of file module_dependency_utilities.cpp.
{
     bool has_cycle = false;
     cycle_detector vis(has_cycle);
     depth_first_search(g, visitor(vis));
     return has_cycle;
 }
Referenced by cycle_detector::cycle_detector(), and has_cyclic_dependency().
has_cyclic_dependency()
bool has_cyclic_dependency (string_vector module_names)
Given a list of steady-state module names (presented as a vector of strings), determine if the list can be put in a suitable order for evaluating the modules.
Parameters
module_names A list (presented as a vector of strings) of names of steady-state modules.
Returns
true if there is a cyclic dependency among the given modules so that they cannot be suitably ordered; false otherwise.
Definition at line 241 of file module_dependency_utilities.cpp.
{
     Graph g = get_dependency_graph(module_names);
     return has_cycle(g);
 }
References get_dependency_graph(), and has_cycle().
Referenced by analyze_system_inputs(), and validate_system_inputs().
order_ok()
bool order_ok (string_vector module_names)
Determines whether the steady-state modules in module_names need to be reordered before evaluation.
Parameters
module_names A list (presented as a vector of strings) of names of steady-state modules.
Returns
true if the list of modules as given in module_names is a suitable evaluation order, false otherwise.
Definition at line 257 of file module_dependency_utilities.cpp.
{
     for (int i = 0; i < module_names.size(); ++i) {
         for (int j = i; j < module_names.size(); ++j) {
             if (depends_on(module_names[i], module_names[j])) {
                 return false;
             }
         }
     }
     return true;
 }
References depends_on().
Referenced by analyze_system_inputs().