BioCro: ed_leaf_photosynthesis Namespace Reference
ed_leaf_photosynthesis Namespace Reference
Data Structures
class module_base
A general module representing photosynthesis calculations. Note that this module cannot be created by the module_wrapper_factory since its constructor has a different signature than a typical module. Instead, it must have concrete derived classes. This class has been made abstract to indicate this. Note also that this module does not have a do_operation method defined.
Functions
string_vector get_reference_inputs ()
A function that finds all inputs required by the reference modules, excluding any unknowns. Here it is important to sort the results so the order is correct when using simultaneous_equations::update_known_quantities.
string_vector get_reference_outputs ()
A function that finds all outputs produced by the reference modules. Here it is important to sort the results so the order is correct when using simultaneous_equations::update_known_quantities. This is accomplished automatically because the find_unique_module_outputs returns a string_set (which is sorted).
void check_module_io_equivalence (std::string reference_module, std::string module_to_test)
Check the the test module to make sure it has the same inputs and outputs as the reference module. This function throws an error if there is a problem.
bool validate_modules (string_vector input_module_names)
Checks to make sure the input modules are valid. The modules are valid if and only if each module has the same inputs and outputs as the corresponding reference module. This function throws an error if there is a problem.
Variables
const string_vector reference_module_names
Function Documentation
check_module_io_equivalence()
void ed_leaf_photosynthesis::check_module_io_equivalence (std::string reference_module, std::string module_to_test)
Check the the test module to make sure it has the same inputs and outputs as the reference module. This function throws an error if there is a problem.
Definition at line 63 of file ed_leaf_photosynthesis.h.
 {
     // Make a lambda to simplify the checks. check_type should be "inputs" or "outputs".
     auto check_equiv =
         [&reference_module, &module_to_test](string_vector const& ref_sv, string_vector const& test_sv, std::string check_type) -> void {
         if (ref_sv.size() != test_sv.size() || !all_are_in_list(ref_sv, test_sv)) {
             throw std::logic_error(
                 std::string("The '") +
                 module_to_test +
                 std::string("' module does not have the same ") +
                 check_type +
                 std::string(" as the reference model ('") +
                 reference_module +
                 std::string("'"));
         }
     };
     // Get the module wrappers
     auto w_ref = module_wrapper_factory::create(reference_module);
     auto w_test = module_wrapper_factory::create(module_to_test);
     // Perform the tests
     check_equiv(w_ref->get_inputs(), w_test->get_inputs(), "inputs");
     check_equiv(w_ref->get_outputs(), w_test->get_outputs(), "outputs");
 }
References module_wrapper_factory::create().
Referenced by validate_modules().
get_reference_inputs()
string_vector ed_leaf_photosynthesis::get_reference_inputs ()
A function that finds all inputs required by the reference modules, excluding any unknowns. Here it is important to sort the results so the order is correct when using simultaneous_equations::update_known_quantities.
Definition at line 33 of file ed_leaf_photosynthesis.h.
 {
     string_set all_reference_inputs = find_strictly_required_inputs(std::vector<string_vector>{reference_module_names});
     string_vector unknown_quantities = get_unknown_quantities(std::vector<string_vector>{reference_module_names});
     string_vector result = string_vector_difference(
         string_set_to_string_vector(all_reference_inputs),
         unknown_quantities);
     std::sort(result.begin(), result.end());
     return result;
 }
References reference_module_names, and ed_leaf_photosynthesis_nr::unknown_quantities.
Referenced by ed_c4_leaf_photosynthesis::get_inputs(), and ed_leaf_photosynthesis_nr::make_se().
get_reference_outputs()
string_vector ed_leaf_photosynthesis::get_reference_outputs ()
A function that finds all outputs produced by the reference modules. Here it is important to sort the results so the order is correct when using simultaneous_equations::update_known_quantities. This is accomplished automatically because the find_unique_module_outputs returns a string_set (which is sorted).
Definition at line 54 of file ed_leaf_photosynthesis.h.
 {
     return string_set_to_string_vector(find_unique_module_outputs(std::vector<string_vector>{reference_module_names}));
 }
References reference_module_names.
Referenced by ed_c4_leaf_photosynthesis::get_outputs(), and ed_leaf_photosynthesis_nr::module_base::module_base().
validate_modules()
bool ed_leaf_photosynthesis::validate_modules (string_vector input_module_names)
Checks to make sure the input modules are valid. The modules are valid if and only if each module has the same inputs and outputs as the corresponding reference module. This function throws an error if there is a problem.
Definition at line 94 of file ed_leaf_photosynthesis.h.
 {
     if (input_module_names.size() != reference_module_names.size()) {
         throw std::logic_error("Thrown by ed_leaf_photosynthesis::validate_modules: wrong number of input modules.");
     }
     for (size_t i = 0; i < input_module_names.size(); ++i) {
         try {
             check_module_io_equivalence(reference_module_names[i], input_module_names[i]);
         } catch (std::exception const& e) {
             throw std::logic_error(std::string("Thrown by ed_leaf_photosynthesis::validate_modules: ") + e.what());
         }
     }
     return true;
 }
References check_module_io_equivalence(), and reference_module_names.
Variable Documentation
reference_module_names
const string_vector ed_leaf_photosynthesis::reference_module_names
Initial value:
= {
    "ed_rh_to_mole_fraction",
    "ed_nikolov_conductance_forced",
    "ed_nikolov_conductance_free",
    "ed_boundary_conductance_max",
    "ed_gas_concentrations",
    "ed_apply_stomatal_water_stress_via_conductance",
    "ed_ball_berry",
    "ed_collatz_c4_assimilation",
    "ed_long_wave_energy_loss",
    "ed_water_vapor_properties",
    "ed_penman_monteith_leaf_temperature"
}
Define a list of reference module names
Definition at line 14 of file ed_leaf_photosynthesis.h.
Referenced by get_reference_inputs(), get_reference_outputs(), and validate_modules().