BioCro: /github/workspace/source/src/numerical_jacobian.h File Reference
numerical_jacobian.h File Reference
#include <memory>
#include "system.h"
#include "simultaneous_equations.h"
#include "constants.h"
Functions
template<typename vector_type , typename time_type >
void evaluate_equations (std::shared_ptr< System > const &sys, vector_type const &x, time_type t, vector_type &y)
Define evaluation behavior for a set of equations defined by a System object.
template<typename in_vector_type , typename time_type , typename out_vector_type >
void evaluate_equations (std::unique_ptr< simultaneous_equations > const &se, in_vector_type const &x, time_type, out_vector_type &y)
Define evaluation behavior for a set of equations defined by a simultaneous_equations object.
template<typename equation_ptr_type , typename x_vector_type , typename time_type , typename f_vector_type , typename matrix_type >
void calculate_jacobian (equation_ptr_type const &equation_ptr, x_vector_type const &x, time_type t, f_vector_type const &f_current, matrix_type &jacobi)
Numerically compute the Jacobian matrix of a vector valued function.
template<typename equation_ptr_type , typename vector_type , typename time_type , typename matrix_type >
void calculate_jacobian (equation_ptr_type const &equation_ptr, vector_type const &x, time_type t, matrix_type &jacobi)
A wrapper for calculate_jacobian(equation_ptr, x, t, f_current, jacobi) that automatically evaluates f_current.
template<typename equation_ptr_type , typename x_vector_type , typename f_vector_type , typename matrix_type >
void calculate_jacobian_nt (equation_ptr_type const &equation_ptr, x_vector_type const &x, f_vector_type const &f_current, matrix_type &jacobi)
A wrapper for calculate_jacobian(equation_ptr, x, t, f_current, jacobi) for equations that have no time dependence.
template<typename equation_ptr_type , typename vector_type , typename time_type , typename matrix_type >
void calculate_jacobian (equation_ptr_type const &equation_ptr, vector_type const &x, matrix_type &jacobi)
A wrapper for calculate_jacobian(equation_ptr, x, t, f_current, jacobi) that automatically evaluates f_current for equations that have no time dependence.
template<typename equation_ptr_type , typename time_type , typename x_vector_type , typename f_vector_type >
void calculate_time_derivative (equation_ptr_type const &equation_ptr, time_type max_time, x_vector_type const &x, time_type t, f_vector_type const &f_current, f_vector_type &dfdt)
Numerically compute the explicit time derivatives of a vector valued function.
template<typename equation_ptr_type , typename time_type , typename x_vector_type , typename f_vector_type >
void calculate_time_derivative (equation_ptr_type const &equation_ptr, time_type max_time, x_vector_type const &x, time_type t, f_vector_type &dfdt)
A wrapper for calculate_time_derivative(equation_ptr, max_time, x, t, f_current, dfdt) that automatically calculates f_current.
template<typename equation_ptr_type , typename time_type , typename vector_type , typename matrix_type >
void calculate_jacobian_and_time_derivative (equation_ptr_type const &equation_ptr, time_type max_time, vector_type const &x, time_type t, matrix_type &jacobi, vector_type &dfdt)
Numerically compute the Jacobian matrix and time derivatives of a vector valued function.
Function Documentation
calculate_jacobian() [1/3]
template<typename equation_ptr_type , typename vector_type , typename time_type , typename matrix_type > void calculate_jacobian (equation_ptr_type const & equation_ptr, vector_type const & x, matrix_type & jacobi)
A wrapper for calculate_jacobian(equation_ptr, x, t, f_current, jacobi) that automatically evaluates f_current for equations that have no time dependence.
Definition at line 170 of file numerical_jacobian.h.
 {
     calculate_jacobian(equation_ptr, x, 0, jacobi);
 }
References calculate_jacobian().
calculate_jacobian() [2/3]
template<typename equation_ptr_type , typename vector_type , typename time_type , typename matrix_type > void calculate_jacobian (equation_ptr_type const & equation_ptr, vector_type const & x, time_type t, matrix_type & jacobi)
A wrapper for calculate_jacobian(equation_ptr, x, t, f_current, jacobi) that automatically evaluates f_current.
Definition at line 140 of file numerical_jacobian.h.
 {
     vector_type f_current(x.size());
     evaluate_equations(equation_ptr, x, t, f_current);
     calculate_jacobian(equation_ptr, x, t, f_current, jacobi);
 }
References calculate_jacobian(), and evaluate_equations().
calculate_jacobian() [3/3]
template<typename equation_ptr_type , typename x_vector_type , typename time_type , typename f_vector_type , typename matrix_type > void calculate_jacobian (equation_ptr_type const & equation_ptr, x_vector_type const & x, time_type t, f_vector_type const & f_current, matrix_type & jacobi)
Numerically compute the Jacobian matrix of a vector valued function.
Parameters
[in] equation_ptr a pointer to an object that can be used to represent a vector valued function f. There must be an associated evaluate_equations(*equation_ptr_type, x, t, y) function defined for equation_ptr_type. It is assumed that the output vector produced by the equations has the same length as the input vector.
[in] x an input vector to be passed to the vector valued function.
[in] t an input time to be passed to the vector valued function.
[in] f_current the output of the vector valued function evaluated at x, t
[out] jacobi the calculated Jacobian matrix (containing df_i/dx_j evaluated at x, t)
Discussion of step size from Nadim Khalil's thesis:
It is known that numerical differentiation is an unstable procedure prone to truncation and subtractive cancellation errors. Decreasing the step size will reduce the truncation error. Unfortunately a smaller step has the opposite effect on the cancellation error. Selecting the optimal step size for a certain problem is computationally expensive and the benefits achieved are not justifiable as the effect of small errors in the values of the elements of the Jacobian matrix is minor. For this reason, the sizing of the finite difference step is not attempted and a constant increment size is used in evaluating the gradient.
In BioCro, we fix a step size and only evaluate the forward perturbation to reduce calculation costs. In other words:
(1) We calculate f(x,t) using the input (x,t) (called f_current)
(2) We make a forward perturbation by adding h to one vector element and calculating the time derivatives (called f_perturbation)
(3) We calculate the rate of change for each vector element according to (f_perturbed[i] - f_current[i])/h
(4) We repeat steps (2) and (3) for each state variable
The alternative method would be:
(1) We make a backward perturbation by substracting h from one state variable and calculating the time derivatives (called f_backward)
(2) We make a forward perturbation by adding h to the same state variable and calculating the time derivatives (called f_forward)
(3) We calculate the rate of change for each state variable according to (f_forward[i] - f_backward[i])/(2*h)
(4) We repeat steps (1) through (3) for each state variable
In the simpler scheme, we make N + 1 derivative evaluations, where N is the number of state variables. In the other scheme, we make 2N derivative evaluations. The improvement in accuracy does not seem to outweigh the cost of additional calculations, since BioCro evaluations are expensive. Likewise, higher-order numerical derivative calculations are also not worthwhile.
Definition at line 97 of file numerical_jacobian.h.
 {
     size_t n = x.size();
     // Make a vector to store the perturbed f(x,t)
     f_vector_type f_perturbed(n);
     // Perturb each element x_i of the input vector to find df_j(x,t)/dx_i,
     // which is stored at jacobi(j,i)
     double h;
     x_vector_type x_perturbed = x;
     for (size_t i = 0; i < n; i++) {
         // Ensure that the step size h is close to eps_deriv but is exactly representable
         //  (see Numerical Recipes in C, 2nd ed., Section 5.7)
         h = calculation_constants::eps_deriv;
         double temp = x[i] + h;
         h = temp - x[i];
         // Calculate the new function value
         x_perturbed[i] = x[i] + h;                                      // Add h to the ith state variable
         evaluate_equations(equation_ptr, x_perturbed, t, f_perturbed);  // Calculate f_perturbed
         // Store the results in the Jacobian matrix
         for (size_t j = 0; j < n; j++) {
             jacobi(j, i) = (f_perturbed[j] - f_current[j]) / h;
         }
         // Reset the ith state variable
         x_perturbed[i] = x[i];
     }
 }
References calculation_constants::eps_deriv, and evaluate_equations().
Referenced by calculate_jacobian(), calculate_jacobian_and_time_derivative(), and calculate_jacobian_nt().
calculate_jacobian_and_time_derivative()
template<typename equation_ptr_type , typename time_type , typename vector_type , typename matrix_type > void calculate_jacobian_and_time_derivative (equation_ptr_type const & equation_ptr, time_type max_time, vector_type const & x, time_type t, matrix_type & jacobi, vector_type & dfdt)
Numerically compute the Jacobian matrix and time derivatives of a vector valued function.
Parameters
[in] equation_ptr a pointer to an object that can be used to represent a vector valued function f. There must be an associated evaluate_equations(*equation_ptr_type, x, t, y) function defined for equation_ptr_type. It is assumed that the output vector produced by the equations has the same length as the input vector.
[in] max_time the largest time value that can be passed to the vector valued function.
[in] x an input vector to be passed to the vector valued function.
[in] t an input time to be passed to the vector valued function.
[out] jacobi the calculated Jacobian matrix (containing df_i/dx_j evaluated at x, t)
[out] dfdt the calculated explicit time dependence (i.e., df_i/dt evaluated at x, t)
Definition at line 271 of file numerical_jacobian.h.
 {
     calculate_jacobian(equation_ptr, x, t, jacobi);
     calculate_time_derivative(equation_ptr, max_time, x, t, dfdt);
 }
References calculate_jacobian(), and calculate_time_derivative().
Referenced by SystemPointerWrapper::operator()().
calculate_jacobian_nt()
template<typename equation_ptr_type , typename x_vector_type , typename f_vector_type , typename matrix_type > void calculate_jacobian_nt (equation_ptr_type const & equation_ptr, x_vector_type const & x, f_vector_type const & f_current, matrix_type & jacobi)
A wrapper for calculate_jacobian(equation_ptr, x, t, f_current, jacobi) for equations that have no time dependence.
Definition at line 156 of file numerical_jacobian.h.
 {
     calculate_jacobian(equation_ptr, x, 0, f_current, jacobi);
 }
References calculate_jacobian().
calculate_time_derivative() [1/2]
template<typename equation_ptr_type , typename time_type , typename x_vector_type , typename f_vector_type > void calculate_time_derivative (equation_ptr_type const & equation_ptr, time_type max_time, x_vector_type const & x, time_type t, f_vector_type & dfdt)
A wrapper for calculate_time_derivative(equation_ptr, max_time, x, t, f_current, dfdt) that automatically calculates f_current.
Definition at line 240 of file numerical_jacobian.h.
 {
     f_vector_type f_current(x.size());
     evaluate_equations(equation_ptr, x, t, f_current);
     calculate_time_derivative(equation_ptr, max_time, x, t, f_current, dfdt);
 }
References calculate_time_derivative(), and evaluate_equations().
calculate_time_derivative() [2/2]
template<typename equation_ptr_type , typename time_type , typename x_vector_type , typename f_vector_type > void calculate_time_derivative (equation_ptr_type const & equation_ptr, time_type max_time, x_vector_type const & x, time_type t, f_vector_type const & f_current, f_vector_type & dfdt)
Numerically compute the explicit time derivatives of a vector valued function.
Parameters
[in] equation_ptr a pointer to an object that can be used to represent a vector valued function f. There must be an associated evaluate_equations(*equation_ptr_type, x, t, y) function defined for equation_ptr_type. It is assumed that the output vector produced by the equations has the same length as the input vector.
[in] max_time the largest time value that can be passed to the vector valued function.
[in] x an input vector to be passed to the vector valued function.
[in] t an input time to be passed to the vector valued function.
[in] f_current the output of the vector valued function evaluated at x, t
[out] dfdt the calculated time derivative, i.e., df_i/dt evaluated at (x, t)
For discussion of numerical derivative calculation, see description of jacobian::calculate_jacobian(equation_ptr, x, t, jacobi).
Definition at line 200 of file numerical_jacobian.h.
 {
     size_t n = x.size();
     // Make a vector to store the perturbed f(x,t)
     f_vector_type f_perturbed(n);
     // Perturb the time to find df(x,t)/dt
     // Use a forward step whenever possible
     // Ensure that the step size h is close to eps_deriv but is exactly representable
     //  (see Numerical Recipes in C, 2nd ed., Section 5.7)
     double h = calculation_constants::eps_deriv;
     if (t + h <= max_time) {
         double temp = t + h;
         h = temp - t;
         evaluate_equations(equation_ptr, x, t + h, f_perturbed);
         for (size_t j = 0; j < n; j++) {
             dfdt[j] = (f_perturbed[j] - f_current[j]) / h;
         }
     } else {
         double temp = t - h;
         h = temp + t;
         evaluate_equations(equation_ptr, x, t - h, f_perturbed);
         for (size_t j = 0; j < n; j++) {
             dfdt[j] = (f_current[j] - f_perturbed[j]) / h;
         }
     }
 }
References calculation_constants::eps_deriv, and evaluate_equations().
Referenced by calculate_jacobian_and_time_derivative(), and calculate_time_derivative().
evaluate_equations() [1/2]
template<typename vector_type , typename time_type > void evaluate_equations (std::shared_ptr< System > const & sys, vector_type const & x, time_type t, vector_type & y)
Define evaluation behavior for a set of equations defined by a System object.
Parameters
[in] sys a shared pointer to a System object.
[in] x a vector to be passed to the System as an input. Since we are evaluating a System, x contains values of the System's state variables.
[in] t a time to be passed to the System as an input.
[out] y the vector output. Since we are evaluating a System object, y contains the time derivative of each state variable.
Definition at line 23 of file numerical_jacobian.h.
 {
     sys->operator()(x, y, t);
 }
Referenced by calculate_jacobian(), and calculate_time_derivative().
evaluate_equations() [2/2]
template<typename in_vector_type , typename time_type , typename out_vector_type > void evaluate_equations (std::unique_ptr< simultaneous_equations > const & se, in_vector_type const & x, time_type , out_vector_type & y)
Define evaluation behavior for a set of equations defined by a simultaneous_equations object.
Parameters
[in] sys a shared pointer to a simultaneous_equations object
[in] x a vector to be passed to the simultaneous_equations as an input. Since we are evaluating simultaneous equations, x contains values of the unknown variables.
[in] t an unused parameter included here to produce the same function signature as when evaluating a System.
[out] y the vector output. Since we are evaluating simultaneous equations, y contains the change in the value of each unknown variable produced by running the modules.
Definition at line 43 of file numerical_jacobian.h.
 {
     se->operator()(x, y);
 }