BioCro: /github/workspace/source/src/R_get_all.cpp File Reference
R_get_all.cpp File Reference
#include <Rinternals.h>
#include <vector>
#include <string>
#include "R_helper_functions.h"
#include "module_library/module_wrapper_factory.h"
#include "system_solver_library/system_solver_factory.h"
#include "se_solver_library/se_solver_factory.h"
Functions
SEXP R_get_all_modules ()
SEXP R_get_all_quantities ()
SEXP R_get_all_system_solvers ()
SEXP R_get_all_se_solvers ()
Function Documentation
R_get_all_modules()
SEXP R_get_all_modules ()
Definition at line 11 of file R_get_all.cpp.
 {
     try {
         std::vector<std::string> result = module_wrapper_factory::get_modules();
         return r_string_vector_from_vector(result);
     } catch (std::exception const& e) {
         Rf_error((std::string("Caught exception in R_get_all_modules: ") + e.what()).c_str());
     } catch (...) {
         Rf_error("Caught unhandled exception in R_get_all_modules.");
     }
 }
References module_wrapper_factory::get_modules(), and r_string_vector_from_vector().
R_get_all_quantities()
SEXP R_get_all_quantities ()
Definition at line 23 of file R_get_all.cpp.
 {
     try {
         std::unordered_map<std::string, std::vector<std::string>> all_quantities = module_wrapper_factory::get_all_quantities();
         return list_from_map(all_quantities);
     } catch (std::exception const& e) {
         Rf_error((std::string("Caught exception in R_get_all_param: ") + e.what()).c_str());
     } catch (...) {
         Rf_error("Caught unhandled exception in R_get_all_param.");
     }
 }
References module_wrapper_factory::get_all_quantities(), and list_from_map().
R_get_all_se_solvers()
SEXP R_get_all_se_solvers ()
Definition at line 47 of file R_get_all.cpp.
 {
     try {
         std::vector<std::string> result = se_solver_factory::get_solvers();
         return r_string_vector_from_vector(result);
     } catch (std::exception const& e) {
         Rf_error((std::string("Caught exception in R_get_all_se_solvers: ") + e.what()).c_str());
     } catch (...) {
         Rf_error("Caught unhandled exception in R_get_all_se_solvers.");
     }
 }
References r_string_vector_from_vector().
R_get_all_system_solvers()
SEXP R_get_all_system_solvers ()
Definition at line 35 of file R_get_all.cpp.
 {
     try {
         std::vector<std::string> result = system_solver_factory::get_solvers();
         return r_string_vector_from_vector(result);
     } catch (std::exception const& e) {
         Rf_error((std::string("Caught exception in R_get_all_system_solvers: ") + e.what()).c_str());
     } catch (...) {
         Rf_error("Caught unhandled exception in R_get_all_system_solvers.");
     }
 }
References r_string_vector_from_vector().