BioCro: /github/workspace/source/src/R_helper_functions.h File Reference
R_helper_functions.h File Reference
#include <Rinternals.h>
#include <vector>
#include <string>
#include "state_map.h"
Functions
state_map map_from_list (SEXP const &list)
state_vector_map map_vector_from_list (SEXP const &list)
std::vector< std::string > make_vector (SEXP const &r_string_vector)
SEXP list_from_map (state_map const &m)
SEXP list_from_map (state_vector_map const &m)
SEXP list_from_map (std::unordered_map< std::string, std::vector< std::string >> const &m)
SEXP vector_from_map (state_map const &m)
SEXP r_string_vector_from_vector (std::vector< std::string > const &v)
SEXP r_logical_from_boolean (bool b)
void output_map (state_map const &m)
void output_list (SEXP const &list)
Function Documentation
list_from_map() [1/3]
SEXP list_from_map (state_map const & m)
Definition at line 83 of file R_helper_functions.cpp.
 {
     auto n = m.size();
     SEXP list =  PROTECT(Rf_allocVector(VECSXP, n));
     SEXP names = PROTECT(Rf_allocVector(STRSXP, n));
     size_t i = 0;
     for (auto it = m.begin(); it != m.end(); ++it, ++i) {
         SET_VECTOR_ELT(list, i, Rf_ScalarReal(it->second));
         SET_STRING_ELT(names, i, Rf_mkChar(it->first.c_str()));
     }
     Rf_setAttrib(list, R_NamesSymbol, names);
     UNPROTECT(2);
     return list;
 }
Referenced by R_get_all_quantities(), R_get_module_info(), R_get_standalone_ss_info(), R_Gro_deriv(), R_Gro_ode(), R_Gro_solver(), R_solve_simultaneous_equations(), R_test_module(), R_test_simultaneous_equations(), and R_test_standalone_ss().
list_from_map() [2/3]
SEXP list_from_map (state_vector_map const & m)
Definition at line 98 of file R_helper_functions.cpp.
 {
     auto n = m.size();
     SEXP list =  PROTECT(Rf_allocVector(VECSXP, n));
     SEXP names = PROTECT(Rf_allocVector(STRSXP, n));
     size_t i = 0;
     for (auto it = m.begin(); it != m.end(); ++it, ++i) {
         size_t j = 0;
         auto second = it->second;
         auto p = second.size();
         SEXP values = PROTECT(Rf_allocVector(REALSXP, p));
         double* vp = REAL(values);  // It's a litte faster if you get a pointer and reuse it.
         for (auto vit = second.begin(); vit != second.end(); ++vit, ++j) {
             vp[j] = second[j];
         }
         SET_VECTOR_ELT(list, i, values);
         SET_STRING_ELT(names, i, Rf_mkChar(it->first.c_str()));
         UNPROTECT(1);
     }
     Rf_setAttrib(list, R_NamesSymbol, names);
     UNPROTECT(2);
     return list;
 }
list_from_map() [3/3]
SEXP list_from_map (std::unordered_map< std::string, std::vector< std::string >> const & m)
Definition at line 122 of file R_helper_functions.cpp.
 {
         auto n = m.size();
     SEXP list =  PROTECT(Rf_allocVector(VECSXP, n));
     SEXP names = PROTECT(Rf_allocVector(STRSXP, n));
     size_t i = 0;
     for (auto it = m.begin(); it != m.end(); ++it, ++i) {
         size_t j = 0;
         auto second = it->second;
         auto p = second.size();
         SEXP values = PROTECT(Rf_allocVector(STRSXP, p));
         for (auto vit = second.begin(); vit != second.end(); ++vit, ++j) {
                         SET_STRING_ELT(values, j, Rf_mkChar((second[j]).c_str()));
         }
         SET_VECTOR_ELT(list, i, values);
         SET_STRING_ELT(names, i, Rf_mkChar(it->first.c_str()));
         UNPROTECT(1);
     }
     Rf_setAttrib(list, R_NamesSymbol, names);
     UNPROTECT(2);
     return list;
 }
make_vector()
std::vector<std::string> make_vector (SEXP const & r_string_vector)
Definition at line 63 of file R_helper_functions.cpp.
{
     vector<string> v;
     size_t n = Rf_length(r_string_vector);
     v.reserve(n);
     for (size_t i = 0; i < n; ++i) {
         v.emplace_back(CHAR(STRING_ELT(r_string_vector, i)));
     }
     return v;
 }
Referenced by R_get_module_info(), R_get_standalone_ss_info(), R_Gro_deriv(), R_Gro_ode(), R_Gro_solver(), R_solve_simultaneous_equations(), R_test_module(), R_test_simultaneous_equations(), R_test_standalone_ss(), R_validate_simultaneous_equations(), and R_validate_system_inputs().
map_from_list()
state_map map_from_list (SEXP const & list)
Definition at line 33 of file R_helper_functions.cpp.
 {
     SEXP names = Rf_getAttrib(list, R_NamesSymbol);
     size_t n = Rf_length(list);
     state_map m;
     m.reserve(n);
     for (size_t i = 0; i < n; ++i) {
         m.emplace(CHAR(STRING_ELT(names, i)), REAL(VECTOR_ELT(list, i))[0]);
     }
     return m;
 }
Referenced by R_Gro_deriv(), R_Gro_ode(), R_Gro_solver(), R_solve_simultaneous_equations(), R_test_module(), R_test_simultaneous_equations(), R_test_standalone_ss(), R_validate_simultaneous_equations(), and R_validate_system_inputs().
map_vector_from_list()
state_vector_map map_vector_from_list (SEXP const & list)
Definition at line 45 of file R_helper_functions.cpp.
 {
     SEXP names = Rf_getAttrib(list, R_NamesSymbol);
     size_t n = Rf_length(list);
     state_vector_map m;
     m.reserve(n);
     for (size_t i = 0; i < n; ++i) {
         size_t p = Rf_length(VECTOR_ELT(list, i));
         vector<double> temporary;
         temporary.reserve(p);
         for (size_t j = 0; j < p; ++j) {
             temporary.emplace_back(REAL(VECTOR_ELT(list, i))[j]);
         }
         m.insert(state_vector_map::value_type(CHAR(STRING_ELT(names, i)), temporary));
     }
     return m;
 }
Referenced by R_Gro_deriv(), R_Gro_solver(), and R_validate_system_inputs().
output_list()
void output_list (SEXP const & list)
Definition at line 184 of file R_helper_functions.cpp.
{
     size_t n = Rf_length(list);
     SEXP names = PROTECT(Rf_allocVector(STRSXP, n));
     names = Rf_getAttrib(list, R_NamesSymbol);
     Rprintf("The list contains the following items: ");
     for (size_t i = 0; i < n - 1; ++i) {
         Rprintf("%s, %0.04f; ", CHAR(STRING_ELT(names, i)), REAL(VECTOR_ELT(list, i))[0]);
     }
     Rprintf("%s, %0.04f.\n\n", CHAR(STRING_ELT(names, n - 1)), REAL(VECTOR_ELT(list, n - 1))[0]);
     UNPROTECT(1);
 }
output_map()
void output_map (state_map const & m)
Definition at line 169 of file R_helper_functions.cpp.
{
     if (!m.empty()) {
         size_t i = 0;
         auto it = m.begin();
         Rprintf("The map contains the following items: ");
         for(; std::next(it) != m.end(); ++it) {
             Rprintf("%s, %0.04f; ", it->first.c_str(), it->second);
             if (++i % 5 == 0) Rprintf("\n");
         }
         Rprintf("%s, %0.04f.\n\n", it->first.c_str(), it->second);
     } else {
         Rprintf("The map is empty.\n");
     }
 }
r_logical_from_boolean()
SEXP r_logical_from_boolean (bool b)
Definition at line 161 of file R_helper_functions.cpp.
 {
     SEXP logical_output = PROTECT(Rf_allocVector(LGLSXP, 1));
     LOGICAL(logical_output)[0] = b;
     UNPROTECT(1);
     return logical_output;
 }
Referenced by R_validate_simultaneous_equations(), and R_validate_system_inputs().
r_string_vector_from_vector()
SEXP r_string_vector_from_vector (std::vector< std::string > const & v)
vector_from_map()
SEXP vector_from_map (state_map const & m)
Definition at line 145 of file R_helper_functions.cpp.
 {
     auto n = m.size();
     SEXP vector = PROTECT(Rf_allocVector(REALSXP, n));
     SEXP names = PROTECT(Rf_allocVector(STRSXP, n));
     double* vp = REAL(vector);  // It's a little faster if you get a pointer and reuse it.
     size_t i = 0;
     for (auto it = m.begin(); it != m.end(); ++it, ++i) {
         vp[i] = it->second;
         SET_STRING_ELT(names, i, Rf_mkChar(it->first.c_str()));
     }
     Rf_setAttrib(vector, R_NamesSymbol, names);
     UNPROTECT(2);
     return vector;
 }