BioCro: /github/workspace/source/src/se_solver_helper_functions.h File Reference
se_solver_helper_functions.h File Reference
#include <vector>
#include <cmath>
Functions
template<typename vector_type >
std::vector< bool > is_outside_bounds (vector_type const &vec_to_test, vector_type const &lower_bounds, vector_type const &upper_bounds)
Checks whether the elements of vec_to_test lie outside the bounds.
template<typename vector_type >
std::vector< bool > has_not_converged_abs (vector_type const &old_guess, vector_type const &new_guess, double const &tolerance)
Checks whether the guesses have converged using an absolute threshold.
template<typename vector_type >
std::vector< bool > has_not_converged_rel (vector_type const &old_guess, vector_type const &new_guess, double const &tolerance)
Checks whether the guesses have converged using a relative threshold.
Function Documentation
has_not_converged_abs()
template<typename vector_type > std::vector<bool> has_not_converged_abs (vector_type const & old_guess, vector_type const & new_guess, double const & tolerance)
Checks whether the guesses have converged using an absolute threshold.
Parameters
[in] old_guess
[in] new_guess
[in] tolerance
Returns
a vector of bools where true indicates that the corresponding element of the input vectors has not met the convergence criteria.
Definition at line 48 of file se_solver_helper_functions.h.
 {
     std::vector<bool> result(new_guess.size());
     for (size_t i = 0; i < new_guess.size(); ++i) {
         result[i] = fabs(new_guess[i] - old_guess[i]) > tolerance;
     }
     return result;
 }
Referenced by se_solver::solve().
has_not_converged_rel()
template<typename vector_type > std::vector<bool> has_not_converged_rel (vector_type const & old_guess, vector_type const & new_guess, double const & tolerance)
Checks whether the guesses have converged using a relative threshold.
Parameters
[in] old_guess
[in] new_guess
[in] tolerance
Returns
a vector of bools where true indicates that the corresponding element of the input vectors has not met the convergence criteria.
Definition at line 75 of file se_solver_helper_functions.h.
 {
     std::vector<bool> result(new_guess.size());
     for (size_t i = 0; i < new_guess.size(); ++i) {
         result[i] = fabs((new_guess[i] - old_guess[i]) / old_guess[i]) > tolerance;
     }
     return result;
 }
Referenced by se_solver::solve().
is_outside_bounds()
template<typename vector_type > std::vector<bool> is_outside_bounds (vector_type const & vec_to_test, vector_type const & lower_bounds, vector_type const & upper_bounds)
Checks whether the elements of vec_to_test lie outside the bounds.
Parameters
[in] vec_to_test
[in] lower_bounds
[in] upper_bounds
Returns
a vector of bools where true indicates that the corresponding element of vec_to_test lies outside the range set by the corresponding elements of lower_bounds and upper_bounds.
Definition at line 21 of file se_solver_helper_functions.h.
 {
     std::vector<bool> result(vec_to_test.size());
     for (size_t i = 0; i < vec_to_test.size(); ++i) {
         result[i] = (vec_to_test[i] < lower_bounds[i] || vec_to_test[i] > upper_bounds[i]);
     }
     return result;
 }
Referenced by se_solver::solve().