BioCro: /github/workspace/source/src/simultaneous_equations.h File Reference
simultaneous_equations.h File Reference
#include "state_map.h"
#include "validate_system.h"
Data Structures
class simultaneous_equations
Defines a set of simultaneous equations.
Functions
bool validate_simultaneous_equations_inputs (std::string &message, state_map const &known_quantities, string_vector const &unknown_quantities, string_vector const &ss_module_names)
Checks over a group of quantities and modules to ensure they can be used to create a valid set of simultaneous equations.
std::string analyze_simultaneous_equations_inputs (string_vector const &ss_module_names)
Provides information about a set of simultaneous_equations inputs that is not strictly required to check validity.
string_vector get_unknown_quantities (std::vector< string_vector > module_name_vector)
Finds the unknown quantities defined by the set of modules.
Function Documentation
analyze_simultaneous_equations_inputs()
std::string analyze_simultaneous_equations_inputs (string_vector const & ss_module_names)
Provides information about a set of simultaneous_equations inputs that is not strictly required to check validity.
The following information is reported:
A list of all quantities required by the modules as inputs
A list of all quantities produced by the modules as outputs
A list of all unknown quantities specified by the modules
Definition at line 113 of file simultaneous_equations.cpp.
 {
     std::string message;
     // List the required inputs
     process_criterion<string_set>(
         message,
         [=]() -> string_set { return find_strictly_required_inputs(std::vector<string_vector>{ss_module_names}); },
         [](string_set string_list) -> std::string { return create_message(
                                                         std::string("No quantities were required by the set of modules"),
                                                         std::string("The following quantities were required by the set of modules:"),
                                                         std::string(""),
                                                         string_list); });
     // List the outputs
     process_criterion<string_set>(
         message,
         [=]() -> string_set { return find_unique_module_outputs(std::vector<string_vector>{ss_module_names}); },
         [](string_set string_list) -> std::string { return create_message(
                                                         std::string("No quantities were produced by any of the modules"),
                                                         std::string("The following quantities were each produced by at least one module:"),
                                                         std::string(""),
                                                         string_list); });
     // List the unknown quantities
     process_criterion<string_vector>(
         message,
         [=]() -> string_vector { return get_unknown_quantities(std::vector<string_vector>{ss_module_names}); },
         [](string_vector string_list) -> std::string { return create_message(
                                                            std::string("The modules did not specify any unknown quantities"),
                                                            std::string("The modules specified the following unknown quantities:"),
                                                            std::string(""),
                                                            string_list); });
     return message;
 }
References create_message(), find_strictly_required_inputs(), find_unique_module_outputs(), and get_unknown_quantities().
Referenced by R_validate_simultaneous_equations().
get_unknown_quantities()
string_vector get_unknown_quantities (std::vector< string_vector > module_name_vector)
Finds the unknown quantities defined by the set of modules.
Returns
A sorted list of quantity names
Definition at line 221 of file simultaneous_equations.cpp.
 {
     string_set required_inputs = find_strictly_required_inputs(module_name_vector);
     string_set module_outputs = find_unique_module_outputs(module_name_vector);
     string_set unknown_quantities;
     for (std::string const& input : required_inputs) {
         if (module_outputs.find(input) != module_outputs.end()) {
             unknown_quantities.insert(input);
         }
     }
     return string_set_to_string_vector(unknown_quantities);
 }
References find_strictly_required_inputs(), find_unique_module_outputs(), string_set_to_string_vector(), and ed_leaf_photosynthesis_nr::unknown_quantities.
Referenced by analyze_simultaneous_equations_inputs(), ed_leaf_photosynthesis::get_reference_inputs(), and validate_simultaneous_equations_inputs().
validate_simultaneous_equations_inputs()
bool validate_simultaneous_equations_inputs (std::string & message, state_map const & known_quantities, string_vector const & unknown_quantities, string_vector const & ss_module_names)
Checks over a group of quantities and modules to ensure they can be used to create a valid set of simultaneous equations.
Parameters
[in,out] message Validation feedback is added to this string.
Returns
true if the inputs are valid, false otherwise.
When discussing a simultaneous_equations object, it is helpful to define several terms as follows:
We consider a quantity to have been "specified" (or "defined") if it is a key in known_quantities or if it is an output variable of one of the steady-state modules listed in ss_module_names.
We consider a quantity to be strictly required as a module input if (i) a module requires it as an input and (ii) it has not been produced as the output of a previous module. Thus the set of strictly required inputs depends on the order of the modules.
If a quantity is (i) strictly required as an input and (ii) is produced as the output of a module, it is said to be an "unknown quantity" since its value will be determined by the set of simultaneous equations that this class represents. Thus the set of unknown quantities also depends on the order of the modules.
While constructing a simultaneous_equations object, the following criteria determine the validity of the inputs:
1. Each quantity is specified only once.
2. All module inputs are specified.
3. Each quantity name in unknown_quantities is an unknown quantity.
4. Each unknown quantity is included in unknown_quantities.
Definition at line 35 of file simultaneous_equations.cpp.
 {
     size_t num_problems = 0;
     string_vector quantity_names = get_defined_quantity_names(
         std::vector<state_map>{known_quantities},
         std::vector<string_vector>{ss_module_names});
     // Criterion 1
     num_problems += process_criterion<string_vector>(
         message,
         [=]() -> string_vector { return find_duplicate_quantity_definitions(quantity_names); },
         [](string_vector string_list) -> std::string {
             return create_message(
                 std::string("No quantities were defined multiple times"),
                 std::string("The following quantities were defined more than once:"),
                 std::string(""),
                 string_list);
         });
     // Criterion 2
     num_problems += process_criterion<string_vector>(
         message,
         [=]() -> string_vector {
             return find_undefined_module_inputs(
                 quantity_names,
                 std::vector<string_vector>{ss_module_names});
         },
         [](string_vector string_list) -> std::string {
             return create_message(
                 std::string("All module inputs were properly defined"),
                 std::string("The following module inputs were not defined:"),
                 std::string(""),
                 string_list);
         });
     string_vector unknown_quantities_from_modules = get_unknown_quantities(std::vector<string_vector>{ss_module_names});
     // Criterion 3
     num_problems += process_criterion<string_vector>(
         message,
         [=]() -> string_vector { return string_vector_difference(unknown_quantities, unknown_quantities_from_modules); },
         [](string_vector string_list) -> std::string {
             return create_message(
                 std::string("All quantities in 'unknown_quantities' are truly unknown quantities"),
                 std::string("The following quantities in 'unknown_quantities' are not actually unknown quantities:"),
                 std::string(""),
                 string_list);
         });
     // Criterion 4
     num_problems += process_criterion<string_vector>(
         message,
         [=]() -> string_vector { return string_vector_difference(unknown_quantities_from_modules, unknown_quantities); },
         [](string_vector string_list) -> std::string {
             return create_message(
                 std::string("All unknown quantities are included in 'unknown_quantities'"),
                 std::string("The following unknown quantities are not included in 'unknown_quantities':"),
                 std::string(""),
                 string_list);
         });
     return num_problems == 0;
 }
References create_message(), find_duplicate_quantity_definitions(), find_undefined_module_inputs(), get_defined_quantity_names(), get_unknown_quantities(), string_vector_difference(), and ed_leaf_photosynthesis_nr::unknown_quantities.
Referenced by R_validate_simultaneous_equations(), and simultaneous_equations::simultaneous_equations().