BioCro: /github/workspace/source/src/standalone_ss.cpp File Reference
standalone_ss.cpp File Reference
#include "standalone_ss.h"
#include "validate_system.h"
#include "system_helper_functions.h"
#include "state_map.h"
Functions
bool validate_standalone_ss_inputs (std::string &message, string_vector const &ss_module_names, std::unordered_map< std::string, const double * > const &input_ptrs, std::unordered_map< std::string, double * > const &output_ptrs)
Checks over a group of quantities and modules to ensure they can be used to create a valid system.
Function Documentation
validate_standalone_ss_inputs()
bool validate_standalone_ss_inputs (std::string & message, string_vector const & ss_module_names, std::unordered_map< std::string, const double * > const & input_ptrs, std::unordered_map< std::string, double * > const & output_ptrs)
Checks over a group of quantities and modules to ensure they can be used to create a valid system.
Parameters
[in,out] message Validation feedback is added to this string.
Returns
true if the inputs are valid, false otherwise.
While constructing a Standalone_SS object, the following criteria determine the validity of the inputs:
1. Each quantity is specified only once.
2. All module inputs are specified.
3. All of the quantities in the output pointers are module outputs.
4. All module inputs are calculated before they are accessed.
We consider a quantity to have been "specified" (or "defined") if it is a key in input_ptrs or if it is an output variable of one of the steady-state modules listed in ss_module_names.
We consider a quantity to have been "calculated" if its value is tied to an external object via a pointer in input_ptrs or if it has been produced as the output of a steady-state module.
Definition at line 28 of file standalone_ss.cpp.
 {
     size_t num_problems = 0;
     string_vector quantity_names = get_defined_quantity_names(
         std::vector<std::unordered_map<std::string, const double*>>{input_ptrs},
         std::vector<string_vector>{ss_module_names});
     // Criterion 1
     num_problems += process_criterion<string_vector>(
         message,
         [=]() -> string_vector { return find_duplicate_quantity_definitions(quantity_names); },
         [](string_vector string_list) -> std::string {
             return create_message(
                 std::string("No quantities were defined multiple times"),
                 std::string("The following quantities were defined more than once:"),
                 std::string(""),
                 string_list);
         });
     // Criterion 2
     num_problems += process_criterion<string_vector>(
         message,
         [=]() -> string_vector {
             return find_undefined_module_inputs(
                 quantity_names,
                 std::vector<string_vector>{ss_module_names});
         },
         [](string_vector string_list) -> std::string {
             return create_message(
                 std::string("All module inputs were properly defined"),
                 std::string("The following module inputs were not defined:"),
                 std::string(""),
                 string_list);
         });
     // Criterion 3
     num_problems += process_criterion<string_vector>(
         message,
         [=]() -> string_vector {
             return find_static_output_parameters(
                 std::vector<state_map>{state_map_from_names(keys(output_ptrs))},
                 std::vector<string_vector>{ss_module_names});
         },
         [](string_vector string_list) -> std::string {
             return create_message(
                 std::string("All quantities in the output pointers are produced as outputs by modules"),
                 std::string("The following quantities in the output pointers are not produced as outputs by modules:"),
                 std::string(""),
                 string_list);
         });
     // Criterion 4
     num_problems += process_criterion<string_vector>(
         message,
         [=]() -> string_vector {
             return find_misordered_modules(
                 std::vector<state_map>{state_map_from_names(keys(input_ptrs))},
                 std::vector<string_vector>{ss_module_names});
         },
         [](string_vector string_list) -> std::string {
             return create_message(
                 std::string("All steady-state modules are ordered in a consistent way"),
                 std::string("The following steady-state modules are out of order, i.e., they require input variables whose values have not yet been calculated:"),
                 std::string(""),
                 string_list);
         });
     return num_problems == 0;
 }
References create_message(), find_duplicate_quantity_definitions(), find_misordered_modules(), find_static_output_parameters(), find_undefined_module_inputs(), get_defined_quantity_names(), keys(), and state_map_from_names().
Referenced by R_get_standalone_ss_info(), and Standalone_SS::Standalone_SS().