BioCro: /github/workspace/source/src/state_map.h File Reference
state_map.h File Reference
#include <unordered_map>
#include <vector>
#include <string>
Data Structures
struct bad_state_vector_map_index
Typedefs
using state_vector_map = std::unordered_map< std::string, std::vector< double > >
using state_map = std::unordered_map< std::string, double >
Functions
template<typename map_with_string_key_type >
std::vector< std::string > keys (map_with_string_key_type const &map)
state_map at (const state_vector_map &vector_map, std::vector< double >::size_type n)
Given a sequence of states (presented as a state_vector_map) and an index n, return the n'th state in the sequence (counting from 0) in the form of a state_map.
template<typename name_list_type >
state_map state_map_from_names (name_list_type names)
state_map abs (state_map x)
Typedef Documentation
state_map
using state_map = std::unordered_map<std::string, double>
A state_map represents the state of a system. It maps names of system attributes to the values they have at some particular time.
Definition at line 30 of file state_map.h.
state_vector_map
using state_vector_map = std::unordered_map<std::string, std::vector<double> >
A state_vector_map represents a chronilogically-ordered sequence of states of a system over some period of time. The keys of the map are attributes of the system; each value is a vector representing the sequence of values of one of those attributes as it changes over time. To be a valid representation, each of the mapped-to vectors should be of the same length.
Definition at line 16 of file state_map.h.
Function Documentation
abs()
state_map abs (state_map x)
at()
state_map at (const state_vector_map & vector_map, std::vector< double >::size_type n)
Given a sequence of states (presented as a state_vector_map) and an index n, return the n'th state in the sequence (counting from 0) in the form of a state_map.
Parameters
vector_map A sequence of states represented as a state_vector_map.
n An index into the sequence of states given by vector_map.
Returns
The n'th state (counting from 0) of the sequence of states represented by vector_map.
Exceptions
bad_state_vector_map_index if n is not a valid index for some or all the vector values of the map.
Definition at line 24 of file state_map.cpp.
 {
     state_map result;
     try {
         for (auto pair : vector_map) {
             result.emplace(pair.first, pair.second.at(n));
         }
     }
     catch (std::out_of_range) {
         throw bad_state_vector_map_index(std::string{"Index "} +
                                          std::to_string(n) +
                                          " is out of range for vector_map.");
     }
     return result;
 }
Referenced by analyze_system_inputs(), System::get_output_param_names(), and validate_system_inputs().
keys()
template<typename map_with_string_key_type > std::vector<std::string> keys (map_with_string_key_type const & map)
Given a map, return a list of its keys.
Parameters
map A map having keys of type std::string.
Returns
A vector containing all of the keys of the map.
Note
The minimal requirement on the "map" argument is that it be a "range" or "sequence" of objects that have a "first" member function yielding a string, what we are considering to be the "key" of the object.
Definition at line 45 of file state_map.h.
 {
     std::vector<std::string> result;
     for (auto const& it : map) {
         result.push_back(it.first);
     }
     return result;
 }
Referenced by find_static_output_parameters(), find_unused_input_parameters(), System::get_state_parameter_names(), insert_key_names(), R_solve_simultaneous_equations(), R_test_simultaneous_equations(), simultaneous_equations::simultaneous_equations(), Standalone_SS::Standalone_SS(), validate_standalone_ss_inputs(), and validate_system_inputs().
state_map_from_names()
template<typename name_list_type > state_map state_map_from_names (name_list_type names)
Given a list of names, create a state_map object whose keys are precisely those names and whose values are all zero.
Definition at line 62 of file state_map.h.
 {
     state_map m;
     for (std::string const& n : names) {
         m[n] = 0;
     }
     return m;
 }
Referenced by R_get_standalone_ss_info(), Standalone_SS::Standalone_SS(), and validate_standalone_ss_inputs().