BioCro: /github/workspace/source/src/state_map.cpp File Reference
state_map.cpp File Reference
#include "state_map.h"
Functions
state_map at (const state_vector_map &vector_map, std::vector< double >::size_type n)
Given a sequence of states (presented as a state_vector_map) and an index n, return the n'th state in the sequence (counting from 0) in the form of a state_map.
Function Documentation
at()
state_map at (const state_vector_map & vector_map, std::vector< double >::size_type n)
Given a sequence of states (presented as a state_vector_map) and an index n, return the n'th state in the sequence (counting from 0) in the form of a state_map.
Parameters
vector_map A sequence of states represented as a state_vector_map.
n An index into the sequence of states given by vector_map.
Returns
The n'th state (counting from 0) of the sequence of states represented by vector_map.
Exceptions
bad_state_vector_map_index if n is not a valid index for some or all the vector values of the map.
Definition at line 24 of file state_map.cpp.
 {
     state_map result;
     try {
         for (auto pair : vector_map) {
             result.emplace(pair.first, pair.second.at(n));
         }
     }
     catch (std::out_of_range) {
         throw bad_state_vector_map_index(std::string{"Index "} +
                                          std::to_string(n) +
                                          " is out of range for vector_map.");
     }
     return result;
 }
Referenced by analyze_system_inputs(), System::get_output_param_names(), and validate_system_inputs().