BioCro: parameter_list Struct Reference
parameter_list Struct Reference
#include <parameters.h>
Public Types
typedef std::pair< std::string, parameter > parameter_entry
typedef std::unordered_map< std::string, parameter > parameter_entries
Public Member Functions
parameter_list (parameter_entries const &l=parameter_entries())
parameter_list (std::initializer_list< parameter_entries::value_type > const &l)
void add (parameter_entry const &entry)
void add (std::string const &s, char const delim, bool const trim)
void add (parameter_entries const &l)
Data Fields
parameter_entries _parameter_list
Detailed Description
Definition at line 15 of file parameters.h.
Member Typedef Documentation
parameter_entries
typedef std::unordered_map<std::string, parameter> parameter_list::parameter_entries
Definition at line 17 of file parameters.h.
parameter_entry
typedef std::pair<std::string, parameter> parameter_list::parameter_entry
Definition at line 16 of file parameters.h.
Constructor & Destructor Documentation
parameter_list() [1/2]
parameter_list::parameter_list (parameter_entries const & l = parameter_entries()) inline
Definition at line 19 of file parameters.h.
 : _parameter_list(l) {};
parameter_list() [2/2]
parameter_list::parameter_list (std::initializer_list< parameter_entries::value_type > const & l) inline
Definition at line 20 of file parameters.h.
 : _parameter_list(l) {};
Member Function Documentation
add() [1/3]
void parameter_list::add (parameter_entries const & l) inline
Definition at line 33 of file parameters.h.
 {
     for (auto const &entry : l) {
         this->add(entry);
     }
 }
References add().
add() [2/3]
void parameter_list::add (parameter_entry const & entry) inline
Definition at line 28 of file parameters.h.
 {
     this->_parameter_list[entry.first] = entry.second;
 }
References _parameter_list.
Referenced by add().
add() [3/3]
void parameter_list::add (std::string const & s, char const delim, bool const trim) inline
Definition at line 40 of file parameters.h.
 {
     std::vector<std::string> tokens;
     boost::split(tokens, s, [delim](char c){return c == delim;});
     if (tokens.size() != 3) throw std::invalid_argument("Each parameter must have exactly three values delimited by \"delim\".");
     if (trim_tokens) {
         for (auto &t : tokens) {
             boost::algorithm::trim(t);
         }
     }
     this->add(parameter_entry {tokens[0], {tokens[1], tokens[2]}});
 }
References add().
Field Documentation
_parameter_list
parameter_entries parameter_list::_parameter_list
Definition at line 25 of file parameters.h.
Referenced by add().
The documentation for this struct was generated from the following file:
/github/workspace/source/src/parameters.h