BioCro: /github/workspace/source/src/system_helper_functions.h File Reference
system_helper_functions.h File Reference
#include <vector>
#include <set>
#include <unordered_map>
#include <string>
#include <memory>
#include "validate_system.h"
#include "constants.h"
Functions
template<typename name_list_type , typename value_type_1 , typename value_type_2 >
std::vector< std::pair< value_type_1 *, const value_type_2 * > > get_pointer_pairs (name_list_type quantity_names, std::unordered_map< std::string, value_type_1 > &map_1, const std::unordered_map< std::string, value_type_2 > &map_2)
template<typename target_value_type , typename source_value_type >
std::vector< std::pair< target_value_type *, const source_value_type * > > get_input_pointer_pairs (std::unordered_map< std::string, target_value_type > &target_map, std::unordered_map< std::string, const source_value_type * > const &source_map)
Returns pairs of pointers that each point to the same named quantity in different places.
template<typename source_value_type , typename target_value_type >
std::vector< std::pair< const source_value_type *, target_value_type * > > get_output_pointer_pairs (std::unordered_map< std::string, source_value_type > const &source_map, std::unordered_map< std::string, target_value_type * > const &target_map)
Returns pairs of pointers that each point to the same named quantity in different places.
template<typename name_list_type , typename value_type >
std::vector< value_type * > get_pointers (name_list_type quantity_names, std::unordered_map< std::string, value_type > &map)
template<typename name_list_type , typename value_type >
std::vector< const value_type * > get_const_pointers (name_list_type quantity_names, std::unordered_map< std::string, value_type > const &map)
bool check_adaptive_compatible (const module_vector *ptr_to_module_vector)
Function Documentation
check_adaptive_compatible()
bool check_adaptive_compatible (const module_vector * ptr_to_module_vector)
Checks whether the collection of modules is compatible with adaptive step size solvers
Definition at line 7 of file system_helper_functions.cpp.
 {
     bool adaptive_compatible = true;
     const module_vector& module_vector_reference = *ptr_to_module_vector;
     for (size_t i = 0; i < module_vector_reference.size(); i++) {
         adaptive_compatible *= module_vector_reference[i]->is_adaptive_compatible();
     }
     return adaptive_compatible;
 }
Referenced by boost_system_solver< boost::numeric::ublas::vector< double > >::boost_system_solver(), Standalone_SS::is_adaptive_compatible(), System::is_adaptive_compatible(), and system_solver::system_solver().
get_const_pointers()
template<typename name_list_type , typename value_type > std::vector<const value_type*> get_const_pointers (name_list_type quantity_names, std::unordered_map< std::string, value_type > const & map)
Returns a vector of pointers that point to elements of map whose targets are specified by quantity_names. Here it is essential that the map is passed by reference; otherwise the pointers will be useless
Definition at line 125 of file system_helper_functions.h.
 {
     std::vector<const value_type*> pointers;
     for (std::string const& name : quantity_names) {
         pointers.push_back(&map.at(name));
     }
     return pointers;
 }
Referenced by simultaneous_equations::simultaneous_equations().
get_input_pointer_pairs()
template<typename target_value_type , typename source_value_type > std::vector<std::pair<target_value_type*, const source_value_type*> > get_input_pointer_pairs (std::unordered_map< std::string, target_value_type > & target_map, std::unordered_map< std::string, const source_value_type * > const & source_map)
Returns pairs of pointers that each point to the same named quantity in different places.
The resulting pairs are intended to be used for updating a central map of quantities (the target_map, which is probably the quantities member of a Standalone_SS object) using values from another source (the source_map, which probably points to variables outside the Standalone_SS object).
One pair will be created for each named quantity in the source_map input.
Here it is essential that the target_map is passed by reference; otherwise the pointer pairs will be useless.
Parameters
[in] target_map An unordered map with string keys and elements that are variables of type target_value_type (often double).
[in] source_map An unordered map with string keys and elements that point to variables of type ‘source_value_type’ (often double).
Returns
A vector of pairs of pointers. The first pointer in each pair points to a "target" variable in the target_map input, while the second pointer points to the same named quantity in another location, as specified by the source_map input.
Definition at line 54 of file system_helper_functions.h.
 {
     std::vector<std::pair<target_value_type*, const source_value_type*>> pointer_pairs;
     for (auto const& it : source_map) {
         std::pair<target_value_type*, const source_value_type*> temporary(&target_map.at(it.first), it.second);
         pointer_pairs.push_back(temporary);
     }
     return pointer_pairs;
 }
Referenced by Standalone_SS::Standalone_SS().
get_output_pointer_pairs()
template<typename source_value_type , typename target_value_type > std::vector<std::pair<const source_value_type*, target_value_type*> > get_output_pointer_pairs (std::unordered_map< std::string, source_value_type > const & source_map, std::unordered_map< std::string, target_value_type * > const & target_map)
Returns pairs of pointers that each point to the same named quantity in different places.
The resulting pairs are intended to be used for updating quantities (specified by the keys and pointers in the target_map) using values from the source_map (which is usually the quantities member of a Standalone_SS object).
One pair will be created for each named quantity in the target_map input.
Here it is essential that the source_map is passed by reference; otherwise the pointer pairs will be useless.
Parameters
[in] source_map An unordered map with string keys and elements that are variables of type ‘source_value_type’ (often double).
[in] target_map An unordered map with string keys and elements that point to variables of type target_value_type (often double).
Returns
A vector of pairs of pointers. The first pointer in each pair points to a "source" variable in the source_map input, while the second pointer points to the same named quantity in another location, as specified by the target_map input.
Definition at line 88 of file system_helper_functions.h.
 {
     std::vector<std::pair<const source_value_type*, target_value_type*>> pointer_pairs;
     for (auto const& it : target_map) {
         std::pair<const source_value_type*, target_value_type*> temporary(&source_map.at(it.first), it.second);
         pointer_pairs.push_back(temporary);
     }
     return pointer_pairs;
 }
Referenced by Standalone_SS::Standalone_SS().
get_pointer_pairs()
template<typename name_list_type , typename value_type_1 , typename value_type_2 > std::vector<std::pair<value_type_1*, const value_type_2*> > get_pointer_pairs (name_list_type quantity_names, std::unordered_map< std::string, value_type_1 > & map_1, const std::unordered_map< std::string, value_type_2 > & map_2)
Returns pairs of pointers that each point to the same named quantity in each of the two input maps. Here it is essential that map_1 and map_2 are passed by reference; otherwise the pointers will be useless.
Definition at line 18 of file system_helper_functions.h.
 {
     std::vector<std::pair<value_type_1*, const value_type_2*>> pointer_pairs;
     for (const std::string& name : quantity_names) {
         std::pair<value_type_1*, const value_type_2*>
             temporary{&(map_1.at(name)), &(map_2.at(name))};
         pointer_pairs.push_back(temporary);
     }
     return pointer_pairs;
 }
Referenced by simultaneous_equations::simultaneous_equations(), and Standalone_SS::Standalone_SS().
get_pointers()
template<typename name_list_type , typename value_type > std::vector<value_type*> get_pointers (name_list_type quantity_names, std::unordered_map< std::string, value_type > & map)
Returns a vector of pointers that point to elements of map whose targets are specified by quantity_names. Here it is essential that the map is passed by reference; otherwise the pointers will be useless
Definition at line 107 of file system_helper_functions.h.
 {
     std::vector<value_type*> pointers;
     for (std::string const& name : quantity_names) {
         pointers.push_back(&map.at(name));
     }
     return pointers;
 }
Referenced by simultaneous_equations::simultaneous_equations(), and Standalone_SS::Standalone_SS().