BioCro: /github/workspace/source/src/system_helper_functions.cpp File Reference
system_helper_functions.cpp File Reference
#include "system_helper_functions.h"
#include "validate_system.h"
Functions
bool check_adaptive_compatible (const module_vector *ptr_to_module_vector)
Function Documentation
check_adaptive_compatible()
bool check_adaptive_compatible (const module_vector * ptr_to_module_vector)
Checks whether the collection of modules is compatible with adaptive step size solvers
Definition at line 7 of file system_helper_functions.cpp.
 {
     bool adaptive_compatible = true;
     const module_vector& module_vector_reference = *ptr_to_module_vector;
     for (size_t i = 0; i < module_vector_reference.size(); i++) {
         adaptive_compatible *= module_vector_reference[i]->is_adaptive_compatible();
     }
     return adaptive_compatible;
 }
Referenced by Standalone_SS::is_adaptive_compatible(), System::is_adaptive_compatible(), and system_solver::system_solver().