BioCro: /github/workspace/source/src/validate_system.h File Reference
validate_system.h File Reference
#include <set>
#include <string>
#include <functional>
#include <memory>
#include <algorithm>
#include "state_map.h"
#include "module_library/module_wrapper_factory.h"
#include "modules.h"
Typedefs
using string_vector = std::vector< std::string >
using string_set = std::set< std::string >
using module_vector = std::vector< std::unique_ptr< Module > >
Functions
bool validate_system_inputs (std::string &message, state_map initial_state, state_map invariant_params, state_vector_map varying_params, string_vector ss_module_names, string_vector deriv_module_names)
Checks over a group of quantities and modules to ensure they can be used to create a valid system.
std::string analyze_system_inputs (state_map initial_state, state_map invariant_params, state_vector_map varying_params, string_vector ss_module_names, string_vector deriv_module_names)
Provides information about a set of system inputs that is not strictly required to check validity.
state_map define_quantity_map (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
string_vector find_duplicate_quantity_definitions (string_vector quantity_names)
string_vector find_undefined_module_inputs (string_vector quantity_names, std::vector< string_vector > module_name_vectors)
string_vector find_undefined_module_outputs (string_vector quantity_names, std::vector< string_vector > module_name_vectors)
string_vector find_misordered_modules (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
string_set find_unique_module_inputs (std::vector< string_vector > module_name_vectors)
string_set find_unique_module_outputs (std::vector< string_vector > module_name_vectors)
string_set find_strictly_required_inputs (std::vector< string_vector > module_name_vectors)
Returns a vector containing all inputs to the set of modules that are not outputs produced by previous modules. Note that the order of modules is important here.
string_vector find_unused_input_parameters (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
string_vector find_static_output_parameters (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
string_vector find_adaptive_incompatibility (std::vector< string_vector > module_name_vectors)
string_vector find_mischaracterized_modules (std::vector< string_vector > module_name_vectors, bool is_deriv)
module_vector get_module_vector (std::vector< string_vector > module_name_vectors, const state_map *input_parameters, state_map *output_parameters)
std::string add_indented_line (std::string message, std::string text_to_add, int num_spaces)
void insert_quantity_name_if_new (std::string quantity_name, string_vector &target_vector, string_vector &duplicate_vector)
void insert_module_param_if_undefined (std::string param_name, std::string module_name, string_vector defined_quantity_names, string_vector &undefined_module_names)
string_vector string_set_to_string_vector (string_set ss)
string_set string_vector_to_string_set (string_vector sv)
Creates a string_set from all the elements of a string_vector.
string_vector string_vector_difference (string_vector find_elements_of_this_vector, string_vector that_are_not_in_this_one)
template<typename string_list_type >
size_t process_criterion (std::string &message, std::function< string_list_type()> criterion_test, std::function< std::string(string_list_type)> form_message)
Template function for testing a system input criterion.
template<typename string_list_type >
std::string create_message (std::string message_if_empty, std::string message_at_beginning, std::string message_at_end, string_list_type string_list, std::string success_indicator="", std::string failure_indicator="")
template<typename string_list_type >
std::string create_marked_message (std::string message_if_empty, std::string message_at_beginning, std::string message_at_end, string_list_type string_list)
template<typename map_type >
void insert_key_names (string_vector &name_vector, const map_type map)
template<typename map_with_string_keys >
string_vector get_defined_quantity_names (std::vector< map_with_string_keys > state_maps, std::vector< string_vector > module_name_vectors)
template<typename list_type >
void insert_quantity_if_undefined (std::string quantity_name, list_type defined_quantity_names, string_vector &undefined_quantity_names)
template<typename list_type >
bool all_are_in_list (list_type find_these, list_type in_this)
Variables
const std::string success_mark { "[pass] " }
const std::string failure_mark { "[fail] " }
Typedef Documentation
module_vector
using module_vector = std::vector<std::unique_ptr<Module> >
Definition at line 16 of file validate_system.h.
string_set
using string_set = std::set<std::string>
Definition at line 15 of file validate_system.h.
string_vector
using string_vector = std::vector<std::string>
Definition at line 14 of file validate_system.h.
Function Documentation
add_indented_line()
std::string add_indented_line (std::string message, std::string text_to_add, int num_spaces)
Adds an indented line to a message
Parameters
[in] message The message being added to.
[in] text_to_add The text being appended to message.
[in] num_spaces The number of spaces of indentation for the appended text.
Returns
A string consisting of the input message followed num_spaces space characters followed by text_to_add.
Definition at line 613 of file validate_system.cpp.
 {
     for (int i = 0; i < num_spaces; i++) {
         message += std::string(" ");
     }
     message += text_to_add + std::string("\n");
     return message;
 }
Referenced by create_message().
all_are_in_list()
template<typename list_type > bool all_are_in_list (list_type find_these, list_type in_this)
Checks whether all of the elements of list find_these are in the list in_this
Definition at line 305 of file validate_system.h.
 {
     bool found;
     for (auto const& find_this : find_these) {
         found = false;
         for (auto const& this_it : in_this) {
             if (find_this == this_it) {
                 found = true;
                 break;
             }
         }
         if (!found) {
             break;
         }
     }
     return found;
 }
Referenced by ed_leaf_photosynthesis::check_module_io_equivalence(), and find_misordered_modules().
analyze_system_inputs()
std::string analyze_system_inputs (state_map initial_state, state_map invariant_params, state_vector_map varying_params, string_vector ss_module_names, string_vector deriv_module_names)
Provides information about a set of system inputs that is not strictly required to check validity.
The following information is reported:
A list of all quantities required by the modules as inputs
A list of unused quantities in the invariant parameter list
A list of unused quantities in the varying parameter list
A list of quantities in the initial state that lack derivatives
A list of quantities whose derivatives have terms calculated by multiple modules
Definition at line 144 of file validate_system.cpp.
 {
     std::string message;
     string_set all_module_inputs = find_unique_module_inputs(std::vector<string_vector>{ss_module_names, deriv_module_names});
     // List a suitable ordering for evaluation of the steady-state
     // modules if the given order isn't suitable.
     if (!has_cyclic_dependency(ss_module_names)) {
         process_criterion<string_vector>(
             message,
             [=]() -> string_vector {
                 string_vector result {};
                 if (!order_ok(ss_module_names)) {
                     return get_evaluation_order(ss_module_names);
                 }
                 else {
                     return {};
                 }
             },
             [](string_vector string_list) -> std::string {
                 return create_message(
                     std::string("The steady-state modules are in a suitable order for evaluation."),
                     std::string("The steady-state modules need to be re-ordered before evaluation.\n") +
                                 "(This will be done automatically by during System construction.)\n" +
                                 "Here is a suitable ordering:",
                     std::string(""),
                     string_list
                 );
             }
         );
     }
     // List the quantities used as inputs to the modules
     process_criterion<string_set>(
         message,
         [=]() -> string_set { return all_module_inputs; },
         [](string_set string_list) -> std::string { return create_message(
                                                         std::string("No quantities were required as inputs to any of the modules"),
                                                         std::string("The following quantities were each required by at least one module:"),
                                                         std::string(""),
                                                         string_list); });
     // List any unused quantities in the invariant parameters
     process_criterion<string_vector>(
         message,
         [=]() -> string_vector { return find_unused_input_parameters(std::vector<state_map>{invariant_params}, std::vector<string_vector>{ss_module_names, deriv_module_names}); },
         [](string_vector string_list) -> std::string { return create_message(
                                                            std::string("Each invariant parameter was used as an input to one or more modules"),
                                                            std::string("The following invariant parameters were not used as inputs to any module:"),
                                                            std::string("You may want to consider removing them for clarity"),
                                                            string_list); });
     // List any unused quantities in the varying parameters
     process_criterion<string_vector>(
         message,
         [=]() -> string_vector { return find_unused_input_parameters(std::vector<state_map>{at(varying_params, 0)}, std::vector<string_vector>{ss_module_names, deriv_module_names}); },
         [](string_vector string_list) -> std::string { return create_message(
                                                            std::string("Each varying parameter was used as an input to one or more modules"),
                                                            std::string("The following varying parameters were not used as inputs to any module:"),
                                                            std::string("You may want to consider removing them for clarity"),
                                                            string_list); });
     // List any quantities in the initial state that lack derivatives
     process_criterion<string_vector>(
         message,
         [=]() -> string_vector { return find_static_output_parameters(std::vector<state_map>{initial_state}, std::vector<string_vector>{deriv_module_names}); },
         [](string_vector string_list) -> std::string { return create_message(
                                                            std::string("All quantities in the initial state have associated derivatives"),
                                                            std::string("The following quantities in the initial state lack associated derivatives:"),
                                                            std::string("These quantities will not change with time, so you may want to consider moving them to the invariant parameters for clarity"),
                                                            string_list); });
     string_vector derivative_module_outputs = get_defined_quantity_names(
         std::vector<state_map>{},
         std::vector<string_vector>{deriv_module_names});
     // List any quantities whose derivative is determined by more than one module
     process_criterion<string_vector>(
         message,
         [=]() -> string_vector { return find_duplicate_quantity_definitions(derivative_module_outputs); },
         [](string_vector string_list) -> std::string { return create_message(
                                                            std::string("No derivative is determined by more than one module"),
                                                            std::string("Derivatives for the following quantities are each determined by more than one module:"),
                                                            std::string(""),
                                                            string_list); });
     // List any modules that are not compatible with adaptive step size methods
     process_criterion<string_vector>(
         message,
         [=]() -> string_vector { return find_adaptive_incompatibility(std::vector<string_vector>{ss_module_names, deriv_module_names}); },
         [](string_vector string_list) -> std::string { return create_message(
                                                            std::string("All modules are compatible with adaptive step size solvers"),
                                                            std::string("The following modules are not compatible with adaptive step size solvers:"),
                                                            std::string(""),
                                                            string_list); });
     // List any mischaracterized steady-state modules
     process_criterion<string_vector>(
         message,
         [=]() -> string_vector { return find_mischaracterized_modules(std::vector<string_vector>{ss_module_names}, false); },
         [](string_vector string_list) -> std::string { return create_message(
                                                            std::string("All modules in the steady-state module list are steady-state modules"),
                                                            std::string("The following modules were in the list of steady-state modules but are actually derivative modules:"),
                                                            std::string(""),
                                                            string_list); });
     // List any mischaracterized derivative modules
     process_criterion<string_vector>(
         message,
         [=]() -> string_vector { return find_mischaracterized_modules(std::vector<string_vector>{deriv_module_names}, true); },
         [](string_vector string_list) -> std::string { return create_message(
                                                            std::string("All modules in the derivative module list are derivative modules"),
                                                            std::string("The following modules were in the list of derivative modules but are actually steady-state modules:"),
                                                            std::string(""),
                                                            string_list); });
     return message;
 }
References at(), create_message(), find_adaptive_incompatibility(), find_duplicate_quantity_definitions(), find_mischaracterized_modules(), find_static_output_parameters(), find_unique_module_inputs(), find_unused_input_parameters(), and get_defined_quantity_names().
Referenced by R_validate_system_inputs().
create_marked_message()
template<typename string_list_type > std::string create_marked_message (std::string message_if_empty, std::string message_at_beginning, std::string message_at_end, string_list_type string_list)
Forms a user feedback message from a list of quantities, modules, etc. This function should be used in preference to create_message for the case where a non-empty string_list corresponds to some failure condition and an empty string_list corresponds to success, and we want to prepend success/failure indicators to the message.
Parameters
[in] message_if_empty This is the string that will be returned (surrounded by new-line characters and an initial "success" indicator) if string_list is empty.
[in] message_at_beginning This string is prepended (after being surrounded by new-line characters and an initial "failure" indicator) to the body of the message if string_list is not empty.
[in] message_at_end This string is appended to the body of the message (along with a new-line character) if string_list is not empty.
[in] string_list A list of strings that will form the body of the message.
Definition at line 215 of file validate_system.h.
 {
     return create_message(message_if_empty,
                           message_at_beginning,
                           message_at_end,
                           string_list,
                           success_mark,
                           failure_mark);
 }
References create_message(), failure_mark, and success_mark.
Referenced by validate_system_inputs().
create_message()
template<typename string_list_type > std::string create_message (std::string message_if_empty, std::string message_at_beginning, std::string message_at_end, string_list_type string_list, std::string success_indicator = "", std::string failure_indicator = "")
Forms a user feedback message from a list of quantities, modules, etc.
Parameters
[in] message_if_empty This is the string that will be returned (surrounded by new-line characters) if string_list is empty.
[in] message_at_beginning This string is prepended (after being surrounded by new-line characters) to the body of the message if string_list is not empty.
[in] message_at_end This string is appended to the body of the message (along with a new-line character) if string_list is not empty.
[in] string_list A list of strings that will form the body of the message.
Definition at line 163 of file validate_system.h.
 {
     std::string message;
     if (string_list.size() == 0) {
         message = std::string{"\n"} + success_indicator + message_if_empty + "\n";
     } else {
         message = std::string{"\n"} + failure_indicator + message_at_beginning + "\n";
         for (std::string text_item : string_list) {
             message = add_indented_line(message, text_item, 1);
         }
         if (message_at_end.size() > 0) {
             message += message_at_end + "\n";
         }
     }
     return message;
 }
References add_indented_line().
Referenced by analyze_simultaneous_equations_inputs(), analyze_system_inputs(), create_marked_message(), R_get_standalone_ss_info(), validate_simultaneous_equations_inputs(), and validate_standalone_ss_inputs().
define_quantity_map()
state_map define_quantity_map (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
Assembles a "master" state_map from a group of state_maps and a list of modules.
The resulting state_map will essentially be the union of all the maps in parameter state_maps and an additional map formed by taking as keys all of the output variables from modules in module_name_vectors and setting the corresponding values to zero. The set of keys in the maps in state_maps should not overlap with one another and should be distinct from the module output variable names.
Parameters
state_maps A list (presented as a std::vector) of state_maps.
module_name_vectors A list of lists (present as a std::vector of strint_vectors) of module names.
Returns
a state_map which is the union of all maps in state_maps together a map whose keys are all the output parameters of modules in module_name_vectors and whose values are all zero.
Definition at line 292 of file validate_system.cpp.
 {
     state_map quantities;
     // Process the state maps
     for (state_map const& m : state_maps) {
         quantities.insert(m.begin(), m.end());
     }
     // Get additional quantities from the modules
     for (string_vector const& names : module_name_vectors) {
         for (std::string const& module_name : names) {
             auto w = module_wrapper_factory::create(module_name);
             string_vector module_outputs = w->get_outputs();
             for (auto const& o : module_outputs) {
                 quantities[o] = 0;
             }
         }
     }
     return quantities;
 }
References module_wrapper_factory::create().
Referenced by simultaneous_equations::simultaneous_equations(), and Standalone_SS::Standalone_SS().
find_adaptive_incompatibility()
string_vector find_adaptive_incompatibility (std::vector< string_vector > module_name_vectors)
Returns modules that are not compatible with adaptive step size algorithms
Definition at line 525 of file validate_system.cpp.
 {
     // Get all the module inputs and outputs
     string_set all_module_inputs = find_unique_module_inputs(module_name_vectors);
     string_set all_module_outputs = find_unique_module_outputs(module_name_vectors);
     // Make an appropriate state_map that contains them all
     state_map quantities;
     for (string_set const& names : std::vector<string_set>{all_module_inputs, all_module_outputs}) {
         for (std::string const& n : names) {
             quantities[n] = 0;
         }
     }
     // Instantiate each module and check its characterization
     string_vector incompatible_modules;
     module_vector modules = get_module_vector(module_name_vectors, &quantities, &quantities);
     for (std::unique_ptr<Module>& m : modules) {
         if (!m->is_adaptive_compatible()) {
             incompatible_modules.push_back(m->get_name());
         }
     }
     return incompatible_modules;
 }
References find_unique_module_inputs(), find_unique_module_outputs(), and get_module_vector().
Referenced by analyze_system_inputs().
find_duplicate_quantity_definitions()
string_vector find_duplicate_quantity_definitions (string_vector quantity_names)
Finds quantities that are defined multiple times in a vector of strings
Parameters
quantity_names A list (presented as a vector of strings) of names of quantities. Generally these will be names of state variables, environment variables ("varying parameters"), system constants ("invariant parameters"), or derived quantites (outputs of steady-state modules).
Returns
A alphabetized list (presented as a vector of strings) of all quantities appearing more than once in the input list.
Definition at line 330 of file validate_system.cpp.
 {
     string_vector defined_quantities;
     string_vector duplicated_quantities;
     for (std::string name : quantity_names) {
         insert_quantity_name_if_new(name, defined_quantities, duplicated_quantities);
     }
     std::sort(duplicated_quantities.begin(), duplicated_quantities.end());
     return duplicated_quantities;
 }
References insert_quantity_name_if_new().
Referenced by analyze_system_inputs(), validate_simultaneous_equations_inputs(), validate_standalone_ss_inputs(), and validate_system_inputs().
find_mischaracterized_modules()
string_vector find_mischaracterized_modules (std::vector< string_vector > module_name_vectors, bool is_deriv)
Returns mischaracterized modules, i.e., steady-state modules in the derivative module list or vice-versa
Definition at line 554 of file validate_system.cpp.
 {
     // Get all the module inputs and outputs
     string_set all_module_inputs = find_unique_module_inputs(module_name_vectors);
     string_set all_module_outputs = find_unique_module_outputs(module_name_vectors);
     // Make an appropriate state_map that contains them all
     state_map quantities;
     for (string_set const& names : std::vector<string_set>{all_module_inputs, all_module_outputs}) {
         for (std::string const& n : names) {
             quantities[n] = 0;
         }
     }
     // Instantiate each module and check its characterization
     string_vector mischaracterized_modules;
     module_vector modules = get_module_vector(module_name_vectors, &quantities, &quantities);
     for (std::unique_ptr<Module>& m : modules) {
         if (m->is_deriv() != is_deriv) {
             mischaracterized_modules.push_back(m->get_name());
         }
     }
     return mischaracterized_modules;
 }
References find_unique_module_inputs(), find_unique_module_outputs(), and get_module_vector().
Referenced by analyze_system_inputs().
find_misordered_modules()
string_vector find_misordered_modules (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
Finds modules that access variables before their values have been calculated
Definition at line 393 of file validate_system.cpp.
 {
     // Get quantity names from the input lists
     string_vector defined_quantity_names = get_defined_quantity_names(state_maps, std::vector<string_vector>{});
     // Check the module order
     string_vector misordered_modules;
     for (string_vector const& names : module_name_vectors) {
         for (std::string const& module_name : names) {
             auto w = module_wrapper_factory::create(module_name);
             string_vector input_names = w->get_inputs();
             if (!all_are_in_list(input_names, defined_quantity_names)) {
                 misordered_modules.push_back(module_name);
             }
             string_vector output_names = w->get_outputs();
             defined_quantity_names.insert(defined_quantity_names.begin(), output_names.begin(), output_names.end());
         }
     }
     return misordered_modules;
 }
References all_are_in_list(), module_wrapper_factory::create(), and get_defined_quantity_names().
Referenced by validate_standalone_ss_inputs().
find_static_output_parameters()
string_vector find_static_output_parameters (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
Returns parameters in the state maps that are not provided as outputs from the modules
Definition at line 502 of file validate_system.cpp.
 {
     string_vector unused_params;
     string_set all_module_outputs = find_unique_module_outputs(module_name_vectors);
     for (state_map const& m : state_maps) {
         string_vector parameters = keys(m);
         for (std::string const& name : parameters) {
             insert_quantity_if_undefined(name, all_module_outputs, unused_params);
         }
     }
     std::sort(unused_params.begin(), unused_params.end());
     return unused_params;
 }
References find_unique_module_outputs(), insert_quantity_if_undefined(), keys(), and parameters.
Referenced by analyze_system_inputs(), and validate_standalone_ss_inputs().
find_strictly_required_inputs()
string_set find_strictly_required_inputs (std::vector< string_vector > module_name_vectors)
Returns a vector containing all inputs to the set of modules that are not outputs produced by previous modules. Note that the order of modules is important here.
Definition at line 457 of file validate_system.cpp.
 {
     string_vector required_module_inputs;
     string_set outputs_from_previous_modules;
     for (string_vector const& names : module_name_vectors) {
         for (std::string const& module_name : names) {
             auto w = module_wrapper_factory::create(module_name);
             for (std::string const& input_name : w->get_inputs()) {
                 insert_quantity_if_undefined(input_name, outputs_from_previous_modules, required_module_inputs);
             }
             string_vector output_names = w->get_outputs();
             outputs_from_previous_modules.insert(output_names.begin(), output_names.end());
         }
     }
     return string_vector_to_string_set(required_module_inputs);
 }
References module_wrapper_factory::create(), insert_quantity_if_undefined(), and string_vector_to_string_set().
Referenced by analyze_simultaneous_equations_inputs(), Standalone_SS::get_inputs(), ed_leaf_photosynthesis::get_reference_inputs(), get_unknown_quantities(), and R_get_standalone_ss_info().
find_undefined_module_inputs()
string_vector find_undefined_module_inputs (string_vector quantity_names, std::vector< string_vector > module_name_vectors)
Finds quantities that are required by modules but are not defined by quantity_names. The output includes the module associated with each undefined input.
Definition at line 348 of file validate_system.cpp.
 {
     string_vector undefined_module_inputs;
     for (string_vector const& names : module_name_vectors) {
         for (std::string const& module_name : names) {
             auto w = module_wrapper_factory::create(module_name);
             string_vector input_names = w->get_inputs();
             for (std::string input : input_names) {
                 insert_module_param_if_undefined(input, module_name, quantity_names, undefined_module_inputs);
             }
         }
     }
     return undefined_module_inputs;
 }
References module_wrapper_factory::create(), and insert_module_param_if_undefined().
Referenced by validate_simultaneous_equations_inputs(), validate_standalone_ss_inputs(), and validate_system_inputs().
find_undefined_module_outputs()
string_vector find_undefined_module_outputs (string_vector quantity_names, std::vector< string_vector > module_name_vectors)
Finds quantities that are output by modules but are not defined by quantity_names. The output includes the module associated with each undefined output.
Definition at line 371 of file validate_system.cpp.
 {
     string_vector undefined_module_outputs;
     for (string_vector const& names : module_name_vectors) {
         for (std::string const& module_name : names) {
             auto w = module_wrapper_factory::create(module_name);
             string_vector output_names = w->get_outputs();
             for (std::string output : output_names) {
                 insert_module_param_if_undefined(output, module_name, quantity_names, undefined_module_outputs);
             }
         }
     }
     return undefined_module_outputs;
 }
References module_wrapper_factory::create(), and insert_module_param_if_undefined().
Referenced by validate_system_inputs().
find_unique_module_inputs()
string_set find_unique_module_inputs (std::vector< string_vector > module_name_vectors)
Returns a set containing all unique inputs to the modules
Definition at line 420 of file validate_system.cpp.
 {
     string_set module_inputs;
     for (string_vector const& names : module_name_vectors) {
         for (std::string const& module_name : names) {
             auto w = module_wrapper_factory::create(module_name);
             string_vector input_names = w->get_inputs();
             module_inputs.insert(input_names.begin(), input_names.end());
         }
     }
     return module_inputs;
 }
References module_wrapper_factory::create().
Referenced by analyze_system_inputs(), find_adaptive_incompatibility(), find_mischaracterized_modules(), and find_unused_input_parameters().
find_unique_module_outputs()
string_set find_unique_module_outputs (std::vector< string_vector > module_name_vectors)
Returns a set containing all unique outputs produced by the modules
Definition at line 438 of file validate_system.cpp.
 {
     string_set module_outputs;
     for (string_vector const& names : module_name_vectors) {
         for (std::string const& module_name : names) {
             auto w = module_wrapper_factory::create(module_name);
             string_vector output_names = w->get_outputs();
             module_outputs.insert(output_names.begin(), output_names.end());
         }
     }
     return module_outputs;
 }
References module_wrapper_factory::create().
Referenced by analyze_simultaneous_equations_inputs(), find_adaptive_incompatibility(), find_mischaracterized_modules(), find_static_output_parameters(), Standalone_SS::get_outputs(), ed_leaf_photosynthesis::get_reference_outputs(), get_unknown_quantities(), R_get_standalone_ss_info(), simultaneous_equations::simultaneous_equations(), and Standalone_SS::Standalone_SS().
find_unused_input_parameters()
string_vector find_unused_input_parameters (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
Returns parameters in the state maps that are not used as inputs to the modules
Definition at line 479 of file validate_system.cpp.
 {
     string_vector unused_params;
     string_set all_module_inputs = find_unique_module_inputs(module_name_vectors);
     for (state_map const& m : state_maps) {
         string_vector parameters = keys(m);
         for (std::string const& name : parameters) {
             insert_quantity_if_undefined(name, all_module_inputs, unused_params);
         }
     }
     std::sort(unused_params.begin(), unused_params.end());
     return unused_params;
 }
References find_unique_module_inputs(), insert_quantity_if_undefined(), keys(), and parameters.
Referenced by analyze_system_inputs().
get_defined_quantity_names()
template<typename map_with_string_keys > string_vector get_defined_quantity_names (std::vector< map_with_string_keys > state_maps, std::vector< string_vector > module_name_vectors)
Assembles the names of all quantities defined by a group of state_maps and module outputs, including any duplicates.
Parameters
[in] state_maps A collection of sets of named quantities presented as a vector of map_with_string_keys objects. Generally, this will either be empty or will consist of the initial state of the system, the set of invariant parameters, and the initial values of the varying parameters.
[in] module_name_vectors A collection of sets of module names presented as a vector of vectors. Usually, this collection will either be empty or will contain only a single item—a set of steady-state module names or a set of derivative module names.
Returns
A vector consisting of the names of all quantities defined in either of the function arguments. If a quantity is defined more than once, it will appear in the output vector more than once. A quantity is considered to be "defined" by the state_maps argument value if it is a key in one of the given maps. It is considered "defined" by the module_name_vectors argument value if it is a name of an output variable of some module named in any set in the collection.
Definition at line 263 of file validate_system.h.
 {
     std::vector<std::string> defined_quantity_names;
     // Get quantity names from the state maps
     for (map_with_string_keys const& m : state_maps) {
         insert_key_names(defined_quantity_names, m);
     }
     // Get quantity names from the modules
     for (string_vector const& names : module_name_vectors) {
         for (std::string const& module_name : names) {
             auto w = module_wrapper_factory::create(module_name);
             string_vector output_names = w->get_outputs();
             defined_quantity_names.insert(defined_quantity_names.begin(), output_names.begin(), output_names.end());
         }
     }
     return defined_quantity_names;
 }
References module_wrapper_factory::create(), and insert_key_names().
Referenced by analyze_system_inputs(), find_misordered_modules(), System::get_output_param_names(), validate_simultaneous_equations_inputs(), validate_standalone_ss_inputs(), and validate_system_inputs().
get_module_vector()
module_vector get_module_vector (std::vector< string_vector > module_name_vectors, const state_map * input_parameters, state_map * output_parameters)
Returns a vector of unique_ptrs to module objects
Definition at line 583 of file validate_system.cpp.
 {
     module_vector modules;
     for (string_vector const& module_names : module_name_vectors) {
         for (std::string name : module_names) {
             auto w = module_wrapper_factory::create(name);
             modules.push_back(w->createModule(input_parameters, output_parameters));
         }
     }
     return modules;
 }
References module_wrapper_factory::create().
Referenced by find_adaptive_incompatibility(), find_mischaracterized_modules(), simultaneous_equations::simultaneous_equations(), and Standalone_SS::Standalone_SS().
insert_key_names()
template<typename map_type > void insert_key_names (string_vector & name_vector, const map_type map)
Inserts all the keys from map into name_vector
Definition at line 232 of file validate_system.h.
 {
     string_vector map_key_names = keys(map);
     name_vector.insert(name_vector.begin(), map_key_names.begin(), map_key_names.end());
 }
References keys().
Referenced by get_defined_quantity_names().
insert_module_param_if_undefined()
void insert_module_param_if_undefined (std::string param_name, std::string module_name, string_vector defined_quantity_names, string_vector & undefined_module_names)
If param_name is not included in defined_quantity_names, a new entry is inserted into undefined_module_names that includes param_name and its associated module_name
Definition at line 653 of file validate_system.cpp.
 {
     if (std::find(defined_quantity_names.begin(), defined_quantity_names.end(), param_name) == defined_quantity_names.end()) {
         undefined_module_names.push_back(param_name + std::string(" from the '") + module_name + std::string("' module"));
     }
 }
Referenced by find_undefined_module_inputs(), and find_undefined_module_outputs().
insert_quantity_if_undefined()
template<typename list_type > void insert_quantity_if_undefined (std::string quantity_name, list_type defined_quantity_names, string_vector & undefined_quantity_names)
If quantity_name is not included in defined_quantity_names, it is inserted into undefined_quantity_names
Definition at line 291 of file validate_system.h.
 {
     if (std::find(defined_quantity_names.begin(), defined_quantity_names.end(), quantity_name) == defined_quantity_names.end()) {
         undefined_quantity_names.push_back(quantity_name);
     }
 }
Referenced by find_static_output_parameters(), find_strictly_required_inputs(), find_unused_input_parameters(), and string_vector_difference().
insert_quantity_name_if_new()
void insert_quantity_name_if_new (std::string quantity_name, string_vector & target_vector, string_vector & duplicates)
Inserts quantity_name into target_vector if it is not already there. In the case of a duplicate, quantity_name is inserted into duplicates.
Parameters
[in] quantity_name A string (the name of a quantity).
[in/out] target_vector A vector of strings. If quantity_name wasn't in the list to begin with, it will be appended.
[in/out] duplicates A vector of strings. If quantity_name was already in target_vector, it will be appended to duplicates.
Definition at line 636 of file validate_system.cpp.
 {
     if (std::find(target_vector.begin(), target_vector.end(), quantity_name) == target_vector.end()) {
         target_vector.push_back(quantity_name);
     } else {
         duplicates.push_back(quantity_name);
     }
 }
Referenced by find_duplicate_quantity_definitions().
process_criterion()
template<typename string_list_type > size_t process_criterion (std::string & message, std::function< string_list_type()> criterion_test, std::function< std::string(string_list_type)> form_message)
Template function for testing a system input criterion.
This function first calls criterion_test, which should return some kind of container of strings, e.g. std::vector<std::string> or std::set<std::string>. A non-empty result generally corresponds to failure to meet the criterion.
The output of criterion_test is then passed to form_message, which should create a user feedback message based on the result of the criterion test.
The output of form_message is added to the message input (passed by reference).
Finally, the number of elements in the output of criterion_test is returned. Again, a non-zero value generally corresponds to a failure to meet the criterion specified by criterion_test.
Parameters
[in,out] message A string, to which this function will append the result of the criterion test.
[in] criterion_test A function object having no input parameters and returning a string_list_type container.
[in] form_message A function object having on parameter of type string_list_type and returning a string. This will generally be a function that cobbles together a readable message from the collection of strings given as input.
Returns
The number of elements in the container returned by criterion_test. Generally, a non-zero value corresponds to a failure to meet the criterion tested by criterion_test.
Definition at line 132 of file validate_system.h.
 {
     string_list_type test_results = criterion_test();
     std::string new_message = form_message(test_results);
     message += new_message;
     return test_results.size();
 }
string_set_to_string_vector()
string_vector string_set_to_string_vector (string_set ss)
Converts a string_set to a string_vector
Definition at line 667 of file validate_system.cpp.
 {
     string_vector sv;
     for (std::string const& s : ss) {
         sv.push_back(s);
     }
     return sv;
 }
Referenced by Standalone_SS::get_outputs(), ed_leaf_photosynthesis::get_reference_inputs(), ed_leaf_photosynthesis::get_reference_outputs(), get_unknown_quantities(), and simultaneous_equations::simultaneous_equations().
string_vector_difference()
string_vector string_vector_difference (string_vector find_elements_of_this_vector, string_vector that_are_not_in_this_one)
Definition at line 689 of file validate_system.cpp.
 {
     string_vector difference;
     for (std::string const& s : find_elements_of_this_vector) {
         insert_quantity_if_undefined(s, that_are_not_in_this_one, difference);
     }
     return difference;
 }
References insert_quantity_if_undefined().
Referenced by ed_leaf_photosynthesis::get_reference_inputs(), and validate_simultaneous_equations_inputs().
string_vector_to_string_set()
string_set string_vector_to_string_set (string_vector sv)
Creates a string_set from all the elements of a string_vector.
Definition at line 680 of file validate_system.cpp.
 {
     string_set ss;
     for (std::string const& s : sv) {
         ss.insert(s);
     }
     return ss;
 }
Referenced by find_strictly_required_inputs().
validate_system_inputs()
bool validate_system_inputs (std::string & message, state_map initial_state, state_map invariant_params, state_vector_map varying_params, string_vector ss_module_names, string_vector deriv_module_names)
Checks over a group of quantities and modules to ensure they can be used to create a valid system.
Parameters
[in,out] message Validation feedback is added to this string.
Returns
true if the inputs are valid, false otherwise.
The following criteria are used to determine validity:
Each quantity is specified only once.
All module inputs are specified.
Derivatives are calculated only for quantities in the initial state.
Steady-state modules can be ordered in such a way that inputs are calculated before they are accessed.
We consider a quantity to have been "specified" (or "defined") if it is a key in one of the maps initial_state, invariant_params, or varying_params, or, if it is an output variable of one of the steady-state modules listed in ss_module_names.
Criterion 2 and criterion 4 are related: Criterion 2 requires merely that each input to a steady-state or deriv module is either a variable in the initial state, is one of the parameters, or is an output of some steady-state module. Criterion 4 goes further for the case of a steady-state module where an input quantity is provided by the output of some other steady-state module: It requires that the steady-state modules can be ordered in such a way that each of a module's input quantities that is neither a parameter or a quantity in the initial state be provided by the output of a module earlier in the list.
Notably absent from these criteria is a requirement that a derivative be calculated for every value given in the initial state. Values in the initial state that are not outputs of any deriv module are assumed to have a derivative of zero, that is, they are assumed to be constant.
Definition at line 43 of file validate_system.cpp.
 {
     size_t num_problems = 0;
     string_vector quantity_names = get_defined_quantity_names(
         std::vector<state_map>{initial_state, invariant_params, at(varying_params, 0)},
         std::vector<string_vector>{ss_module_names});
     // Criterion 1
     num_problems += process_criterion<string_vector>(
         message,
         [=]() -> string_vector { return find_duplicate_quantity_definitions(quantity_names); },
         [](string_vector string_list) -> std::string {
             return create_marked_message(
                 std::string("No quantities were defined multiple times in the inputs"),
                 std::string("The following quantities were defined more than once in the inputs:"),
                 std::string(""),
                 string_list
             );
         }
     );
     // Criterion 2
     num_problems += process_criterion<string_vector>(
         message,
         [=]() -> string_vector {
             return find_undefined_module_inputs(
                 quantity_names,
                 std::vector<string_vector>{ss_module_names, deriv_module_names}
             );
         },
         [](string_vector string_list) -> std::string {
             return create_marked_message(
                 std::string("All module inputs were properly defined"),
                 std::string("The following module inputs were not defined:"),
                 std::string(""),
                 string_list
             );
         }
     );
     // Criterion 3
     num_problems += process_criterion<string_vector>(
         message,
         [=]() -> string_vector {
             return find_undefined_module_outputs(
                 keys(initial_state),
                 std::vector<string_vector>{deriv_module_names}
             );
         },
         [](string_vector string_list) -> std::string {
             return create_marked_message(
                 std::string("All derivative module outputs were included in the initial state"),
                 std::string("The following derivative module outputs were not part of the initial state:"),
                 std::string(""),
                 string_list
             );
         }
     );
     // Criterion 4
     num_problems += process_criterion<string_vector>(
         message,
         [=]() -> string_vector {
             string_vector result {};
             if (has_cyclic_dependency(ss_module_names)) {
                 // For now, we just want a non-zero vector size.  It
                 // may, however, prove useful to display a set of
                 // modules that comprise a cyclic dependency.
                 result.push_back("");
             }
             return  result;
         },
         [](string_vector string_list) -> std::string {
             return create_marked_message(
                 std::string("There are no cyclic dependencies among the steady-state modules."),
                 std::string("The steady-state modules have a cyclic dependency."),
                 std::string(""),
                 string_list
             );
         }
     );
     return num_problems == 0;
 }
References at(), create_marked_message(), find_duplicate_quantity_definitions(), find_undefined_module_inputs(), find_undefined_module_outputs(), get_defined_quantity_names(), and keys().
Referenced by R_validate_system_inputs().
Variable Documentation
failure_mark
const std::string failure_mark { "[fail] " }
Definition at line 19 of file validate_system.h.
Referenced by create_marked_message().
success_mark
const std::string success_mark { "[pass] " }
Definition at line 18 of file validate_system.h.
Referenced by create_marked_message().