The BioCro C++ Library: /github/workspace/source/src/module_library/ball_berry.hpp File Reference
ball_berry.hpp File Reference
Functions
double ball_berry (double assimilation, double atmospheric_co2_concentration, double atmospheric_relative_humidity, double beta0, double beta1)
double water_saturation_vapor_pressure (double Tkelvin)
Function Documentation
ball_berry()
double ball_berry (double assimilation, double atmospheric_co2_concentration, double atmospheric_relative_humidity, double beta0, double beta1)
Definition at line 14 of file ball_berry.cpp.
Referenced by c4photoC(), ball_berry_module::do_operation(), and collatz_leaf::do_operation().
water_saturation_vapor_pressure()
double water_saturation_vapor_pressure (double temperature)
Calculate saturation vapor pressure of water from air temperature.
This is the Arden Buck equation. http://en.wikipedia.org/wiki/Arden_Buck_equation temperature has units of kelvin.
Definition at line 77 of file ball_berry.cpp.