The BioCro C++ Library: boost_rkck54_system_solver< state_type > Class Template Reference
boost_rkck54_system_solver< state_type > Class Template Reference
#include <boost_solvers.h>
Public Member Functions
boost_rkck54_system_solver (double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps)
Public Member Functions inherited from boost_system_solver< state_type >
boost_system_solver (std::string solver_name, bool check_adaptive_compatible, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps)
Public Member Functions inherited from system_solver
system_solver (std::string solver_name, bool check_adaptive_compatible, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps)
virtual ~system_solver ()
state_vector_map solve (std::shared_ptr< System > sys)
std::string generate_info_report () const
std::string generate_solve_report () const
Private Member Functions
void do_boost_solve (SystemCaller syscall, push_back_state_and_time< state_type > &observer) override
std::string get_boost_param_info () const override
Additional Inherited Members
Protected Member Functions inherited from boost_system_solver< state_type >
template<class stepper_type >
void run_integrate_const (stepper_type stepper, SystemCaller syscall, push_back_state_and_time< state_type > observer)
Protected Member Functions inherited from system_solver
double get_output_step_size () const
double get_adaptive_rel_error_tol () const
double get_adaptive_abs_error_tol () const
int get_adaptive_max_steps () const
Detailed Description
template<class state_type>
class boost_rkck54_system_solver< state_type >
Definition at line 178 of file boost_solvers.h.
Constructor & Destructor Documentation
boost_rkck54_system_solver()
boost_rkck54_system_solver (double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps) inline
Definition at line 181 of file boost_solvers.h.
Member Function Documentation
do_boost_solve()
void do_boost_solve (SystemCaller syscall, push_back_state_and_time< state_type > & observer) inline override private virtual
Implements boost_system_solver< state_type >.
Definition at line 188 of file boost_solvers.h.
References system_solver::get_adaptive_abs_error_tol(), system_solver::get_adaptive_rel_error_tol(), and boost_system_solver< state_type >::run_integrate_const().
get_boost_param_info()
std::string get_boost_param_info () const inline override private virtual
Implements boost_system_solver< state_type >.
Definition at line 199 of file boost_solvers.h.
References system_solver::get_adaptive_abs_error_tol(), system_solver::get_adaptive_max_steps(), and system_solver::get_adaptive_rel_error_tol().
The documentation for this class was generated from the following file:
/github/workspace/source/src/system_solver_library/boost_solvers.h