The BioCro C++ Library: ten_layer_c4_canopy Class Reference
ten_layer_c4_canopy Class Reference
A child class of multilayer_canopy_photosynthesis where:
#include <multilayer_c4_canopy.h>
Public Member Functions
ten_layer_c4_canopy (const std::unordered_map< std::string, double > *input_parameters, std::unordered_map< std::string, double > *output_parameters)
Public Member Functions inherited from multilayer_canopy_photosynthesis< ten_layer_canopy_properties, c4_leaf_photosynthesis >
multilayer_canopy_photosynthesis (const std::string &module_name, const int &nlayers, const std::unordered_map< std::string, double > *input_parameters, std::unordered_map< std::string, double > *output_parameters)
Constructor for a multilayer canopy photosynthesis module, which initializes the leaf module and prepares to pass inputs to it from the canopy module.
Public Member Functions inherited from SteadyModule
SteadyModule (const std::string &module_name, bool adaptive_compatible=true)
Public Member Functions inherited from Module
Module (std::string const &module_name, bool const &deriv, bool const &adaptive_compatible)
virtual ~Module ()=0
std::string get_name () const
bool is_deriv () const
bool is_adaptive_compatible () const
void run () const
Static Public Member Functions
static std::vector< std::string > get_inputs ()
static std::vector< std::string > get_outputs ()
static std::string get_description ()
Private Member Functions
void do_operation () const
Static Private Attributes
static const int nlayers = 10
Additional Inherited Members
Protected Member Functions inherited from multilayer_canopy_photosynthesis< ten_layer_canopy_properties, c4_leaf_photosynthesis >
void run () const
Protected Member Functions inherited from SteadyModule
void update (double *output_ptr, const double &value) const
Protected Member Functions inherited from Module
double get_val_debug (const double *ptr, const std::string name) const
Static Protected Member Functions inherited from multilayer_canopy_photosynthesis< ten_layer_canopy_properties, c4_leaf_photosynthesis >
static std::vector< std::string > generate_inputs (int nlayers)
static std::vector< std::string > generate_outputs (int nlayers)
Static Protected Attributes inherited from Module
static const double eps = 1e-10
Detailed Description
A child class of multilayer_canopy_photosynthesis where:
The canopy module is set to the ten_layer_canopy_properties module
The leaf module is set to the c4_leaf_photosynthesis module
The number of layers is set to 10 Instances of this class can be created using the module factory.
Definition at line 17 of file multilayer_c4_canopy.h.
Constructor & Destructor Documentation
ten_layer_c4_canopy()
ten_layer_c4_canopy (const std::unordered_map< std::string, double > * input_parameters, std::unordered_map< std::string, double > * output_parameters) inline
Definition at line 20 of file multilayer_c4_canopy.h.
Member Function Documentation
do_operation()
void do_operation () const private virtual
Reimplemented from Module.
Definition at line 55 of file multilayer_c4_canopy.h.
References multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::run().
get_description()
static std::string get_description () static
get_inputs()
std::vector< std::string > get_inputs () static
Definition at line 43 of file multilayer_c4_canopy.h.
References multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::generate_inputs(), and nlayers.
get_outputs()
std::vector< std::string > get_outputs () static
Definition at line 49 of file multilayer_c4_canopy.h.
References multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::generate_outputs(), and nlayers.
Member Data Documentation
nlayers
const int nlayers = 10 static private
Definition at line 36 of file multilayer_c4_canopy.h.
Referenced by get_inputs(), and get_outputs().
The documentation for this class was generated from the following file:
/github/workspace/source/src/module_library/multilayer_c4_canopy.h