The BioCro C++ Library: /github/workspace/source/src/R_modules.cpp File Reference
R_modules.cpp File Reference
#include <Rinternals.h>
#include <vector>
#include <string>
#include "R_helper_functions.h"
#include "state_map.h"
#include "module_library/module_wrapper_factory.h"
#include "modules.h"
Functions
SEXP R_get_module_info (SEXP module_name_input, SEXP verbose)
SEXP R_test_module (SEXP module_name_input, SEXP input_parameters)
Function Documentation
R_get_module_info()
SEXP R_get_module_info (SEXP module_name_input, SEXP verbose)
Definition at line 11 of file R_modules.cpp.
References list_from_map(), make_vector(), and parameters.
R_test_module()
SEXP R_test_module (SEXP module_name_input, SEXP input_parameters)
Definition at line 116 of file R_modules.cpp.
References list_from_map(), make_vector(), map_from_list(), and parameters.