The BioCro C++ Library: system_solver Class Reference
system_solver Class Reference abstract
#include <system_solver.h>
Public Member Functions
system_solver (std::string solver_name, bool check_adaptive_compatible, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps)
virtual ~system_solver ()
state_vector_map solve (std::shared_ptr< System > sys)
std::string generate_info_report () const
std::string generate_solve_report () const
Protected Member Functions
double get_output_step_size () const
double get_adaptive_rel_error_tol () const
double get_adaptive_abs_error_tol () const
int get_adaptive_max_steps () const
Private Member Functions
virtual state_vector_map do_solve (std::shared_ptr< System > sys)=0
virtual state_vector_map handle_adaptive_incompatibility (std::shared_ptr< System > sys)
virtual std::string get_param_info () const =0
virtual std::string get_solution_info () const =0
Private Attributes
const std::string solver_name
const bool check_adaptive_compatible
double output_step_size
double adaptive_rel_error_tol
double adaptive_abs_error_tol
int adaptive_max_steps
bool solve_method_has_been_called = false
Detailed Description
Definition at line 12 of file system_solver.h.
Constructor & Destructor Documentation
system_solver()
system_solver (std::string solver_name, bool check_adaptive_compatible, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps) inline
Definition at line 15 of file system_solver.h.
~system_solver()
virtual ~system_solver () inline virtual
Definition at line 28 of file system_solver.h.
Member Function Documentation
do_solve()
virtual state_vector_map do_solve (std::shared_ptr< System > sys) private pure virtual
Implemented in boost_system_solver< state_type >, boost_system_solver< boost::numeric::ublas::vector< double > >, auto_solver< state_type >, and homemade_euler_solver< state_type >.
Referenced by solve().
generate_info_report()
std::string generate_info_report () const inline
Definition at line 32 of file system_solver.h.
References get_param_info(), and solver_name.
generate_solve_report()
std::string generate_solve_report () const inline
Definition at line 34 of file system_solver.h.
References get_solution_info(), and solve_method_has_been_called.
get_adaptive_abs_error_tol()
double get_adaptive_abs_error_tol () const inline protected
Definition at line 46 of file system_solver.h.
References adaptive_abs_error_tol.
Referenced by boost_rkck54_system_solver< state_type >::do_boost_solve(), boost_rsnbrk_system_solver::do_boost_solve(), boost_rkck54_system_solver< state_type >::get_boost_param_info(), and boost_rsnbrk_system_solver::get_boost_param_info().
get_adaptive_max_steps()
int get_adaptive_max_steps () const inline protected
Definition at line 47 of file system_solver.h.
References adaptive_max_steps.
Referenced by boost_rkck54_system_solver< state_type >::get_boost_param_info(), and boost_rsnbrk_system_solver::get_boost_param_info().
get_adaptive_rel_error_tol()
double get_adaptive_rel_error_tol () const inline protected
Definition at line 45 of file system_solver.h.
References adaptive_rel_error_tol.
Referenced by boost_rkck54_system_solver< state_type >::do_boost_solve(), boost_rsnbrk_system_solver::do_boost_solve(), boost_rkck54_system_solver< state_type >::get_boost_param_info(), and boost_rsnbrk_system_solver::get_boost_param_info().
get_output_step_size()
double get_output_step_size () const inline protected
Definition at line 44 of file system_solver.h.
References output_step_size.
Referenced by boost_system_solver< boost::numeric::ublas::vector< double > >::get_param_info().
get_param_info()
virtual std::string get_param_info () const private pure virtual
Implemented in auto_solver< state_type >, boost_system_solver< state_type >, and homemade_euler_solver< state_type >.
Referenced by generate_info_report().
get_solution_info()
virtual std::string get_solution_info () const private pure virtual
Implemented in auto_solver< state_type >, boost_system_solver< state_type >, and homemade_euler_solver< state_type >.
Referenced by generate_solve_report().
handle_adaptive_incompatibility()
state_vector_map handle_adaptive_incompatibility (std::shared_ptr< System > sys) inline private virtual
Reimplemented in auto_solver< state_type >.
Definition at line 68 of file system_solver.h.
References solver_name.
Referenced by solve().
solve()
state_vector_map solve (std::shared_ptr< System > sys)
Definition at line 3 of file system_solver.cpp.
References check_adaptive_compatible, do_solve(), handle_adaptive_incompatibility(), and solve_method_has_been_called.
Member Data Documentation
adaptive_abs_error_tol
double adaptive_abs_error_tol private
Definition at line 55 of file system_solver.h.
Referenced by get_adaptive_abs_error_tol().
adaptive_max_steps
int adaptive_max_steps private
Definition at line 56 of file system_solver.h.
Referenced by get_adaptive_max_steps().
adaptive_rel_error_tol
double adaptive_rel_error_tol private
Definition at line 54 of file system_solver.h.
Referenced by get_adaptive_rel_error_tol().
check_adaptive_compatible
const bool check_adaptive_compatible private
Definition at line 51 of file system_solver.h.
Referenced by boost_system_solver< boost::numeric::ublas::vector< double > >::boost_system_solver(), and solve().
output_step_size
double output_step_size private
Definition at line 53 of file system_solver.h.
Referenced by get_output_step_size().
solve_method_has_been_called
bool solve_method_has_been_called = false private
Definition at line 58 of file system_solver.h.
Referenced by generate_solve_report(), and solve().
solver_name
const std::string solver_name private
Definition at line 50 of file system_solver.h.
Referenced by boost_system_solver< boost::numeric::ublas::vector< double > >::boost_system_solver(), generate_info_report(), and handle_adaptive_incompatibility().
The documentation for this class was generated from the following files:
/github/workspace/source/src/system_solver.h
/github/workspace/source/src/system_solver.cpp