The BioCro C++ Library: System Class Reference
System Class Reference
Defines a system of differential equations. Intended to be passed to a system_solver object.
#include <system.h>
Public Member Functions
System (state_map const &init_state, state_map const &invariant_params, state_vector_map const &varying_params, string_vector const &ss_module_names, string_vector const &deriv_module_names)
size_t get_ntimes () const
bool is_adaptive_compatible () const
Check that the system is adaptive compatible based on the modules that it uses.
template<typename state_type >
void get_state (state_type &x) const
Updates the state parameter x with the current values of all the state parameters.
template<typename state_type , typename time_type >
void update (const state_type &x, const time_type &t)
Updates all quantities (including ones calculated by steady state modules) based on the input state and time.
template<typename state_type , typename time_type >
void operator() (const state_type &x, state_type &dxdt, const time_type &t)
Calculates a derivative given an input state and time.
std::vector< const double * > get_quantity_access_ptrs (string_vector quantity_names) const
Returns pointers that can be used to access quantity values from the system's central map of quantities.
string_vector get_state_parameter_names () const
string_vector get_output_param_names () const
Returns a vector of the names of all quantities that change throughout a simulation.
int get_ncalls () const
void reset_ncalls ()
std::string generate_startup_report () const
std::string generate_usage_report () const
void reset ()
Resets all quantities back to their original values.
Private Member Functions
void update_varying_params (double time_indx)
Gets values from the varying parameters at the input time (double)
template<typename time_type >
void update_varying_params (time_type time_indx)
Gets values of the varying parameters using a discrete time index (e.g.
template<class vector_type >
void update_state_params (vector_type const &new_state)
Updates the system's internally stored state parameter values to the new ones in new_state.
void run_steady_state_modules ()
Runs all the steady state modules.
template<class vector_type >
void run_derivative_modules (vector_type &derivs)
Calculates a derivative from the internally stored quantity map by running all the derivative modules.
Private Attributes
const state_map initial_state
const state_map invariant_parameters
const state_vector_map varying_parameters
string_vector steady_state_module_names
const string_vector derivative_module_names
state_map quantities
state_map module_output_map
module_vector steady_state_modules
module_vector derivative_modules
double * timestep_ptr
std::vector< double * > state_ptrs
std::vector< double * > steady_state_ptrs
std::vector< std::pair< double *, const double * > > state_ptr_pairs
std::vector< std::pair< double *, const double * > > steady_state_ptr_pairs
std::vector< std::pair< double *, const std::vector< double > * > > varying_ptr_pairs
int ncalls = 0
std::string startup_message
Detailed Description
Defines a system of differential equations. Intended to be passed to a system_solver object.
Definition at line 17 of file system.h.
Constructor & Destructor Documentation
System()
System (state_map const & init_state, state_map const & invariant_params, state_vector_map const & varying_params, string_vector const & ss_module_names, string_vector const & deriv_module_names)
Definition at line 5 of file system.cpp.
Member Function Documentation
generate_startup_report()
std::string generate_startup_report () const inline
Definition at line 60 of file system.h.
References startup_message.
generate_usage_report()
std::string generate_usage_report () const inline
Definition at line 62 of file system.h.
References ncalls.
get_ncalls()
int get_ncalls () const inline
Definition at line 58 of file system.h.
References ncalls.
get_ntimes()
size_t get_ntimes () const inline
Definition at line 28 of file system.h.
References varying_parameters.
get_output_param_names()
string_vector get_output_param_names () const
Returns a vector of the names of all quantities that change throughout a simulation.
The quantities that change are (1) the quantites that are calculated using differential equations; these should coincide with all quantities in the initial state; (2) the varying known parameters; (3) the secondary variables, that is, the variables that are outputs of steady-state modules.
Note
Even though each variable in the initial state should correspond to a derivative calculated by some derivative module, it is possible and permissible to have some variable \(v\) in the initial state that doesn't correspond to any such derivative. In that case, a differential equation \(dv/dt = 0\) is assumed. So such variables in fact do not change during the course of the simulation.
Definition at line 151 of file system.cpp.
References at(), get_defined_quantity_names(), initial_state, steady_state_module_names, and varying_parameters.
get_quantity_access_ptrs()
std::vector< const double * > get_quantity_access_ptrs (string_vector quantity_names) const
Returns pointers that can be used to access quantity values from the system's central map of quantities.
Definition at line 124 of file system.cpp.
References quantities.
get_state()
void get_state (state_type & x) const
Updates the state parameter x with the current values of all the state parameters.
Parameters
[out] x An object capable of containing the state, typically either std::vector<double> or boost::numeric::ublas::vector<double>.
Definition at line 122 of file system.h.
References state_ptr_pairs.
Referenced by R_Gro_deriv(), and R_Gro_ode().
get_state_parameter_names()
string_vector get_state_parameter_names () const inline
Definition at line 54 of file system.h.
References initial_state, and keys().
Referenced by R_Gro_deriv(), and R_Gro_ode().
is_adaptive_compatible()
bool is_adaptive_compatible () const inline
Check that the system is adaptive compatible based on the modules that it uses.
Definition at line 36 of file system.h.
References check_adaptive_compatible(), derivative_modules, and steady_state_modules.
operator()()
void operator() (const state_type & x, state_type & dxdt, const time_type & t)
Calculates a derivative given an input state and time.
Function signature is set by the boost::odeint library.
Parameters
[in] x values of the state parameters
[out] dxdt derivatives of the state parameters calculated using x and t
[in] t time value
Definition at line 150 of file system.h.
References ncalls, run_derivative_modules(), and update().
reset()
void reset ()
Resets all quantities back to their original values.
Definition at line 75 of file system.cpp.
References initial_state, quantities, run_steady_state_modules(), and update_varying_params().
reset_ncalls()
void reset_ncalls () inline
Definition at line 59 of file system.h.
References ncalls.
run_derivative_modules()
void run_derivative_modules (vector_type & dxdt) private
Calculates a derivative from the internally stored quantity map by running all the derivative modules.
Parameters
[out] dxdt a vector for storing the derivative (passed by reference for speed)
Definition at line 185 of file system.h.
References derivative_modules, state_ptr_pairs, state_ptrs, and timestep_ptr.
Referenced by operator()().
run_steady_state_modules()
void run_steady_state_modules () private
Runs all the steady state modules.
Definition at line 104 of file system.cpp.
References steady_state_modules, steady_state_ptr_pairs, and steady_state_ptrs.
Referenced by reset(), and update().
update()
void update (const state_type & x, const time_type & t)
Updates all quantities (including ones calculated by steady state modules) based on the input state and time.
Parameters
[in] x the state
[in] t the time
Definition at line 135 of file system.h.
References run_steady_state_modules(), update_state_params(), and update_varying_params().
Referenced by operator()().
update_state_params()
void update_state_params (vector_type const & new_state) private
Updates the system's internally stored state parameter values to the new ones in new_state.
Definition at line 172 of file system.h.
References state_ptr_pairs.
Referenced by update().
update_varying_params() [1/2]
void update_varying_params (double time_indx) private
Gets values from the varying parameters at the input time (double)
Definition at line 85 of file system.cpp.
References varying_ptr_pairs.
Referenced by reset(), and update().
update_varying_params() [2/2]
void update_varying_params (time_type time_indx) private
Gets values of the varying parameters using a discrete time index (e.g.
int or size_t)
Definition at line 161 of file system.h.
References varying_ptr_pairs.
Member Data Documentation
derivative_module_names
const string_vector derivative_module_names private
Definition at line 77 of file system.h.
derivative_modules
module_vector derivative_modules private
Definition at line 85 of file system.h.
Referenced by is_adaptive_compatible(), and run_derivative_modules().
initial_state
const state_map initial_state private
Definition at line 73 of file system.h.
Referenced by get_output_param_names(), get_state_parameter_names(), and reset().
invariant_parameters
const state_map invariant_parameters private
Definition at line 74 of file system.h.
module_output_map
state_map module_output_map private
Definition at line 81 of file system.h.
ncalls
int ncalls = 0 private
Definition at line 110 of file system.h.
Referenced by generate_usage_report(), get_ncalls(), operator()(), and reset_ncalls().
quantities
state_map quantities private
Definition at line 80 of file system.h.
Referenced by get_quantity_access_ptrs(), and reset().
startup_message
std::string startup_message private
Definition at line 111 of file system.h.
Referenced by generate_startup_report().
state_ptr_pairs
std::vector<std::pair<double*, const double*> > state_ptr_pairs private
Definition at line 91 of file system.h.
Referenced by get_state(), run_derivative_modules(), and update_state_params().
state_ptrs
std::vector<double*> state_ptrs private
Definition at line 89 of file system.h.
Referenced by run_derivative_modules().
steady_state_module_names
string_vector steady_state_module_names private
Definition at line 76 of file system.h.
Referenced by get_output_param_names().
steady_state_modules
module_vector steady_state_modules private
Definition at line 84 of file system.h.
Referenced by is_adaptive_compatible(), and run_steady_state_modules().
steady_state_ptr_pairs
std::vector<std::pair<double*, const double*> > steady_state_ptr_pairs private
Definition at line 92 of file system.h.
Referenced by run_steady_state_modules().
steady_state_ptrs
std::vector<double*> steady_state_ptrs private
Definition at line 90 of file system.h.
Referenced by run_steady_state_modules().
timestep_ptr
double* timestep_ptr private
Definition at line 88 of file system.h.
Referenced by run_derivative_modules().
varying_parameters
const state_vector_map varying_parameters private
Definition at line 75 of file system.h.
Referenced by get_ntimes(), and get_output_param_names().
varying_ptr_pairs
std::vector<std::pair<double*, const std::vector<double>*> > varying_ptr_pairs private
Definition at line 93 of file system.h.
Referenced by update_varying_params().
The documentation for this class was generated from the following files:
/github/workspace/source/src/system.h
/github/workspace/source/src/system.cpp