The BioCro C++ Library: se_solver_rand Namespace Reference
se_solver_rand Namespace Reference
Functions
std::mt19937 eng (rd())
std::uniform_real_distribution< double > dist (0, std::nextafter(1, std::numeric_limits< double >::max()))
double rand_01 ()
Variables
std::random_device rd
Function Documentation
dist()
std::uniform_real_distribution<double> se_solver_rand::dist (0 , std::nextafter(1, std::numeric_limits< double >::max()))
Referenced by rand_01().
eng()
std::mt19937 se_solver_rand::eng (rd())
Referenced by rand_01().
rand_01()
double se_solver_rand::rand_01 ()
Definition at line 21 of file se_solver.cpp.
References dist(), and eng().
Referenced by se_solver::adjust_bad_guess().
Variable Documentation
rd
std::random_device rd
Definition at line 12 of file se_solver.cpp.
Referenced by collatz_photoC().